=== paparazzi/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (doc,settings_file*,settings*,dep?,autoload*,header?,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT doc (description,(define|configure|section)*)>
<!ELEMENT settings_file (file*)>
<!ELEMENT settings (dl_settings?)>
<!ELEMENT dep (depends?,conflicts?,provides?)>
<!ELEMENT depends (#PCDATA)>
<!ELEMENT conflicts (#PCDATA)>
<!ELEMENT provides (#PCDATA)>
<!ELEMENT autoload EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|include|flag|file|file_arch|raw|test)*>
<!ELEMENT test (configure|define|include|file|file_arch|shell)*>
<!ELEMENT section (define|configure)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT include EMPTY>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT shell EMPTY>
<!ELEMENT raw (#PCDATA)>
<!ELEMENT dl_settings (dl_setting|dl_settings)+>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED
task CDATA #IMPLIED>

<!ATTLIST autoload
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST event
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA #IMPLIED
firmware CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST section
name CDATA #REQUIRED
prefix CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #IMPLIED
case CDATA #IMPLIED
default CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
integer CDATA #IMPLIED
unit CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST include
name CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST shell
cmd CDATA #REQUIRED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST settings_file
name CDATA #REQUIRED
>

<!ATTLIST settings
name CDATA #IMPLIED
target CDATA #IMPLIED
>

<!ATTLIST dl_settings
name CDATA #IMPLIED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ATTLIST test
arch CDATA #IMPLIED
firmware CDATA #IMPLIED
>

=== paparazzi/paparazzi/conf/modules/gps_uavcan.xml
<!DOCTYPE module SYSTEM "module.dtd">
<module name="gps_uavcan" dir="gps" task="sensors">
  <doc>
    <description>UAVCAN gps module. Handle uavcan.equipment.gnss.Fix2 message (1063).</description>
    <define name="GPS_UAVCAN_USE_NODE_ID" value="TRUE|FALSE" description="Use source node ID as ABI ID (default:FALSE)"/>
  </doc>
  <dep>
    <depends>uavcan,gps</depends>
    <provides>gps</provides>
  </dep>
  <header>
    <file name="gps_uavcan.h"/>
  </header>
  <init fun="gps_uavcan_init()"/>
  <makefile>
    <file name="gps_uavcan.c"/>
    <!-- Load DSDL generated files-->
    <include name="$(PAPARAZZI_HOME)/var/include/DSDLcode/include"/>
    <file name="uavcan.equipment.gnss.Fix2.c" dir="$(PAPARAZZI_HOME)/var/include/DSDLcode/src"/>
    <define name="PRIMARY_GPS" value="GPS_UAVCAN"/>
    <raw>
      $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/gps/gps_uavcan.h\"
    </raw>
        <raw>
          ifdef SECONDARY_GPS
          ifneq (,$(findstring $(SECONDARY_GPS), uavcan))
          # this is the secondary GPS
          $(TARGET).CFLAGS += -DGPS_SECONDARY_TYPE_H=\"modules/gps/gps_uavcan.h\"
          $(TARGET).CFLAGS += -DSECONDARY_GPS=GPS_UAVCAN
          else
          $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/gps/gps_uavcan.h\"
          $(TARGET).CFLAGS += -DPRIMARY_GPS=GPS_UAVCAN
          endif
          else
          # plain old single GPS usage
          $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/gps/gps_uavcan.h\"
          endif
    </raw>
    <test>
      <include name="$(PAPARAZZI_HOME)/sw/ext/dronecan/libcanard"/>
    </test>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/flight_recorder.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="flight_recorder" dir="loggers">
  <doc>
    <description>
      Record flight data according to your telemetry file.
      Data are stored on a SD card with the pprzlog format.
      Currently only supported on Apogee/Fixedwing using chibios implementation.
      The selected telemetry file should include a FlightRecorder process.
    </description>
    <configure name="FLIGHTRECORDER_SDLOG" value="TRUE|FALSE" description="Enable/disable logging on internal SD card (default=TRUE)"/>
    <define name="FLIGHTRECORDER_DEVICE" value="dev" description="Device to be used when not internal SD card (ex: uart0)"/>
  </doc>
  <header>
    <file name="flight_recorder.h"/>
  </header>
  <init fun="flight_recorder_init()"/>
  <periodic fun="flight_recorder_periodic()" freq="100" autorun="TRUE"/>
  <makefile target="ap">
    <file name="flight_recorder.c"/>
    <define name="FLIGHTRECORDER_SDLOG" cond="ifneq (FALSE,$(findstring $(FLIGHTRECORDER_SDLOG),FALSE))"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/extra_dl.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="extra_dl" dir="datalink">
  <doc>
    <description>Extra datalink (PPRZ transport)</description>
    <configure name="EXTRA_DL_PORT" value="UARTX|UDPX" description="Select port for extra datalink"/>
    <configure name="EXTRA_DL_BAUD" value="B57600" description="Baudrate for extra datalink if link device is UART"/>
  </doc>
  <header>
    <file name="extra_pprz_dl.h"/>
  </header>
  <init fun="extra_pprz_dl_init()"/>
  <periodic fun="extra_pprz_dl_periodic()" freq="PERIODIC_FREQUENCY" autorun="TRUE"/>
  <event fun="ExtraDatalinkEvent()"/>
  <makefile target="ap">
    <configure name="EXTRA_DL_PORT" default="uart1" case="upper|lower"/>
    <define name="EXTRA_DOWNLINK_DEVICE" value="$(EXTRA_DL_PORT_LOWER)"/>
    <define name="USE_$(EXTRA_DL_PORT_UPPER)"/>
    <raw>
      ifneq (,$(findstring udp,$(EXTRA_DL_PORT_LOWER)))
      include $(CFG_SHARED)/udp.makefile
      else
      EXTRA_DL_BAUD ?= B57600
      $(TARGET).CFLAGS += -D$(EXTRA_DL_PORT_UPPER)_BAUD=$(EXTRA_DL_BAUD)
      endif
    </raw>
    <file name="extra_pprz_dl.c"/>
    <file name="pprz_transport.c" dir="pprzlink/src"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/tune_airspeed.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="tune_airspeed" dir="nav">
  <doc>
    <description>NAV AIRSPEED.
      Navigation Airspeeds to be called from the flightplan.
      The included settings allow tuning of your different airspeeds
      In your flightplans you call the airspeeds with
      set var=v_ctl_auto_airspeed_setpoint value=nav_airspeed_nominal_setting
      set var=v_ctl_auto_airspeed_setpoint value=nav_airspeed_tracking_setting
      set var=v_ctl_auto_airspeed_setpoint value=nav_airspeed_landing_setting
      attitude pitch=DegOfRad(nav_takeoff_pitch_setting) ...
    </description>
    <define name="NOMINAL_AIRSPEED" value="15" description="m/s (required))"/>
    <define name="TRACKING_AIRSPEED" value="20" description="m/s (default: (1.25f * NOMINAL_AIRSPEED))"/>
    <define name="LANDING_AIRSPEED" value="12" description="m/s (default: (0.8f * NOMINAL_AIRSPEED)"/>
    </doc>
  <settings>
    <dl_settings name="control">
      <dl_settings name="airspeed">
        <dl_setting max="50" min="5" step="0.5" var="nav_airspeed_nominal_setting" shortname="nominal"/>
        <dl_setting max="50" min="5" step="0.5" var="nav_airspeed_tracking_setting" shortname="tracking"/>
        <dl_setting max="50" min="5" step="0.5" var="nav_airspeed_landing_setting" shortname="landing"/>
        <dl_setting max="80" min="-10" step="0.5" var="nav_takeoff_pitch_setting" shortname="takeoff_pitch" unit="rad" alt_unit="deg" />
      </dl_settings>
    </dl_settings>
  </settings>
  <header>
    <file name="nav_airspeed.h"/>
  </header>
  <makefile target="!fbw">
    <file name="nav_airspeed.c"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/board_tmotor_aiof7.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="board_tmotor_aiof7" dir="boards">
  <doc>
    <description>
      Autoload several onboard sensors for the T-Motor aiof7 board with proper configuration
      - IMU (MPU6500) 
      - Baro (BMP280 SPI)
      - Mag (Externe)
    </description>
  </doc>
  <dep>
    <depends>imu_mpu6000,baro_bmp280</depends> 
  </dep>
  <makefile target="!sim|nps|fbw">
    <configure name="IMU_SPI_DEV" value="spi1" case="upper|lower"/>
    <configure name="IMU_SPI_SLAVE_IDX" value="SPI_SLAVE0"/>
    <define name="TMOTOR_AIO_IMU_ROT" value=".body_to_sensor={{16383,0,0,0,-16383,0,0,0,-16382}}"/>
    <define name="TMOTOR_AIO_MAG_ROT" value=".body_to_sensor={{11585,11585,0,-11585,11585,0,0,0,16382}}"/>

    <configure name="BMP280_USE_SPI" value="TRUE"/>
    <configure name="BMP280_DEV" value="spi3"/>
    <configure name="BMP280_SLAVE_IDX" value="SPI_SLAVE3"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/eff_scheduling_rotwing_V2.xml
<!DOCTYPE module SYSTEM "module.dtd">
<module name="eff_scheduling_rotwing_V2" dir="ctrl">
  <doc>
    <description>T
      The control effectiveness scheduler for the rotating wing quadplane drone type
     - it requires a servo called ROTATION_MECH
    </description>
    <section name="ROTWING" prefix="ROTWING_EFF_SCHED_">
      <define name="IXX_BODY" value="0"  description=""/>
      <define name="IYY_BODY" value="0"  description=""/>
      <define name="IZZ" value="0"       description=""/>
      <define name="IXX_WING" value="0"  description=""/>
      <define name="IYY_WING" value="0"  description=""/>
      <define name="M" value="0"         description=""/>
      <define name="ROLL_ARM" value="0"  description=""/>
      <define name="PITCH_ARM" value="0" description=""/>
      <define name="HOVER_DF_DPPRZ" value="0" description=""/>
      <define name="HOVER_ROLL_PITCH_COEF" value="{0,0}" description=""/>
    </section>
  </doc>
    <settings>
   <dl_settings>
     <dl_settings NAME="eff_sched">
       <dl_setting var="ele_min"            min="0"       step="100"   max="6400"  shortname="ele_min"/> 
       <dl_setting var="ele_eff"            min="5"       step="0.5"   max="50"    shortname="ele_eff"/> 
       <dl_setting var="airspeed_fake_on"   min="0"       step="1"     max="1"     values="OFF|ON" shortname="bool_airspeed_fake"/> 
       <dl_setting var="airspeed_fake"      min="0"       step="0.001" max="20"    shortname="airspeed_fake"/>     
     </dl_settings>
   </dl_settings>
  </settings>
  <header>
    <file name="eff_scheduling_rotwing_V2.h"/>
  </header>
  <init fun="eff_scheduling_rotwing_init()"/>
  <periodic fun="eff_scheduling_rotwing_periodic()"/>
  <makefile>
    <file name="eff_scheduling_rotwing_V2.c"/>
    <test firmware="rotorcraft">
      <define name="ROTWING_EFF_SCHED_IXX_BODY" value="1"/>
      <define name="ROTWING_EFF_SCHED_IYY_BODY" value="1"/>
      <define name="ROTWING_EFF_SCHED_IZZ"      value="1"/>
      <define name="ROTWING_EFF_SCHED_IXX_WING" value="1"/>
      <define name="ROTWING_EFF_SCHED_IYY_WING" value="1"/>
      <define name="ROTWING_EFF_SCHED_M"        value="1"/>
      <define name="M_PI"                        value="3.14"/>
      <define name="PERIODIC_FREQUENCY"          value="500.0"/>
      <define name="ACTUATORS_NB"                value="10"/>
      <define name="COMMANDS_NB_PASSIVE"         value="1"/>
      <define name="COMMANDS_NB_VIRTUAL"         value="2"/>
      <define name="COMMANDS_NB_REAL"            value="9"/>
      <define name="COMMANDS_NB_OTHER"           value="2"/>
      <define name="ANDI_OUTPUTS"                value="6"/>
      <define name="EFF_MAT_ROWS_NB"             value="6"/> 
      <define name="EFF_MAT_COLS_NB"             value="11"/>
      <define name="COMMAND_MOTOR_FRONT"         value="0"/>
      <define name="COMMAND_MOTOR_RIGHT"         value="8"/>
      <define name="COMMAND_MOTOR_BACK"          value="9"/>
      <define name="COMMAND_MOTOR_LEFT"          value="3"/>
      <define name="COMMAND_MOTOR_PUSHER"        value="10"/>
      <define name="COMMAND_ELEVATOR"            value="5"/>
      <define name="COMMAND_RUDDER"              value="6"/>
      <define name="COMMAND_AILERONS"            value="7"/>
      <define name="COMMAND_ROT_MECH"            value="11"/>
      <define name="RW_aX"                       value="0"/>
      <define name="RW_aY"                       value="1"/>
      <define name="RW_aZ"                       value="2"/>
      <define name="RW_aN"                       value="0"/>
      <define name="RW_aE"                       value="1"/>
      <define name="RW_aD"                       value="2"/>
      <define name="RW_ap"                       value="3"/>
      <define name="RW_aq"                       value="4"/>
      <define name="RW_ar"                       value="5"/>
      <define name="ZERO_ELE_PPRZ"               value="8000"/>
      <define name="ELE_MIN_AS"                  value="8.8"/>
      <define name="ELE_MAX_AS"                  value="16.0"/>
    </test>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/actuators_xvert.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="actuators_esc32" dir="actuators" task="actuators">
  <doc>
    <description>
      Actuators Driver for x-vert vtol escs
   </description>
    <configure name="ESCS_PORT" value="usb_serial" description="Port used to connect to the atmegas escs."/>
    <configure name="ESCS_BAUD" value="250000" description="Baud rate for ESCS_PORT if a UART"/>
  </doc>
  <header>
    <file name="actuators_xvert.h" dir="subsystems/actuators"/>
  </header>
  <makefile target="ap">
    <define name="ACTUATORS"/>    
    <file_arch name="actuators_xvert.c" dir="subsystems/actuators"/>
    <file_arch name="actuators_pwm_arch.c" dir="subsystems/actuators"/>
    <configure name="ESCS_PORT" default="uart1" case="upper|lower"/>
    <configure name="ESCS_BAUD" default="250000"/>
    <define name="USE_$(ESCS_PORT_UPPER)"/>
    <define name="ESCS_UART" value="$(ESCS_PORT_LOWER)"/>
    <define name="$(ESCS_PORT_UPPER)_BAUD" value="$(ESCS_BAUD)"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/system_core.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="system_core" dir="core" task="core">
  <doc>
    <description>
      Core system components meta module

      Includes: sys_time, commands, LED interfaces
    </description>
  </doc>
  <dep>
    <depends>mcu,math,state_interface,@actuators|@intermcu,settings|@no_settings</depends>
    <provides>core</provides>
  </dep>
  <header>
    <file name="commands.h"/>
    <file name="led.h" dir="."/>
  </header>
  <init fun="commands_init()"/>
  <periodic fun="LED_PERIODIC()" freq="50"/>
  <makefile>
    <configure name="SRC_BOARD" value="boards/$(BOARD)"/>
    <configure name="SRC_MODULES" value="modules"/>
    <configure name="SRC_ARCH" value="arch/$(ARCH)"/>
    <define name="BOARD_CONFIG" value="$(BOARD_CFG)"/>
    <define name="SYS_TIME_LED" value="$(SYS_TIME_LED)" cond="ifneq ($(SYS_TIME_LED),none)"/>
    <include name="$(SRC_BOARD)"/>
    <include name="$(SRC_MODULES)"/>
    <file name="sys_time.c" dir="mcu_periph"/>
    <file name="commands.c"/>
    <define name="USE_COMMANDS"/>
    <file_arch name="sys_time_arch.c" dir="mcu_periph"/>
    <file_arch name="led_hw.c" dir="." cond="ifeq ($(ARCH), stm32)"/>
    <file_arch name="led_hw.c" dir="." cond="ifeq ($(TARGET), sim)"/>
    <flag name="LDFLAGS" value="lrt" cond="ifeq ($(ARCH), linux)"/>
    <raw>
VPATH += $(PAPARAZZI_HOME)/var/share
VPATH += $(PAPARAZZI_HOME)/sw/ext
$(TARGET).ARCHDIR = $(ARCH)
    </raw>
    <test/>
  </makefile>
  <makefile target="!nps|sim">
    <define name="USE_LED"/>
  </makefile>
</module>
