=== paparazzi/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (doc,settings_file*,settings*,dep?,autoload*,header?,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT doc (description,(define|configure|section)*)>
<!ELEMENT settings_file (file*)>
<!ELEMENT settings (dl_settings?)>
<!ELEMENT dep (depends?,conflicts?,provides?)>
<!ELEMENT depends (#PCDATA)>
<!ELEMENT conflicts (#PCDATA)>
<!ELEMENT provides (#PCDATA)>
<!ELEMENT autoload EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|include|flag|file|file_arch|raw|test)*>
<!ELEMENT test (configure|define|include|file|file_arch|shell)*>
<!ELEMENT section (define|configure)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT include EMPTY>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT shell EMPTY>
<!ELEMENT raw (#PCDATA)>
<!ELEMENT dl_settings (dl_setting|dl_settings)+>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED
task CDATA #IMPLIED>

<!ATTLIST autoload
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST event
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA #IMPLIED
firmware CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST section
name CDATA #REQUIRED
prefix CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #IMPLIED
case CDATA #IMPLIED
default CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
integer CDATA #IMPLIED
unit CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST include
name CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST shell
cmd CDATA #REQUIRED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST settings_file
name CDATA #REQUIRED
>

<!ATTLIST settings
name CDATA #IMPLIED
target CDATA #IMPLIED
>

<!ATTLIST dl_settings
name CDATA #IMPLIED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ATTLIST test
arch CDATA #IMPLIED
firmware CDATA #IMPLIED
>

=== paparazzi/paparazzi/conf/modules/ahrs_int_cmpl_quat.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="ahrs_int_cmpl_quat" dir="ahrs">
  <doc>
    <description>
      AHRS using complementary filter in fixed point.
      Propagation is done in quaternion representation.

      By default uses magnetometer for heading for rotorcrafts.
      For fixedwing firmware AHRS_GRAVITY_UPDATE_COORDINATED_TURN is enabled by default and magnetometer disabled (needs GPS).

      To measure attitude angles, gyrometers measurements are integrated.
      The result of integration is accurate for short term, but gyro bias is accumulated, which results in long term errors (drift).
      On the other hand, accelerometers can be used to infer pitch/roll angles utilizing gravity vector measurement, but they suffer from noise due to vibrations.
      The measurement is then only accurate when averaged over a long term.
      Also, accelerometers alone are unable to give accurate angles when the vehicle is accelerating.
      Complementary filter takes advantage of both sensors, using a low-pass filter on accelerometer readings and high pass filter on gyrometers readings, to estimate attitude angles.

      - No danger of gimbal lock, since quaternions are used.
      - The arithmetic is fixed point and is thus suitable if the processor (on your board) has no FPU.
      - Estimates the gyro bias.
    </description>
    <configure name="USE_MAGNETOMETER" value="TRUE" description="set to FALSE to disable magnetometer"/>
    <configure name="AHRS_ALIGNER_LED" value="1" description="LED number to indicate AHRS alignment, none to disable (default is board dependent)"/>
    <define name="AHRS_MAG_UPDATE_ALL_AXES" value="FALSE|TRUE" description="Use magnetometer to update all axes and not only yaw"/>
    <define name="AHRS_USE_GPS_HEADING" value="FALSE|TRUE" description="Use GPS course to update heading"/>
    <define name="AHRS_GRAVITY_UPDATE_COORDINATED_TURN" value="FALSE|TRUE" description="Compensation of centrifugal force via GPS speed (to fly in circles with a fixedwing)"/>
    <define name="AHRS_GPS_SPEED_IN_NEGATIVE_Z_DIRECTION" value="FALSE|TRUE" description="AHRS_GRAVITY_UPDATE_COORDINATED_TURN assumes the GPS speed is in the X axis direction. Quadshot, DelftaCopter and other hybrids can have the GPS speed in the negative Z direction"/>
    <define name="AHRS_PROPAGATE_LOW_PASS_RATES" description="apply a low pass filter on rotational velocity"/>
    <define name="AHRS_BIAS_UPDATE_HEADING_THRESHOLD" value="5.0" description="don't update gyro bias if heading deviation is above this threshold in degrees"/>
    <define name="AHRS_HEADING_UPDATE_GPS_MIN_SPEED" value="5.0" description="Don't update heading from GPS course if GPS ground speed is below is this threshold in m/s"/>
    <define name="AHRS_GRAVITY_HEURISTIC_FACTOR" value="30" description="Default is 30. Reduce accelerometer cut-off frequency when the vehicle is accelerating: norm(ax,ay,az) ~ 9,81 m/s2. WARNING: when the IMU is not well damped, the norm of accelerometers never equals to 9,81 m/s2. As a result, the GRAVITY_HEURISTIC_FACTOR will reduce the accelerometer bandwith even if the vehicle is not accelerating. Set to 0 in case of vibrations"/>
    <define name="AHRS_ICQ_IMU_ID" value="ABI_BROADCAST" description="ABI sender id of IMU to use"/>
    <define name="AHRS_ICQ_MAG_ID" value="ABI_BROADCAST" description="ABI sender id of magnetometer to use"/>
    <define name="AHRS_ICQ_GPS_ID" value="GPS_MULTI_ID" description="ABI sender id of GPS to use"/>
  </doc>

  <settings>
    <dl_settings>
      <dl_settings NAME="AHRS">
        <dl_setting var="ahrs_icq.gravity_heuristic_factor" min="0" step="1" max="50" module="subsystems/ahrs/ahrs_int_cmpl_quat" shortname="g_heuristic" param="AHRS_GRAVITY_HEURISTIC_FACTOR" type="uint8" persistent="true"/>
        <dl_setting var="ahrs_icq.accel_omega" min="0.02" step="0.02" max="0.2" module="subsystems/ahrs/ahrs_int_cmpl_quat" shortname="acc_omega" param="AHRS_ACCEL_OMEGA" unit="rad/s" handler="SetAccelOmega" type="float" persistent="true"/>
        <dl_setting var="ahrs_icq.accel_zeta" min="0.7" step="0.05" max="1.5" module="subsystems/ahrs/ahrs_int_cmpl_quat" shortname="acc_zeta" param="AHRS_ACCEL_ZETA" handler="SetAccelZeta" type="float" persistent="true"/>
        <dl_setting var="ahrs_icq.mag_omega" min="0.02" step="0.01" max="0.1" module="subsystems/ahrs/ahrs_int_cmpl_quat" shortname="mag_omega" param="AHRS_MAG_OMEGA" unit="rad/s" handler="SetMagOmega" type="float" persistent="true"/>
        <dl_setting var="ahrs_icq.mag_zeta" min="0.7" step="0.05" max="1.5" module="subsystems/ahrs/ahrs_int_cmpl_quat" shortname="mag_zeta" param="AHRS_MAG_ZETA" handler="SetMagZeta" type="float" persistent="true"/>
      </dl_settings>
    </dl_settings>
  </settings>

  <autoload name="ahrs_sim"/>
  <header>
    <file name="ahrs.h" dir="subsystems"/>
  </header>

  <makefile target="!sim|fbw" firmware="fixedwing">
    <configure name="USE_MAGNETOMETER" default="0"/>
    <define name="AHRS_USE_GPS_HEADING" cond="ifneq (,$(findstring $(USE_MAGNETOMETER),0 FALSE))"/>
    <define name="AHRS_GRAVITY_UPDATE_COORDINATED_TURN"/>
  </makefile>
  <makefile target="!sim|fbw">
    <configure name="USE_MAGNETOMETER" default="1"/>

    <define name="USE_MAGNETOMETER" cond="ifeq (,$(findstring $(USE_MAGNETOMETER),0 FALSE))"/>
    <define name="AHRS_ALIGNER_LED" value="$(AHRS_ALIGNER_LED)" cond="ifneq ($(AHRS_ALIGNER_LED),none)"/>
    <define name="USE_AHRS"/>
    <define name="USE_AHRS_ALIGNER"/>

    <file name="ahrs.c" dir="subsystems"/>
    <file name="ahrs_aligner.c" dir="subsystems/ahrs"/>
    <file name="ahrs_int_cmpl_quat.c" dir="subsystems/ahrs"/>
    <file name="ahrs_int_cmpl_quat_wrapper.c" dir="subsystems/ahrs"/>
    <raw>
ifdef SECONDARY_AHRS
ifneq (,$(findstring $(SECONDARY_AHRS), icq int_cmpl_quat))
# this is the secondary AHRS
$(TARGET).CFLAGS += -DAHRS_SECONDARY_TYPE_H=\"subsystems/ahrs/ahrs_int_cmpl_quat_wrapper.h\"
$(TARGET).CFLAGS += -DSECONDARY_AHRS=ahrs_icq
else
# this is the primary AHRS
$(TARGET).CFLAGS += -DAHRS_TYPE_H=\"subsystems/ahrs/ahrs_int_cmpl_quat_wrapper.h\"
$(TARGET).CFLAGS += -DPRIMARY_AHRS=ahrs_icq
endif
else
# plain old single AHRS usage
$(TARGET).CFLAGS += -DAHRS_TYPE_H=\"subsystems/ahrs/ahrs_int_cmpl_quat_wrapper.h\"
endif
    </raw>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/stabilization_indi_hinf.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="stabilization_indi_hinf" dir="stabilization" task="control">
  <doc>
    <description>
      Hinfinity controller for INDI stabilization outer loop
    </description>

    <section name="STABILIZATION_ATTITUDE_INDI_HINF" prefix="STABILIZATION_INDI_HINF_">
      <define name="Ap" value="x" description="proportional A coef"/>
      <define name="Bp" value="x" description="proportional B coef"/>
      <define name="Cp" value="x" description="proportional C coef"/>
      <define name="Dp" value="x" description="proportional D coef"/>
      <define name="Ad" value="x" description="derivative A coef"/>
      <define name="Bd" value="x" description="derivative B coef"/>
      <define name="Cd" value="x" description="derivative C coef"/>
      <define name="Dd" value="x" description="derivative D coef"/>
    </section>
  </doc>
  <dep>
    <depends>stabilization_indi</depends>
  </dep>
  <makefile target="ap|nps" firmware="rotorcraft">
    <file name="stabilization_indi_hinf.c" dir="$(SRC_FIRMWARE)/stabilization"/>
    <test firmware="rotorcraft">
      <define name="INDI_OUTPUTS" value="4"/>
      <define name="INDI_NUM_ACT" value="4"/>
    </test>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/nav_survey_zamboni.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="nav_survey_zamboni" dir="nav">
  <doc>
    <description>
     Zamboni pattern survey for fixedwings.
    </description>
  </doc>
  <header>
    <file name="nav_survey_zamboni.h"/>
  </header>
  <makefile target="ap|sim|nps">
    <file name="nav_survey_zamboni.c"/>
    <test firmware="fixedwing">
      <define name="CTRL_TYPE_H" value="firmwares/fixedwing/guidance/guidance_v.h" type="string"/>
    </test>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/cv_opticflow.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="cv_opticflow" dir="computer_vision">
  <doc>
    <description>
      Compute optical flow.
      Made for Linux video Devices.
      Computes x and y velocity using optical flow and distance to ground (using sonar).
    </description>

    <!-- Optical flow calculation parameters -->
    <section name="OPTICFLOW" prefix="OPTICFLOW_">
      <define name="AGL_ID" value="ABI_SENDER_ID" description="ABI sender id for AGL message (sonar measurement) (default: ABI_BROADCAST)"/>

      <!-- Video device parameters -->
      <define name="DEVICE" value="/dev/video2" description="The V4L2 camera device that is used for the calculations"/>
      <define name="DEVICE_SIZE" value="320,240" description="The V4L2 camera device width and height"/>
      <define name="DEVICE_BUFFERS" value="15" description="Amount of V4L2 video buffers"/>
      <define name="SUBDEV" description="The V4L2 subdevice to initialize before the main device"/>

      <!-- Camera parameters -->
      <define name="FOV_W" value="0.89360857702" description="The field of view width of the bottom camera (Defaults are from an ARDrone 2)"/>
      <define name="FOV_H" value="0.67020643276" description="The field of view height of the bottom camera (Defaults are from an ARDrone 2)"/>
      <define name="FX" value="343.1211" description="Field in the x direction of the camera (Defaults are from an ARDrone 2)"/>
      <define name="FY" value="348.5053" description="Field in the y direction of the camera (Defaults are from an ARDrone 2)"/>

      <!-- Lucas Kanade optical flow calculation parameters -->
      <define name="MAX_TRACK_CORNERS" value="25" description="The maximum amount of corners the Lucas Kanade algorithm is tracking between two frames"/>
      <define name="WINDOW_SIZE" value="10" description="Window size used in Lucas Kanade algorithm"/>
      <define name="SUBPIXEL_FACTOR" value="10" description="Amount of subpixels per pixel, used for more precise (subpixel) calculations of the flow"/>
      <define name="MAX_ITERATIONS" value="10" description="Maximum number of iterations the Lucas Kanade algorithm should take"/>
      <define name="THRESHOLD_VEC" value="2" description="TThreshold in subpixels when the iterations of Lucas Kanade should stop"/>

      <!-- FAST9 corner detection parameters -->
      <define name="FAST9_ADAPTIVE" value="TRUE" description="Whether we should use and adapative FAST9 crner detection threshold"/>
      <define name="FAST9_THRESHOLD" value="20" description="FAST9 default threshold"/>
      <define name="FAST9_MIN_DISTANCE" value="10" description="The amount of pixels between corners that should be detected"/>
    </section>
  </doc>

  <settings>
	<dl_settings NAME="Vision stabilization">

      <!-- Optical flow calculations parameters for Lucas Kanade and FAST9 -->
      <dl_settings name="vision_calc">
        <dl_setting var="opticflow.max_track_corners" module="computer_vision/opticflow_module" min="0" step="1" max="500" shortname="max_trck_corners" param="OPTICFLOW_MAX_TRACK_CORNERS"/>
        <dl_setting var="opticflow.window_size" module="computer_vision/opticflow_module" min="0" step="1" max="500" shortname="window_size" param="OPTICFLOW_WINDOW_SIZE"/>
        <dl_setting var="opticflow.subpixel_factor" module="computer_vision/opticflow_module" min="0" step="1" max="100" shortname="subpixel_factor" param="OPTICFLOW_SUBPIXEL_FACTOR"/>
        <dl_setting var="opticflow.max_iterations" module="computer_vision/opticflow_module" min="0" step="1" max="100" shortname="max_iterations" param="OPTICFLOW_MAX_ITERATIONS"/>
        <dl_setting var="opticflow.threshold_vec" module="computer_vision/opticflow_module" min="0" step="1" max="100" shortname="threshold_vec" param="OPTICFLOW_THRESHOLD_VEC"/>

        <dl_setting var="opticflow.fast9_adaptive" module="computer_vision/opticflow_module" min="0" step="1" max="1" values="TRUE|FALSE" shortname="fast9_adaptive" param="OPTICFLOW_FAST9_ADAPTIVE"/>
        <dl_setting var="opticflow.fast9_threshold" module="computer_vision/opticflow_module" min="0" step="1" max="255" shortname="fast9_threshold" param="OPTICFLOW_FAST9_THRESHOLD"/>
        <dl_setting var="opticflow.fast9_min_distance" module="computer_vision/opticflow_module" min="0" step="1" max="500" shortname="fast9_min_distance" param="OPTICFLOW_FAST9_MIN_DISTANCE"/>
      </dl_settings>
    </dl_settings>
  </settings>

  <depends>video_thread</depends>

  <header>
    <file name="opticflow_module.h"/>
  </header>

  <init fun="opticflow_module_init()"/>
  <periodic fun="opticflow_module_run()" start="opticflow_module_start()" stop="opticflow_module_stop()" autorun="TRUE"/>

  <makefile target="ap">
    <!-- Include the needed Computer Vision files -->
    <define name="modules/computer_vision" type="include"/>

    <!-- The optical flow module (calculator) -->
    <file name="opticflow_module.c"/>
    <file name="opticflow_calculator.c" dir="modules/computer_vision/opticflow"/>
    <file name="size_divergence.c" dir="modules/computer_vision/opticflow"/>
    <file name="linear_flow_fit.c" dir="modules/computer_vision/opticflow"/>
    <file name="pprz_algebra_float.c" dir="math"/>
    <file name="pprz_matrix_decomp_float.c" dir="math"/>

    <!-- Low-level vision calculations -->
    <file name="fast_rosten.c" dir="modules/computer_vision/lib/vision"/>
    <file name="lucas_kanade.c" dir="modules/computer_vision/lib/vision"/>
  </makefile>

</module>

=== paparazzi/paparazzi/conf/modules/uwb_positioning.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="uwb_positioning" dir="decawave">
  <doc>
    <description>
      Estimate local position from UWB anchor measurements.

      UWB devices can be used for communication, ranging, and positioning.
      This module consumes anchor measurements and estimates a local position.
      With range measurements, 3 anchors are required/supported by the current trilateration path.

      See https://hal-enac.archives-ouvertes.fr/hal-01936955 for more information on the EKF filtering.
    </description>
    <configure name="UWB_POSITIONING_USE_AS_LOCAL_POS" value="FALSE|TRUE" description="use as a local positioning system (default: TRUE)"/>
    <configure name="UWB_POSITIONING_USE_AS_GPS" value="FALSE|TRUE" description="use as a fake GPS positioning system (default: FALSE)"/>
    <section name="UWB_POSITIONING" prefix="UWB_POSITIONING_">
      <define name="ANCHORS_IDS" value="1, 2, 3" type="int[]" description="Comma separated list of anchors ID"/>
      <define name="ANCHORS_POS_X" value="0., 0., 5." type="float[]" description="Comma separated list of anchors ID over X axis"/>
      <define name="ANCHORS_POS_Y" value="0., 5., 0." type="float[]" description="Comma separated list of anchors ID over Y axis"/>
      <define name="ANCHORS_POS_Z" value="0., 0., 0." type="float[]" description="Comma separated list of anchors ID over Z axis"/>
      <define name="RANGE_OFFSET" value="0., 0., 0." type="float[]" description="Offset applied to individual range measurements"/>
      <define name="RANGE_SCALE" value="1., 1., 1." type="float[]" description="Scale factor applied to individual range measurements"/>
      <define name="INITIAL_HEADING" value="0." description="Initial heading correction between anchors frame and global frame"/>
      <define name="NB_ANCHORS" value="3" description="Set number of anchors, only 3 are required/supported at the moment"/>
      <define name="USE_EKF" value="FALSE|TRUE" description="Enable EKF filtering, required to estimate speed"/>
      <define name="EKF_Q" value="1.0" description="EKF process noise"/>
      <define name="EKF_R_DIST" value="0.1" description="EKF noise on distance measurements"/>
      <define name="EKF_R_SPEED" value="0.1" description="EKF noise on speed measurements (if available)"/>
      <define name="NOISE_X|Y|Z" value="0.1" description="Noise level reported by the POSITION_ESTIMATE message when USE_AS_LOCAL_POS is activated"/>
      <define name="VEL_NOISE_X|Y|Z" value="0.1" description="Noise level reported by the VELOCITY_ESTIMATE message when USE_AS_LOCAL_POS is activated"/>
    </section>
  </doc>
  <dep>
    <depends>@ranging</depends>
  </dep>
  <settings>
    <dl_settings>
      <dl_settings name="uwb_positioning">
        <dl_setting max="1" min="0" step="1" module="decawave/uwb_positioning" var="uwb_positioning_use_ekf" shortname="use_ekf" values="FALSE|TRUE"/>
        <dl_setting max="5.0" min="0.01" step="0.01" module="decawave/uwb_positioning" var="uwb_positioning_ekf_q" shortname="q_noise" handler="update_ekf_q"/>
        <dl_setting max="1.0" min="0.01" step="0.01" module="decawave/uwb_positioning" var="uwb_positioning_ekf_r_dist" shortname="r_dist" handler="update_ekf_r_dist"/>
        <dl_setting max="1.0" min="0.01" step="0.01" module="decawave/uwb_positioning" var="uwb_positioning_ekf_r_speed" shortname="r_speed" handler="update_ekf_r_speed"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <header>
    <file name="uwb_positioning.h"/>
  </header>
  <init fun="uwb_positioning_init()"/>
  <periodic fun="uwb_positioning_periodic()" freq="10"/>
  <periodic fun="uwb_positioning_range_periodic()" freq="10"/>
  <periodic fun="uwb_positioning_report()" freq="10" autorun="FALSE"/>
  <periodic fun="uwb_positioning_reset_heading_ref()" freq="1" autorun="FALSE"/>
  <makefile>
    <configure name="UWB_POSITIONING_USE_AS_LOCAL_POS" default="TRUE"/>
    <configure name="UWB_POSITIONING_USE_AS_GPS" default="FALSE"/>
    <file name="uwb_positioning.c"/>
    <file name="trilateration.c"/>
    <file name="ekf_range.c"/>
    <define name="UWB_POSITIONING_USE_AS_LOCAL_POS" value="$(UWB_POSITIONING_USE_AS_LOCAL_POS)"/>
    <define name="UWB_POSITIONING_USE_AS_GPS" value="$(UWB_POSITIONING_USE_AS_GPS)"/>
    <raw>
      ifeq (,$(findstring $(UWB_POSITIONING_USE_AS_GPS),0 FALSE))
        ifdef SECONDARY_GPS
          ifneq (,$(findstring $(SECONDARY_GPS), uwb_positioning))
            # this is the secondary GPS
            $(TARGET).CFLAGS += -DGPS_SECONDARY_TYPE_H=\"modules/decawave/uwb_positioning.h\"
            $(TARGET).CFLAGS += -DSECONDARY_GPS=GPS_UWB
          else
            $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/decawave/uwb_positioning.h\"
            $(TARGET).CFLAGS += -DPRIMARY_GPS=GPS_UWB
          endif
        else
          # plain old single GPS usage
          $(TARGET).CFLAGS += -DGPS_TYPE_H=\"modules/decawave/uwb_positioning.h\"
        endif
      endif
    </raw>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/approach_moving_target.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="approach_moving_target" dir="ctrl">
  <doc>
    <description>
      Approach a moving target (e.g. ship) along a diagonal.
    </description>
  </doc>
  <settings>
    <dl_settings>
      <dl_settings NAME="Approach">
        <dl_setting var="amt.psi_ref" min="-180." max="180." step="1.0" shortname="psi_app" unit="degrees"/>
        <dl_setting var="amt.slope_ref" min="0." max="80." step="1.0" shortname="slope_app" unit="degrees"/>
        <dl_setting var="amt.speed" min="-5.0" max="5." step="0.1" shortname="speed" unit="m/s"/>
        <dl_setting var="amt.distance" min="0.0" max="200." step="1.0" shortname="dist" unit="m"/>
        <dl_setting var="amt_err_slowdown_gain" min="0.0" max="4." step="0.01" shortname="slwdn_gain"/>
        <dl_setting var="amt.pos_gain" min="0.05" max="3.0" step="0.01" shortname="pos_gain"/>
        <dl_setting var="amt.speed_gain" min="0.0" max="1.0" step="0.01" shortname="speed_gain"/>
        <dl_setting var="amt.relvel_gain" min="0.0" max="1.0" step="0.01" shortname="relvel_gain"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <dep>
    <depends>target_pos</depends>
  </dep>
  <header>
    <file name="approach_moving_target.h"/>
  </header>
  <init fun="approach_moving_target_init()"/>
  <periodic fun="follow_diagonal_approach()" freq="100.0"/>
  <makefile>
    <file name="approach_moving_target.c"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/cv_textons.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="cv_textons" dir="computer_vision">
  <doc>
    <description>Represent the appearance (texture, color) of an image by means of a texton histogram.</description>

    <section name="TEXTONS" prefix="TEXTONS_">
      <define name="FPS" value="0" description="The (maximum) frequency to run the calculations at. If zero, it will max out at the camera frame rate"/>
      <define name="CAMERA" value="bottom_camera|front_camera" description="The V4L2 camera device that is used for the calculations"/>
      <define name="RUN" value="YES" description="Whether the texton function is running (YES) or not (NO)."/>  
      <define name="LOAD_DICTIONARY" value="YES" description="Whether a dictionary is loaded (YES) or learned (NO)."/>
      <define name="REINITIALIZE_DICTIONARY" value="NO" description="If set to YES, the dictionary will be reinitialized with the current image."/>
      <define name="N_TEXTONS" value="10" description="The number of textons (words) in the dictionary."/>
      <define name="PATCH_SIZE" value="6" description="Size of the image patches extracted from the image - even numbers."/>
      <define name="FULL_SAMPLING" value="NO" description="If YES, the entire image is covered with samples, if NO sub-sampling is used (faster)."/>
      <define name="DICTIONARY_NUMBER" value="0" description="Number of the dictionary (so that different environments can each have their specific dictionary)."/>
      <define name="N_SAMPLES" value="50" description="Number of samples extracted form the image when not doing full sampling."/>
      <define name="N_LEARNING_SAMPLES" value="5000" description="Number of samples used for learning the dictionary."/>
      <define name="ALPHA" value="10" description="Learning rate when creating the dictionary: 0 = no learning, 255 = the texton becomes equal to the new patch."/>
      <define name="BORDER_WIDTH" value="0" description="Width of the image border from which no samples are taken."/>
      <define name="BORDER_HEIGHT" value="0" description="Height of the border from which no samples are taken."/>
      <define name="DICTIONARY_PATH" value="/data/ftp/internal_000" description="Path to which the textons dictionary is saved."/>
    </section>

  </doc>

  <settings>
    <dl_settings>
      <dl_settings NAME="Textons">
        <dl_setting var="running" min="0" step="1" max="1" module="computer_vision/textons" shortname="running" values="NO|YES" param="TEXTONS_RUN"/>
        <dl_setting var="load_dictionary" min="0" step="1" max="1" module="computer_vision/textons" shortname="load dict." values="NO|YES" param="TEXTONS_LOAD_DICTIONARY"/>
        <dl_setting var="reinitialize_dictionary" min="0" step="1" max="1" module="computer_vision/textons" shortname="reinit dict." values="NO|YES" param="TEXTONS_REINITIALIZE_DICTIONARY"/>
        <dl_setting var="n_textons" min="1" step="1" max="255" shortname="n_textons" param="TEXTONS_N_TEXTONS"/>
        <dl_setting var="patch_size" min="2" step="2" max="40" shortname="p_size" param="TEXTONS_PATCH_SIZE" />
        <dl_setting var="FULL_SAMPLING"  min="0" step="1" max="1" shortname="full_sam" values="NO|YES" param="TEXTONS_FULL_SAMPLING" />
        <dl_setting var="dictionary_number"  min="0" step="1" max="20" shortname="dict_num" param="TEXTONS_DICTIONARY_NUMBER" />
        <dl_setting var="n_samples_image"  min="0" step="10" max="1000" shortname="n_samples" param="TEXTONS_N_SAMPLES" />
        <dl_setting var="n_learning_samples"  min="1" step="100" max="250000" shortname="n_l_samples" param="TEXTONS_N_LEARNING_SAMPLES" />
        <dl_setting var="alpha_uint" min="0" step="1" max="255" shortname="alpha" param="TEXTONS_ALPHA"/>
        <dl_setting var="border_width"  min="0" step="1" max="200" shortname="b_w" param="TEXTONS_BORDER_WIDTH"/>
        <dl_setting var="border_height"  min="0" step="1" max="200" shortname="b_h" param="TEXTONS_BORDER_HEIGHT"/>
      </dl_settings>
    </dl_settings>
  </settings>

  <header>
    <file name="textons.h"/>
  </header>
  <init fun="textons_init()"/>

  <makefile target="ap|nps">
    <file name="textons.c"/>
    <file name="image.c" dir="modules/computer_vision/lib/vision"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/electrical.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="electrical" dir="energy" task="core">
  <doc>
    <description>
      General electrical interface
    </description>
  </doc>
  <settings>
    <dl_settings>
      <dl_settings NAME="Electrical">
          <dl_setting var="avg_reset" min="0" step="1" max="1" values="FALSE|TRUE" handler="avg_reset" module="modules/energy/electrical" type="fun"/>
      </dl_settings>
    </dl_settings>
  </settings>
  <dep>
    <depends>adc</depends>
    <provides>electrical</provides>
  </dep>
  <header>
    <file name="electrical.h"/>
  </header>
  <init fun="electrical_init()"/>
  <periodic fun="electrical_periodic()" freq="10"/>
  <makefile target="fbw|sim|nps" firmware="fixedwing">
    <file name="electrical.c"/>
    <test firmware="fixedwing">
      <define name="ELECTRICAL_PERIODIC_FREQ" value="10"/>
    </test>
  </makefile>
  <makefile target="ap" firmware="fixedwing" cond="ifeq (,$(findstring $(SEPARATE_FBW),0 FALSE))">
    <file name="electrical.c"/>
  </makefile>
  <makefile firmware="rotorcraft">
    <file name="electrical.c"/>
  </makefile>
  <makefile firmware="rover">
    <file name="electrical.c"/>
  </makefile>
</module>
