=== paparazzi/paparazzi/conf/modules/module.dtd
<!-- Paparazzi Modules DTD -->

<!ELEMENT module (doc,settings_file*,settings*,dep?,autoload*,header?,init*,periodic*,event*,datalink*,makefile*)>
<!ELEMENT doc (description,(define|configure|section)*)>
<!ELEMENT settings_file (file*)>
<!ELEMENT settings (dl_settings?)>
<!ELEMENT dep (depends?,conflicts?,provides?)>
<!ELEMENT depends (#PCDATA)>
<!ELEMENT conflicts (#PCDATA)>
<!ELEMENT provides (#PCDATA)>
<!ELEMENT autoload EMPTY>
<!ELEMENT header (file*)>
<!ELEMENT init EMPTY>
<!ELEMENT periodic EMPTY>
<!ELEMENT event EMPTY>
<!ELEMENT handler EMPTY>
<!ELEMENT datalink EMPTY>
<!ELEMENT makefile (configure|define|include|flag|file|file_arch|raw|test)*>
<!ELEMENT test (configure|define|include|file|file_arch|shell)*>
<!ELEMENT section (define|configure)*>
<!ELEMENT description (#PCDATA)>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT include EMPTY>
<!ELEMENT flag EMPTY>
<!ELEMENT file EMPTY>
<!ELEMENT file_arch EMPTY>
<!ELEMENT shell EMPTY>
<!ELEMENT raw (#PCDATA)>
<!ELEMENT dl_settings (dl_setting|dl_settings)+>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST module
name CDATA #REQUIRED
dir CDATA #IMPLIED
task CDATA #IMPLIED>

<!ATTLIST autoload
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST init
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST periodic
fun CDATA #REQUIRED
period CDATA #IMPLIED
freq CDATA #IMPLIED
delay CDATA #IMPLIED
start CDATA #IMPLIED
stop CDATA #IMPLIED
autorun (TRUE|FALSE|LOCK) #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST event
fun CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST datalink
message CDATA #REQUIRED
fun CDATA #REQUIRED>

<!ATTLIST makefile
target CDATA #IMPLIED
firmware CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST section
name CDATA #REQUIRED
prefix CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #IMPLIED
case CDATA #IMPLIED
default CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
integer CDATA #IMPLIED
unit CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST include
name CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST flag
name CDATA #REQUIRED
value CDATA #REQUIRED
cond CDATA #IMPLIED>

<!ATTLIST shell
cmd CDATA #REQUIRED>

<!ATTLIST file
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST file_arch
name CDATA #REQUIRED
dir CDATA #IMPLIED
cond CDATA #IMPLIED>

<!ATTLIST settings_file
name CDATA #REQUIRED
>

<!ATTLIST settings
name CDATA #IMPLIED
target CDATA #IMPLIED
>

<!ATTLIST dl_settings
name CDATA #IMPLIED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

<!ATTLIST test
arch CDATA #IMPLIED
firmware CDATA #IMPLIED
>

=== paparazzi/paparazzi/conf/modules/gps_ubx_uart.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="gps_ubx" dir="gps">
  <doc>
    <description>Ublox gps (uart)</description>
  </doc>
  <header>
    <file name="gps_ubx_uart.h"/>
  </header>
  <init fun="gps_init()"/>
  <event fun="GpsEvent(on_gps_solution)"/>
  <makefile>
    <file name="gps.c" dir="subsystems"/>
  </makefile>
  <makefile target="ap">
    <file name="gps_ubx.c" dir="subsystems/gps"/>
    <raw>
      ap.CFLAGS += -DGPS_TYPE_H=\"subsystems/gps/gps_ubx.h\"
    </raw>
  </makefile>
  <makefile target="sim|jsbsim">
    <file name="gps_sim.c" dir="subsystems/gps"/>
    <raw>
      sim.CFLAGS += -DGPS_TYPE_H=\"subsystems/gps/gps_sim.h\"
      jsbsim.CFLAGS += -DGPS_TYPE_H=\"subsystems/gps/gps_sim.h\"
    </raw>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/imu_mpu9250_i2c.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="imu_mpu9250_i2c" dir="imu">
  <doc>
    <description>
      IMU with MPU9250 via I2C.
      Also reads the internal AK8963 magnetometer.
    </description>
    <configure name="IMU_MPU9250_I2C_DEV" value="i2c2" description="I2C device to use for MPU9250"/>
    <define name="IMU_MPU9250_GYRO_LOWPASS_FILTER" value="MPU9250_DLPF_GYRO_250HZ" description="gyro DigitalLowPassFilter setting of the MPU"/>
    <define name="IMU_MPU9250_ACCEL_LOWPASS_FILTER" value="MPU9250_DLPF_ACCEL_184HZ" description="accelerometer DigitalLowPassFilter setting of the MPU"/>
    <define name="IMU_MPU9250_SMPLRT_DIV" value="3" description="sample rate divider setting of the MPU"/>
    <define name="IMU_MPU9250_GYRO_RANGE" value="MPU9250_GYRO_RANGE_1000" description="gyroscope range setting of the MPU"/>
    <define name="IMU_MPU9250_ACCEL_RANGE" value="MPU9250_ACCEL_RANGE_8G" description="accelerometer range setting of the MPU"/>
    <define name="IMU_MPU9250_I2C_ADDR" value="MPU9250_ADDR_ALT" description="I2C address of the MPU"/>
    <define name="IMU_MPU9250_CHAN_X" value="0" description="channel index"/>
    <define name="IMU_MPU9250_CHAN_Y" value="1" description="channel index"/>
    <define name="IMU_MPU9250_CHAN_Z" value="2" description="channel index"/>
  </doc>
  <autoload name="imu_common"/>
  <autoload name="imu_nps"/>
  <header>
    <file name="imu_mpu9250_i2c.h" dir="subsystems/imu"/>
  </header>

  <init fun="imu_mpu9250_init()"/>
  <periodic fun="imu_mpu9250_periodic()"/>
  <event fun="imu_mpu9250_event()"/>

  <makefile target="!sim|nps|fbw">
    <configure name="IMU_MPU9250_I2C_DEV" default="i2c2" case="lower|upper"/>

    <define name="IMU_MPU9250_I2C_DEV" value="$(IMU_MPU9250_I2C_DEV_LOWER)"/>
    <define name="USE_$(IMU_MPU9250_I2C_DEV_UPPER)"/>

    <define name="IMU_TYPE_H" value="subsystems/imu/imu_mpu9250_i2c.h" type="string"/>

    <file name="mpu9250.c" dir="peripherals"/>
    <file name="mpu9250_i2c.c" dir="peripherals"/>
    <file name="ak8963.c" dir="peripherals"/>
    <file name="imu_mpu9250_i2c.c" dir="subsystems/imu"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/gps_sim.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="gps_sim" dir="gps" task="sensors">
  <doc>
    <description>
      Simulated GPS
      For simple fixedwing OCaml simulator. Does not model any GPS inaccuracies/noise.
    </description>
  </doc>
  <dep>
    <depends>gps</depends>
    <provides>gps</provides>
  </dep>
  <header>
    <file name="gps.h" dir="subsystems"/>
  </header>
  <init fun="gps_sim_init()"/>
  <periodic fun="gps_sim_periodic_check()" freq="1." autorun="TRUE"/>
  <makefile target="sim">
    <file name="gps_sim.c" dir="subsystems/gps"/>
    <define name="GPS_TYPE_H" value="subsystems/gps/gps_sim.h" type="string"/>
    <test/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/osd_max7456_new.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="max7456" dir="osd_max7456_new">
  <doc>
    <description>MAX7456 driver (SPI)</description>
    <configure name="MAX7456_SPI_DEV" value="spiX" description="select spi peripheral to use (default spi2)"/>
    <configure name="MAX7456_SLAVE_IDX" value="SPI_SLAVE1" description="SPI slave select index"/>
    <define name="USE_PAL_FOR_OSD_VIDEO" value="1" description="SELECT PAL OR NTSC" />
  </doc>
  <header>
    <file name="max7456.h"/>
  </header>
  <init fun="max7456_init()"/>
  <periodic fun="max7456_periodic()" freq="20" autorun="TRUE"/>
  <event fun="max7456_event()"/>
  <makefile target="ap">
    <configure name="MAX7456_SPI_DEV" default="spi2" case="upper|lower"/>
    <configure name="MAX7456_SLAVE_IDX" default="spi_slave1" case="upper|lower"/>

    <define name="MAX7456_SPI_DEV" value="$(MAX7456_SPI_DEV_LOWER)" />
    <define name="USE_$(MAX7456_SPI_DEV_UPPER)" />

    <define name="MAX7456_SLAVE_IDX" value="$(MAX7456_SLAVE_IDX_UPPER)" />
    <define name="USE_$(MAX7456_SLAVE_IDX_UPPER)" />

    <file name="max7456.c" />
    <raw>
      include $(CFG_SHARED)/spi_master.makefile
    </raw>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/tcas.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="tcas" dir="multi">
  <doc>
    <description>TCAS collision avoidance</description>
  </doc>
  <header>
    <file name="tcas.h"/>
  </header>
  <init fun="tcas_init()"/>
  <periodic fun="tcas_periodic_task_1Hz()" freq="1"/>
  <periodic fun="tcas_periodic_task_4Hz()" freq="4"/>
  <datalink message="TCAS_RESOLVE" fun="ParseTcasResolve()"/>
  <makefile>
    <file name="tcas.c"/>
    <define name="TCAS"/>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/i2c_abuse_test.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="i2c_abuse_test" dir="benchmark">
  <doc>
    <description></description>
  </doc>
  <header>
    <file name="i2c_abuse_test.h"/>
  </header>
  <init fun="init_i2c_abuse_test()"/>
  <periodic fun="periodic_50Hz_i2c_abuse_test()" period="0.02" autorun="TRUE" />
  <event fun="event_i2c_abuse_test()" />
  <makefile>
    <file name="i2c_abuse_test.c"/>
    <raw>
ifeq ($(ARCH), lpc21)
$(TARGET).CFLAGS += -DI2C_ABUSE_LED=3
$(TARGET).CFLAGS += -DUSE_I2C0
$(TARGET).CFLAGS += -DI2C_ABUSE_PORT=i2c0
else ifeq ($(ARCH), stm32)
$(TARGET).CFLAGS += -DI2C_ABUSE_LED=7
$(TARGET).CFLAGS += -DI2C_ABUSE_PORT=i2c2
endif

    </raw>
  </makefile>
</module>

=== paparazzi/paparazzi/conf/modules/decawave_serial_communication.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="decawave_serial_communication" dir="decawave">
	<doc>
		<description>
			Decawave DWM1000 module serial communication
		</description>
	</doc>
	<header>
		<file name="decawave_serial_communication.h" />
	</header>
	<init fun="decawave_serial_communication_init()" />
	<periodic fun="decawave_serial_communication_periodic()" freq="30" autorun="TRUE" />
	<event fun="decawave_serial_communication_event()"/>
	<makefile target="ap">
		<file name="decawave_serial_communication.c" />
		<configure name="SERIAL_UART" default="uart2" case="upper|lower" />
		<configure name="SERIAL_BAUD" default="B9600" />
		<configure name="SERIAL_LED" default="3" />
		<define name="USE_$(SERIAL_UART_UPPER)" />
		<define name="SERIAL_UART" value="$(SERIAL_UART_LOWER)" />
		<define name="$(SERIAL_UART_UPPER)_BAUD" value="$(SERIAL_BAUD)" />
	</makefile>
</module>

=== paparazzi/paparazzi/conf/modules/nav_gls.xml
<!DOCTYPE module SYSTEM "module.dtd">

<module name="nav_gls" dir="nav" task="control">
  <doc>
    <description>
      gps landing system
 * -automatic calculation of top of decent for const app angle
 * -smooth intercept posible
 * -landing direction is set by app fix / also possible in flight!!!
    </description>
  </doc>
  <header>
    <file name="nav_gls.h"/>
  </header>
  <dep>
    <depends>@navigation</depends>
  </dep>
  <makefile target="ap|sim|nps">
    <file name="nav_gls.c"/>
    <test firmware="fixedwing">
      <define name="CTRL_TYPE_H" value="firmwares/fixedwing/guidance/guidance_v.h" type="string"/>
    </test>
  </makefile>
</module>
