=== paparazzi/paparazzi/conf/airframes/airframe.dtd
<!-- Paparazzi airframe DTD -->

<!ELEMENT airframe (include|servos|commands|rc_commands|auto_rc_commands|ap_only_commands|command_laws|section|modules|firmware|autopilot|heli_curves|description)*>
<!ELEMENT include EMPTY>
<!ELEMENT servos (servo)*>
<!ELEMENT commands (axis)*>
<!ELEMENT rc_commands (set)*>
<!ELEMENT auto_rc_commands (set)*>
<!ELEMENT ap_only_commands (copy)*>
<!ELEMENT command_laws (let|set|call|ratelimit)*>
<!ELEMENT heli_curves (curve)*>
<!ELEMENT section (define|comment)*>
<!ELEMENT servo EMPTY>
<!ELEMENT axis EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT ratelimit EMPTY>
<!ELEMENT copy EMPTY>
<!ELEMENT curve EMPTY>
<!ELEMENT let EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT modules (module)*>
<!ELEMENT configure EMPTY>
<!ELEMENT firmware (target|module|autopilot|configure|define|comment)*>
<!ELEMENT target (module|autopilot|configure|define|comment)*>
<!ELEMENT module (configure|define|comment)*>
<!ELEMENT autopilot EMPTY>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST include
href CDATA #REQUIRED>

<!ATTLIST firmware
name CDATA #REQUIRED>

<!ATTLIST autopilot
name CDATA #REQUIRED
freq CDATA #IMPLIED>

<!ATTLIST target
name CDATA #REQUIRED
board CDATA #REQUIRED>

<!ATTLIST airframe
name CDATA #IMPLIED>

<!ATTLIST servos
driver CDATA #IMPLIED>

<!ATTLIST commands>
<!ATTLIST rc_commands>
<!ATTLIST ap_only_commands>
<!ATTLIST command_laws>

<!ATTLIST heli_curves>

<!ATTLIST section
name CDATA #IMPLIED
prefix CDATA #IMPLIED>

<!ATTLIST servo
name CDATA #REQUIRED
no CDATA #REQUIRED
min CDATA #REQUIRED
neutral CDATA #REQUIRED
max CDATA #REQUIRED>

<!ATTLIST curve
throttle CDATA #REQUIRED
rpm CDATA #IMPLIED
collective CDATA #REQUIRED>

<!ATTLIST axis
name CDATA #REQUIRED
failsafe_value CDATA #REQUIRED>

<!ATTLIST set
value CDATA #REQUIRED
command CDATA #IMPLIED
servo CDATA #IMPLIED>

<!ATTLIST call
fun CDATA #REQUIRED>

<!ATTLIST copy
command CDATA #REQUIRED>

<!ATTLIST let
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST ratelimit
var CDATA #REQUIRED
value CDATA #REQUIRED
rate_min CDATA #REQUIRED
rate_max CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
unit CDATA #IMPLIED
code_unit CDATA #IMPLIED
integer CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED
description CDATA #IMPLIED>

<!ATTLIST modules
main_freq CDATA #IMPLIED
target CDATA #IMPLIED>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED
dir CDATA #IMPLIED>

=== paparazzi/paparazzi/conf/airframes/TUDELFT/tudelft_selfie.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<airframe name="ardrone2_oa_avoid">

  <firmware name="rotorcraft">
    <target name="ap" board="ardrone2">
      <configure name="USE_BARO_BOARD" value="TRUE"/>
    </target>

    <define name="FAILSAFE_DESCENT_SPEED" value="0.5"/>
    <define name="USE_SONAR" value="FALSE"/>
 <define name="USE_GPS_ALT" value="1"/>

    <configure name="USE_MAGNETOMETER" value="TRUE"/>

	<!-- Subsystem section -->
    <module name="telemetry" type="transparent_udp"/>
    <module name="radio_control" type="datalink"/>
    <module name="motor_mixing"/>
    <module name="actuators" type="ardrone2"/>
    <module name="imu" type="ardrone2"/>
 <module name="gps" type="datalink"/>
    <module name="stabilization" type="int_quat"/>
    <module name="ahrs" type="int_cmpl_quat"/>
    <module name="ins" type="extended"/>
  </firmware>

  <modules main_freq="512">
    <module name="bat_voltage_ardrone2"/>
    <module name="stereocam">
	<configure name="STEREO_UART" value="UART1"/>
	<configure name="STEREO_BAUD" value="B115200"/>
    </module>
    <module name="stereocam_follow_me"/>
  </modules>

  <commands>
    <axis name="PITCH" failsafe_value="0"/>
    <axis name="ROLL" failsafe_value="0"/>
    <axis name="YAW" failsafe_value="0"/>
    <axis name="THRUST" failsafe_value="3000"/>
  </commands>

  <servos driver="Default">
    <servo name="TOP_LEFT" no="0" min="0" neutral="1" max="500"/>
    <servo name="TOP_RIGHT" no="1" min="0" neutral="1" max="500"/>
    <servo name="BOTTOM_RIGHT" no="2" min="0" neutral="1" max="500"/>
    <servo name="BOTTOM_LEFT" no="3" min="0" neutral="1" max="500"/>
  </servos>

  <section name="MIXING" prefix="MOTOR_MIXING_">
    <define name="TRIM_ROLL" value="0"/>
    <define name="TRIM_PITCH" value="0"/>
    <define name="TRIM_YAW" value="0"/>

    <!-- Time cross layout (X), with order NW (CW), NE (CCW), SE (CW), SW (CCW) -->
    <define name="TYPE" value="QUAD_X"/>
  </section>

  <command_laws>
    <call fun="motor_mixing_run(autopilot_motors_on,FALSE,values)"/>
    <set servo="TOP_LEFT" value="motor_mixing.commands[MOTOR_FRONT_LEFT]"/>
    <set servo="TOP_RIGHT" value="motor_mixing.commands[MOTOR_FRONT_RIGHT]"/>
    <set servo="BOTTOM_RIGHT" value="motor_mixing.commands[MOTOR_BACK_RIGHT]"/>
    <set servo="BOTTOM_LEFT" value="motor_mixing.commands[MOTOR_BACK_LEFT]"/>
  </command_laws>

  <section name="IMU" prefix="IMU_">
    <!-- Accelero -->
    <define name="ACCEL_X_NEUTRAL" value="2048"/>
    <define name="ACCEL_Y_NEUTRAL" value="2048"/>
    <define name="ACCEL_Z_NEUTRAL" value="2048"/>

    <!-- Magneto calibration -->
    <define name="MAG_X_NEUTRAL" value="0"/>
    <define name="MAG_Y_NEUTRAL" value="0"/>
    <define name="MAG_Z_NEUTRAL" value="-180"/>
    <define name="MAG_X_SENS" value="16." integer="16"/>
    <define name="MAG_Y_SENS" value="16." integer="16"/>
    <define name="MAG_Z_SENS" value="16." integer="16"/>

    <!-- Magneto current calibration -->
    <define name="MAG_X_CURRENT_COEF" value="0.0"/>
    <define name="MAG_Y_CURRENT_COEF" value="0.0"/>
    <define name="MAG_Z_CURRENT_COEF" value="0.0"/>

    <define name="BODY_TO_IMU_PHI" value="-2.3" unit="deg"/>
    <define name="BODY_TO_IMU_THETA" value="1.7" unit="deg"/>
    <define name="BODY_TO_IMU_PSI" value="0." unit="deg"/>
  </section>

  <!-- local magnetic field -->
  <!-- http://wiki.paparazziuav.org/wiki/Subsystem/ahrs#Local_Magnetic_Field -->
  <section name="AHRS" prefix="AHRS_">
    <!-- Delft -->
    <define name="H_X" value="0.3892503"/>
    <define name="H_Y" value="0.0017972"/>
    <define name="H_Z" value="0.9211303"/>
  </section>

  <section name="INS" prefix="INS_">
  </section>


  <section name="STABILIZATION_ATTITUDE_INDI" prefix="STABILIZATION_INDI_">
    <!-- control effectiveness -->
    <define name="G1_P" value="0.028551973"/>
    <define name="G1_Q" value="0.023775417"/>
    <define name="G1_R" value="0.00173069"/>
    <define name="G2_R" value="0.086460732"/>

    <!-- reference acceleration for attitude control -->
    <define name="REF_ERR_P" value="380.0"/>
    <define name="REF_ERR_Q" value="380.0"/>
    <define name="REF_ERR_R" value="70.0"/>
    <define name="REF_RATE_P" value="21.6"/>
    <define name="REF_RATE_Q" value="21.6"/>
    <define name="REF_RATE_R" value="11.0"/>

    <!-- second order filter parameters -->
    <define name="FILT_OMEGA" value="20.0"/>
    <define name="FILT_ZETA" value="0.55"/>
    <define name="FILT_OMEGA_R" value="20.0"/>
    <define name="FILT_ZETA_R" value="0.55"/>

    <!-- first order actuator dynamics -->
    <define name="ACT_DYN_P" value="0.06"/>
    <define name="ACT_DYN_Q" value="0.06"/>
    <define name="ACT_DYN_R" value="0.06"/>

    <!-- Adaptive Learning Rate -->
    <define name="USE_ADAPTIVE" value="FALSE"/>
    <define name="ADAPTIVE_MU" value="0.0001"/>
  </section>
  <section name="STABILIZATION_ATTITUDE" prefix="STABILIZATION_ATTITUDE_">
    <!-- setpoints -->
    <define name="SP_MAX_PHI" value="45" unit="deg"/>
    <define name="SP_MAX_THETA" value="45" unit="deg"/>
    <define name="SP_MAX_R" value="180" unit="deg/s"/>
    <define name="DEADBAND_A" value="0"/>
    <define name="DEADBAND_E" value="0"/>
    <define name="DEADBAND_R" value="250"/>

    <!-- reference -->
    <define name="REF_OMEGA_P" value="450" unit="deg/s"/>
    <define name="REF_ZETA_P" value="0.9"/>
    <define name="REF_MAX_P" value="600." unit="deg/s"/>
    <define name="REF_MAX_PDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_Q" value="450" unit="deg/s"/>
    <define name="REF_ZETA_Q" value="0.9"/>
    <define name="REF_MAX_Q" value="600." unit="deg/s"/>
    <define name="REF_MAX_QDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_R" value="450" unit="deg/s"/>
    <define name="REF_ZETA_R" value="0.9"/>
    <define name="REF_MAX_R" value="600." unit="deg/s"/>
    <define name="REF_MAX_RDOT" value="RadOfDeg(8000.)"/>

  <!-- feedback -->
    <define name="PHI_PGAIN" value="850"/>
    <define name="PHI_DGAIN" value="425"/>
    <define name="PHI_IGAIN" value="0"/>

    <define name="THETA_PGAIN" value="850"/>
    <define name="THETA_DGAIN" value="425"/>
    <define name="THETA_IGAIN" value="0"/>

    <define name="PSI_PGAIN" value="1000"/>
    <define name="PSI_DGAIN" value="700"/>
    <define name="PSI_IGAIN" value="0"/>

    <!-- feedforward -->
    <define name="PHI_DDGAIN" value="0"/>
    <define name="THETA_DDGAIN" value="0"/>
    <define name="PSI_DDGAIN" value="100"/>
  </section>

  <section name="GUIDANCE_V" prefix="GUIDANCE_V_">
    <define name="HOVER_KP" value="583"/>
    <define name="HOVER_KD" value="82"/>
    <define name="HOVER_KI" value="13"/>
    <define name="NOMINAL_HOVER_THROTTLE" value="0.645"/>
    <define name="ADAPT_THROTTLE_ENABLED" value="false"/>
  </section>


  <section name="GUIDANCE_H" prefix="GUIDANCE_H_">
    <!-- Good weather -->
    <define name="MAX_BANK" value="20" unit="deg"/>
    <!-- Bad weather -->
    <!-- define name="MAX_BANK" value="32" unit="deg"/ -->

    <define name="PGAIN" value="363"/>
    <define name="DGAIN" value="237"/>
    <define name="IGAIN" value="30"/>
    <define name="VGAIN" value="0"/>
    <define name="AGAIN" value="0"/>
  </section>

  <section name="SIMULATOR" prefix="NPS_">
    <define name="ACTUATOR_NAMES" value="nw_motor, ne_motor, se_motor, sw_motor" type="string[]"/>
    <define name="JSBSIM_MODEL" value="simple_ardrone2" type="string"/>
    <define name="JSBSIM_INIT" value="reset00" type="string"/>
    <define name="SENSORS_PARAMS" value="nps_sensors_params_ardrone2.h" type="string"/>
  </section>

  <section name="AUTOPILOT">
    <define name="MODE_STARTUP" value="AP_MODE_NAV"/>
    <define name="MODE_MANUAL" value="AP_MODE_ATTITUDE_DIRECT"/>
    <define name="MODE_AUTO1" value="AP_MODE_HOVER_Z_HOLD"/>
    <define name="MODE_AUTO2" value="AP_MODE_NAV"/>
    <define name="ARRIVED_AT_WAYPOINT" value="0.15"/>
    <define name="AUTOPILOT_IN_FLIGHT_MIN_THRUST" value="1500"/>
    <define name="NO_RC_THRUST_LIMIT" value="TRUE"/>
  </section>

  <section name="BAT">
    <define name="MILLIAMP_AT_FULL_THROTTLE" value="8700"/>
    <define name="CATASTROPHIC_BAT_LEVEL" value="9.3" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="9.9" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="10.1" unit="V"/>
    <define name="MAX_BAT_LEVEL" value="12.4" unit="V"/>
  </section>
</airframe>

=== paparazzi/paparazzi/conf/airframes/HooperFly/teensyfly_quad_lisa_mx_20.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<!-- this is a quadcopter frame in x-configuration equiped with
     * Autopilot:   Lisa/MX 2.0 with STM32F4  http://wiki.paparazziuav.org/wiki/Lisa/M_v20
     * IMU:         Integrated Aspirin 2.2    http://wiki.paparazziuav.org/wiki/AspirinIMU
     * Actuators:   PWM motor controllers     http://wiki.paparazziuav.org/wiki/Subsystem/actuators#PWM
     * GPS:         Ublox                     http://wiki.paparazziuav.org/wiki/Subsystem/gps
     * RC:          two Spektrum sats         http://wiki.paparazziuav.org/wiki/Subsystem/radio_control#Spektrum
-->

<airframe name="TeensyFly Quad LisaMX_2.0 pwm">

  <firmware name="rotorcraft">
    <target name="ap" board="lisa_mx_2.0">
      <!-- MPU6000 is configured to output data at 2kHz, but polled at 512Hz PERIODIC_FREQUENCY -->
    </target>

    <target name="nps" board="pc">
      <subsystem name="fdm" type="jsbsim"/>
    </target>

    <subsystem name="radio_control" type="spektrum">
      <define name="RADIO_MODE" value="RADIO_AUX1"/>
      <configure name="USE_SECONDARY_SPEKTRUM_RECEIVER" value="1"/>
    </subsystem>

    <subsystem name="motor_mixing"/>
    <subsystem name="actuators"     type="pwm">
      <define name="SERVO_HZ" value="400"/>
    </subsystem>

    <subsystem name="telemetry"     type="transparent"/>
    <subsystem name="imu"           type="aspirin_v2.2"/>
    <subsystem name="gps"           type="ublox"/>
    <subsystem name="stabilization" type="int_quat"/>
    <subsystem name="ahrs"          type="int_cmpl_quat"/>
    <subsystem name="ins"           type="hff"/>

    <!--define name="KILL_ON_GROUND_DETECT" value="TRUE"/-->
  </firmware>

  <modules>
    <load name="adc_generic.xml">
      <configure name="ADC_CHANNEL_GENERIC1" value="ADC_1"/>
      <configure name="ADC_CHANNEL_GENERIC2" value="ADC_2"/>
    </load>
    <load name="gps_ubx_ucenter.xml"/>
    <load name="geo_mag.xml"/>
    <load name="air_data.xml"/>
  </modules>

  <servos driver="Pwm">
    <servo name="FRONT_LEFT"  no="0" min="1000" neutral="1100" max="1900"/>
    <servo name="FRONT_RIGHT" no="1" min="1000" neutral="1100" max="1900"/>
    <servo name="BACK_RIGHT"  no="3" min="1000" neutral="1100" max="1900"/>
    <servo name="BACK_LEFT"   no="4" min="1000" neutral="1100" max="1900"/>
  </servos>

  <commands>
    <axis name="ROLL"   failsafe_value="0"/>
    <axis name="PITCH"  failsafe_value="0"/>
    <axis name="YAW"    failsafe_value="0"/>
    <axis name="THRUST" failsafe_value="0"/>
  </commands>

  <section name="MIXING" prefix="MOTOR_MIXING_">
    <define name="TRIM_ROLL"  value="0"/>
    <define name="TRIM_PITCH" value="0"/>
    <define name="TRIM_YAW"   value="0"/>
    <define name="NB_MOTOR"   value="4"/>
    <define name="SCALE"      value="256"/>
    <!-- order (and rotation direction) : FL(CW), FR(CCW), BR(CW), BL(CCW) -->
    <define name="ROLL_COEF"   value="{  256, -256, -256,  256 }"/>
    <define name="PITCH_COEF"  value="{  256,  256, -256, -256 }"/>
    <define name="YAW_COEF"    value="{ -256,  256, -256,  256 }"/>
    <define name="THRUST_COEF" value="{  256,  256,  256,  256 }"/>
  </section>

  <command_laws>
    <call fun="motor_mixing_run(autopilot_motors_on,FALSE,values)"/>
    <set servo="FRONT_LEFT"  value="motor_mixing.commands[0]"/>
    <set servo="FRONT_RIGHT" value="motor_mixing.commands[1]"/>
    <set servo="BACK_RIGHT"  value="motor_mixing.commands[2]"/>
    <set servo="BACK_LEFT"   value="motor_mixing.commands[3]"/>
  </command_laws>

  <section name="IMU" prefix="IMU_">
    <define name="ACCEL_X_NEUTRAL" value="11"/>
    <define name="ACCEL_Y_NEUTRAL" value="11"/>
    <define name="ACCEL_Z_NEUTRAL" value="-25"/>

    <!-- replace this with your own calibration -->
    <define name="MAG_X_NEUTRAL" value="-179"/>
    <define name="MAG_Y_NEUTRAL" value="-21"/>
    <define name="MAG_Z_NEUTRAL" value="79"/>
    <define name="MAG_X_SENS" value="4.17334785618" integer="16"/>
    <define name="MAG_Y_SENS" value="3.98885954135" integer="16"/>
    <define name="MAG_Z_SENS" value="4.40442339014" integer="16"/>

    <define name="BODY_TO_IMU_PHI"   value="0." unit="deg"/>
    <define name="BODY_TO_IMU_THETA" value="0." unit="deg"/>
    <define name="BODY_TO_IMU_PSI"   value="0." unit="deg"/>
  </section>

  <section name="AHRS" prefix="AHRS_">
    <!-- values used if no GPS fix, on 3D fix is update by geo_mag module -->
    <define name="H_X" value="0.3770441"/>
    <define name="H_Y" value="0.0193986"/>
    <define name="H_Z" value="0.9259921"/>
  </section>

  <section name="STABILIZATION_RATE" prefix="STABILIZATION_RATE_">
    <!-- setpoints -->
    <define name="SP_MAX_P" value="10000"/>
    <define name="SP_MAX_Q" value="10000"/>
    <define name="SP_MAX_R" value="10000"/>
    <define name="DEADBAND_P" value="20"/>
    <define name="DEADBAND_Q" value="20"/>
    <define name="DEADBAND_R" value="200"/>
    <define name="REF_TAU" value="4"/>

    <!-- feedback -->
    <define name="GAIN_P" value="400"/>
    <define name="GAIN_Q" value="400"/>
    <define name="GAIN_R" value="350"/>

    <define name="IGAIN_P" value="75"/>
    <define name="IGAIN_Q" value="75"/>
    <define name="IGAIN_R" value="50"/>

    <!-- feedforward -->
    <define name="DDGAIN_P" value="300"/>
    <define name="DDGAIN_Q" value="300"/>
    <define name="DDGAIN_R" value="300"/>
  </section>


  <section name="STABILIZATION_ATTITUDE" prefix="STABILIZATION_ATTITUDE_">
    <!-- setpoints -->
    <define name="SP_MAX_PHI"     value="45." unit="deg"/>
    <define name="SP_MAX_THETA"   value="45." unit="deg"/>
    <define name="SP_MAX_R"       value="90." unit="deg/s"/>
    <define name="DEADBAND_A"     value="0"/>
    <define name="DEADBAND_E"     value="0"/>
    <define name="DEADBAND_R"     value="250"/>

    <!-- reference -->
    <define name="REF_OMEGA_P"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_P"   value="0.85"/>
    <define name="REF_MAX_P"    value="400." unit="deg/s"/>
    <define name="REF_MAX_PDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_Q"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_Q"   value="0.85"/>
    <define name="REF_MAX_Q"    value="400." unit="deg/s"/>
    <define name="REF_MAX_QDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_R"  value="250" unit="deg/s"/>
    <define name="REF_ZETA_R"   value="0.85"/>
    <define name="REF_MAX_R"    value="180." unit="deg/s"/>
    <define name="REF_MAX_RDOT" value="RadOfDeg(1800.)"/>

    <!-- feedback -->
    <define name="PHI_PGAIN"  value="1000"/>
    <define name="PHI_DGAIN"  value="400"/>
    <define name="PHI_IGAIN"  value="200"/>

    <define name="THETA_PGAIN"  value="1000"/>
    <define name="THETA_DGAIN"  value="400"/>
    <define name="THETA_IGAIN"  value="200"/>

    <define name="PSI_PGAIN"  value="500"/>
    <define name="PSI_DGAIN"  value="300"/>
    <define name="PSI_IGAIN"  value="10"/>

    <!-- feedforward -->
    <define name="PHI_DDGAIN"   value="300"/>
    <define name="THETA_DDGAIN" value="300"/>
    <define name="PSI_DDGAIN"   value="300"/>
  </section>

  <section name="GUIDANCE_V" prefix="GUIDANCE_V_">
    <define name="HOVER_KP"    value="150"/>
    <define name="HOVER_KD"    value="80"/>
    <define name="HOVER_KI"    value="20"/>
    <define name="NOMINAL_HOVER_THROTTLE" value="0.5"/>
    <define name="ADAPT_THROTTLE_ENABLED" value="TRUE"/>
  </section>

  <section name="GUIDANCE_H" prefix="GUIDANCE_H_">
    <define name="MAX_BANK" value="20" unit="deg"/>
    <define name="USE_SPEED_REF" value="TRUE"/>
    <define name="PGAIN" value="50"/>
    <define name="DGAIN" value="100"/>
    <define name="AGAIN" value="70"/>
    <define name="IGAIN" value="20"/>
  </section>

  <section name="SIMULATOR" prefix="NPS_">
    <define name="ACTUATOR_NAMES"  value="{&quot;nw_motor&quot;, &quot;ne_motor&quot;, &quot;se_motor&quot;, &quot;sw_motor&quot;}"/>
    <define name="JSBSIM_MODEL"    value="&quot;HooperFly/teensyfly_quad&quot;"/>
    <define name="SENSORS_PARAMS"  value="&quot;nps_sensors_params_default.h&quot;"/>
    <!-- mode switch on joystick channel 5 (axis numbering starting at zero) -->
    <define name="JS_AXIS_MODE"    value="4"/>
  </section>

  <section name="AUTOPILOT">
    <define name="MODE_MANUAL" value="AP_MODE_ATTITUDE_DIRECT"/>
    <define name="MODE_AUTO1"  value="AP_MODE_HOVER_Z_HOLD"/>
    <define name="MODE_AUTO2"  value="AP_MODE_NAV"/>
  </section>

  <section name="BAT">
    <define name="CATASTROPHIC_BAT_LEVEL" value="9.3" unit="V"/>
    <define name="CRITIC_BAT_LEVEL"       value="9.6" unit="V"/>
    <define name="LOW_BAT_LEVEL"          value="10.1" unit="V"/>
    <define name="MAX_BAT_LEVEL"          value="12.4" unit="V"/>
  </section>

  <section name="GCS">
    <define name="ALT_SHIFT_PLUS_PLUS" value="30"/>
    <define name="ALT_SHIFT_PLUS"      value="5"/>
    <define name="ALT_SHIFT_MINUS"     value="-5"/>
    <define name="SPEECH_NAME"         value="Teensy Fly Quad"/>
    <define name="AC_ICON"             value="quadrotor_x"/>
  </section>

</airframe>

=== paparazzi/paparazzi/conf/airframes/examples/matek_h7_fixedwing_hitl.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<airframe name="Matek H7 FW HITL">

  <description>
    Mateksys FC H743 SLIM Fixedwing HITL
  </description>

  <firmware name="fixedwing">
    <configure name="PERIODIC_FREQUENCY" value="100"/>
    <configure name="USE_HARD_FAULT_RECOVERY" value="FALSE"/>

    <target name="ap" board="matek_h743_slim">
    </target>

    <target name="nps" board="pc">
      <module name="fdm" type="jsbsim"/>
    </target>

    <module name="radio_control" type="datalink"/>
    <module name="telemetry" type="transparent">
      <configure name="MODEM_PORT" value="usb_serial"/>
    </module>

    <module name="control" type="new"/>
    <module name="navigation"/>

    <configure name="HITL_PORT" value="usb_serial_debug"/>
    <module name="sensors" type="hitl">
      <define name="USE_BATTERY_MONITOR"/>
    </module>
    <module name="actuators" type="hitl"/>

    <!--module name="ahrs" type="float_dcm"/>
    <module name="ins" type="alt_float"/-->
    <module name="ins" type="float_invariant">
      <configure name="AHRS_PROPAGATE_FREQUENCY" value="100"/>
      <configure name="AHRS_CORRECT_FREQUENCY" value="100"/>
    </module>

    <module name="sys_mon"/>
    <module name="air_data"/>
  </firmware>

  <firmware name="generic_hitl">
    <target name="hitl" board="pc">
      <configure name="USE_HARD_FAULT_RECOVERY" value="FALSE"/>
      <module name="fdm" type="jsbsim"/>
      <module name="nps" type="hitl_sensors">
        <define name="AP_DEV" value="/dev/pprz-dbg" type="string"/>
      </module>
    </target>
  </firmware>

  <!-- commands section -->
  <!-- Servo Configuration -->
  <servos>
    <servo name="THROTTLE"	    no="5" min="1100" neutral="1100" max="1900"/>
    <servo name="AILERON_RIGHT" no="1" min="900" neutral="1500" max="2100"/>
    <servo name="AILERON_LEFT"	no="2" min="2100" neutral="1500" max="900"/>
    <servo name="ELEVATOR"      no="3" min="975" neutral="1500" max="2100"/>
    <servo name="RUDDER"        no="4" min="2100" neutral="1500" max="900"/>
  </servos>

  <!-- Servo Command Structure -->
  <commands>
    <axis name="THROTTLE"   failsafe_value="0"/>
    <axis name="ROLL"       failsafe_value="0"/>
    <axis name="PITCH"      failsafe_value="0"/>
    <axis name="YAW"        failsafe_value="0"/>
  </commands>

  <!-- RC Command Structure -->
  <rc_commands>
    <set command="THROTTLE" value="@THROTTLE"/>
    <set command="ROLL"     value="@ROLL"/>
    <set command="PITCH"    value="@PITCH"/>
    <set command="YAW"	    value="@YAW"/>
  </rc_commands>

  <!-- Define RC commands to Servo in Auto Mode -->
  <auto_rc_commands>
    <set command="YAW"  value="@YAW"/>
  </auto_rc_commands>

  <!-- Define Mixing Parameters -->
  <section name="MIXER">
    <define name="AILERON_AILERON_RATE" value="0.9"/>
    <define name="ELEV_ELEV_RATE" value="0.8"/>
  </section>

  <!-- Define RC commands to Servos in Manual -->
  <command_laws>
    <let var="aileron" value="@ROLL * AILERON_AILERON_RATE"/>
    <let var="elevator" value="@PITCH * ELEV_ELEV_RATE"/>

    <set servo="THROTTLE"       value="@THROTTLE"/>
    <set servo="AILERON_RIGHT"  value="$aileron"/>  <!--flip signs if necessary -->
    <set servo="AILERON_LEFT"   value=" - $aileron"/>
    <set servo="ELEVATOR"       value="$elevator"/>
    <set servo="RUDDER"         value="@YAW"/>
  </command_laws>

  <!-- Define Max Roll and Pitch setpoints in Auto1 -->
  <section name="AUTO1" prefix="AUTO1_">
    <define name="MAX_ROLL" value="0.7"/>
    <define name="MAX_PITCH" value="0.6"/>
  </section>

  <section name="IMU" prefix="IMU_">
    <define name="BODY_TO_IMU_PHI"   value="0." unit="deg"/>
    <define name="BODY_TO_IMU_THETA" value="0." unit="deg"/>
    <define name="BODY_TO_IMU_PSI"   value="0." unit="deg"/>

    <!-- Dummy Mag values for NPS -
         replace with your own calibration -->
    <define name="MAG_X_NEUTRAL" value="0"/>
    <define name="MAG_Y_NEUTRAL" value="0"/>
    <define name="MAG_Z_NEUTRAL" value="0"/>
  </section>

  <include href="conf/mag/toulouse_muret.xml"/>

  <section name="INS" prefix="INS_">
    <define name="ROLL_NEUTRAL_DEFAULT"  value="0" unit="deg"/>
    <define name="PITCH_NEUTRAL_DEFAULT" value="0" unit="deg"/>
  </section>


  <!-- Define current estimator and Battery Level Warnings -->
  <section name="BAT">
    <!-- Simulator values -->
    <define name="MAX_BAT_LEVEL" value="5.0" unit="V" />
    <define name="LOW_BAT_LEVEL" value="4.0" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="3.5" unit="V"/>
    <define name="CATASTROPHIC_BAT_LEVEL" value="3.0" unit="V"/>
  </section>

  <section name="MISC">
    <define name="NOMINAL_AIRSPEED"   value="16."     unit="m/s"/> <!-- GCS only -->
    <define name="CARROT"             value="5."  unit="s"/>   <!-- GCS only -->
    <define name="KILL_MODE_DISTANCE"   value="(1.5*MAX_DIST_FROM_HOME)"/>
    <define name="DEFAULT_CIRCLE_RADIUS" value="120."/>
  </section>

  <section name="VERTICAL CONTROL" prefix="V_CTL_">
    <!-- outer loop proportional gain -->
    <define name="ALTITUDE_PGAIN" value="0.136"/>
    <!-- outer loop saturation -->
    <define name="ALTITUDE_MAX_CLIMB" value="3."/>

    <!-- auto throttle inner loop -->
    <define name="AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE" value="0.65"/>
    <define name="AUTO_THROTTLE_MIN_CRUISE_THROTTLE" value="0.20"/>
    <define name="AUTO_THROTTLE_MAX_CRUISE_THROTTLE" value="0.80"/>
    <define name="AUTO_PITCH_MAX_PITCH" value="20." unit="deg"/>
    <define name="AUTO_PITCH_MIN_PITCH" value="-20." unit="deg"/>

    <!-- Climb loop (throttle) -->
    <define name="AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT" value="0.1" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_PGAIN" value="0.006"/>
    <define name="AUTO_THROTTLE_DGAIN" value="0.0"/>
    <define name="AUTO_THROTTLE_IGAIN" value="0.035"/>
    <define name="AUTO_THROTTLE_PITCH_OF_VZ_PGAIN" value="0.09"/>

    <!-- Climb loop (pitch) -->
    <define name="AUTO_PITCH_PGAIN" value="0.027"/>
    <define name="AUTO_PITCH_DGAIN" value="0.01"/>
    <define name="AUTO_PITCH_IGAIN" value="0.0"/>

    <!-- airspeed control -->
    <define name="AUTO_AIRSPEED_SETPOINT" value="16."/>
    <define name="AUTO_AIRSPEED_THROTTLE_PGAIN" value="0.1"/>
    <define name="AUTO_AIRSPEED_THROTTLE_DGAIN" value="0.12"/>
    <define name="AUTO_AIRSPEED_THROTTLE_IGAIN" value="0.0"/>
    <define name="AUTO_AIRSPEED_PITCH_PGAIN" value="0.06"/>
    <define name="AUTO_AIRSPEED_PITCH_DGAIN" value="0.0"/>
    <define name="AUTO_AIRSPEED_PITCH_IGAIN" value="0.042"/>
    <define name="AIRSPEED_MAX" value="30" unit="m/s"/>
    <define name="AIRSPEED_MIN" value="10" unit="m/s"/>

    <!-- groundspeed control -->
    <define name="AUTO_GROUNDSPEED_SETPOINT" value="15" unit="m/s"/>
    <define name="AUTO_GROUNDSPEED_PGAIN" value="1."/>
    <define name="AUTO_GROUNDSPEED_IGAIN" value="0."/>

    <!-- pitch trim -->
    <define name="PITCH_LOITER_TRIM" value="0." unit="deg"/>
    <define name="PITCH_DASH_TRIM" value="0." unit="deg"/>

    <define name="THROTTLE_SLEW" value="0.1"/>
  </section>

  <section name="HORIZONTAL CONTROL" prefix="H_CTL_">
    <define name="COURSE_PGAIN" value="1.135"/>
    <define name="COURSE_DGAIN" value="0.35"/>
    <define name="ROLL_MAX_SETPOINT" value="0.6" unit="rad"/>
    <define name="PITCH_MAX_SETPOINT" value="0.35" unit="rad"/>
    <define name="PITCH_MIN_SETPOINT" value="-0.2" unit="rad"/>

    <define name="PITCH_PGAIN" value="10000."/>
    <define name="PITCH_DGAIN" value="1500"/>
    <define name="PITCH_IGAIN" value="500"/>
     
    <define name="ROLL_ATTITUDE_GAIN" value="9000"/>
    <define name="ROLL_RATE_GAIN" value="1600"/>
    <define name="ROLL_IGAIN" value="100."/>

    <define name="PITCH_OF_ROLL" value="1." unit="deg"/>
    <define name="AILERON_OF_THROTTLE" value="0.0"/>
  </section>

  <section name="AGGRESSIVE" prefix="AGR_">
    <define name="BLEND_START" value="20"/><!-- Altitude Error to Initiate Aggressive Climb CANNOT BE ZERO!!-->
    <define name="BLEND_END" value="10"/><!-- Altitude Error to Blend Aggressive to Regular Climb Modes  CANNOT BE ZERO!!-->
    <define name="CLIMB_THROTTLE" value="0.85"/><!-- Gaz for Aggressive Climb -->
    <define name="CLIMB_PITCH" value="0.13"/><!-- Pitch for Aggressive Climb -->
    <define name="DESCENT_THROTTLE" value="0.1"/><!-- Gaz for Aggressive Decent -->
    <define name="DESCENT_PITCH" value="-0.1"/><!-- Pitch for Aggressive Decent -->
    <define name="CLIMB_NAV_RATIO" value="0.8"/><!-- Percent Navigation for Altitude Error Equal to Start Altitude -->
    <define name="DESCENT_NAV_RATIO" value="1.0"/>
  </section>

  <section name="FAILSAFE" prefix="FAILSAFE_">
    <define name="DELAY_WITHOUT_GPS" value="5" unit="s"/>
    <define name="DEFAULT_THROTTLE" value="0" unit="%"/>
    <define name="DEFAULT_ROLL" value="0.3" unit="rad"/>
    <define name="DEFAULT_PITCH" value="0.5" unit="rad"/>
    <define name="HOME_RADIUS" value="100" unit="m"/>
  </section>

  <section name="SIMULATOR" prefix="NPS_">
    <define name="JSBSIM_LAUNCHSPEED" value="15"/>
    <define name="JSBSIM_MODEL" value="easystar" type="string"/>
    <define name="JS_AXIS_MODE" value="4"/>
  </section>

</airframe>
