=== paparazzi/paparazzi/conf/airframes/airframe.dtd
<!-- Paparazzi airframe DTD -->

<!ELEMENT airframe (include|servos|commands|rc_commands|auto_rc_commands|ap_only_commands|command_laws|section|modules|firmware|autopilot|heli_curves|description)*>
<!ELEMENT include EMPTY>
<!ELEMENT servos (servo)*>
<!ELEMENT commands (axis)*>
<!ELEMENT rc_commands (set)*>
<!ELEMENT auto_rc_commands (set)*>
<!ELEMENT ap_only_commands (copy)*>
<!ELEMENT command_laws (let|set|call|ratelimit)*>
<!ELEMENT heli_curves (curve)*>
<!ELEMENT section (define|comment)*>
<!ELEMENT servo EMPTY>
<!ELEMENT axis EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT ratelimit EMPTY>
<!ELEMENT copy EMPTY>
<!ELEMENT curve EMPTY>
<!ELEMENT let EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT modules (module)*>
<!ELEMENT configure EMPTY>
<!ELEMENT firmware (target|module|autopilot|configure|define|comment)*>
<!ELEMENT target (module|autopilot|configure|define|comment)*>
<!ELEMENT module (configure|define|comment)*>
<!ELEMENT autopilot EMPTY>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST include
href CDATA #REQUIRED>

<!ATTLIST firmware
name CDATA #REQUIRED>

<!ATTLIST autopilot
name CDATA #REQUIRED
freq CDATA #IMPLIED>

<!ATTLIST target
name CDATA #REQUIRED
board CDATA #REQUIRED>

<!ATTLIST airframe
name CDATA #IMPLIED>

<!ATTLIST servos
driver CDATA #IMPLIED>

<!ATTLIST commands>
<!ATTLIST rc_commands>
<!ATTLIST ap_only_commands>
<!ATTLIST command_laws>

<!ATTLIST heli_curves>

<!ATTLIST section
name CDATA #IMPLIED
prefix CDATA #IMPLIED>

<!ATTLIST servo
name CDATA #REQUIRED
no CDATA #REQUIRED
min CDATA #REQUIRED
neutral CDATA #REQUIRED
max CDATA #REQUIRED>

<!ATTLIST curve
throttle CDATA #REQUIRED
rpm CDATA #IMPLIED
collective CDATA #REQUIRED>

<!ATTLIST axis
name CDATA #REQUIRED
failsafe_value CDATA #REQUIRED>

<!ATTLIST set
value CDATA #REQUIRED
command CDATA #IMPLIED
servo CDATA #IMPLIED>

<!ATTLIST call
fun CDATA #REQUIRED>

<!ATTLIST copy
command CDATA #REQUIRED>

<!ATTLIST let
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST ratelimit
var CDATA #REQUIRED
value CDATA #REQUIRED
rate_min CDATA #REQUIRED
rate_max CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
unit CDATA #IMPLIED
code_unit CDATA #IMPLIED
integer CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED
description CDATA #IMPLIED>

<!ATTLIST modules
main_freq CDATA #IMPLIED
target CDATA #IMPLIED>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED
dir CDATA #IMPLIED>

=== paparazzi/paparazzi/conf/airframes/untested/examples/easystar.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<!--
    Multiplex EasyStar, using rudder
    TWOG v1 board
    Tilted infrared sensor
    XBee 2.4GHz modem in transparent mode
-->

<airframe name="EasyStar TWOGv1">

  <firmware name="fixedwing">
    <target name="ap" 			board="twog_1.0"/>
    <target name="sim" 			board="pc"/>

    <define name="LOITER_TRIM"/>

    <subsystem name="radio_control" type="ppm"/>
    <subsystem name="telemetry" type="transparent"/>
    <subsystem name="control"/>
    <subsystem name="gps" type="ublox"/>
    <subsystem name="navigation"/>
    <subsystem name="ins" type="alt_float"/>
  </firmware>

  <firmware name="setup">
    <target name="tunnel" 		board="twog_1.0"/>
  </firmware>

  <modules>
    <load name="infrared_adc.xml"/>
    <load name="ahrs_infrared.xml"/>
  </modules>

<!-- commands section -->
  <servos>
    <servo name="THROTTLE"      no="7" min="1120" neutral="1120" max="1920"/>
    <servo name="ELEVATOR"      no="3" min="1100" neutral="1515" max="1900"/>
    <servo name="RUDDER"        no="4" min="950" neutral="1440" max="2050"/>
  </servos>

  <commands>
    <axis name="THROTTLE" failsafe_value="0"/>
    <axis name="ROLL"     failsafe_value="0"/>
    <axis name="PITCH"    failsafe_value="0"/>
  </commands>

  <rc_commands>
    <set command="ROLL"      value="@ROLL"/>
    <set command="PITCH"     value="@PITCH"/>
    <set command="THROTTLE"  value="@THROTTLE"/>
  </rc_commands>

  <command_laws>
    <set servo="THROTTLE"    value="@THROTTLE"/>
    <set servo="RUDDER"      value="@ROLL"/>
    <set servo="ELEVATOR"    value="@PITCH"/>
  </command_laws>

  <section name="AUTO1" prefix="AUTO1_">
    <define name="MAX_ROLL" value="50" unit="deg"/>
    <define name="MAX_PITCH" value="40" unit="deg"/>
  </section>

  <section name="INFRARED" prefix="IR_">
    <define name="ADC_IR1_NEUTRAL" value="512"/>
    <define name="ADC_IR2_NEUTRAL" value="510"/>
    <define name="ADC_TOP_NEUTRAL" value="500"/>

    <define name="LATERAL_CORRECTION" value="0.7"/>
    <define name="LONGITUDINAL_CORRECTION" value="0.7"/>
    <define name="VERTICAL_CORRECTION" value="1."/>

    <define name="HORIZ_SENSOR_TILTED" value="1"/>
    <define name="IR1_SIGN" value="1"/>
    <define name="IR2_SIGN" value="-1"/>
    <define name="TOP_SIGN" value="1"/>

    <define name="ROLL_NEUTRAL_DEFAULT" value="-5.3" unit="deg"/>
    <define name="PITCH_NEUTRAL_DEFAULT" value="-3" unit="deg"/>

    <define name="CORRECTION_UP" value="1."/>
    <define name="CORRECTION_DOWN" value="1."/>
    <define name="CORRECTION_LEFT" value="1."/>
    <define name="CORRECTION_RIGHT" value="1."/>
  </section>


  <section name="BAT">
    <define name="MILLIAMP_AT_FULL_THROTTLE" value="20000" unit="mA"/>
    <define name="CATASTROPHIC_BAT_LEVEL" value="8.0" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="8.5" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="9.5" unit="V"/>
    <define name="MAX_BAT_LEVEL" value="12.5" unit="V"/>
  </section>

  <section name="MISC">
    <define name="NOMINAL_AIRSPEED" value="15." unit="m/s"/>
    <define name="CARROT" value="4." unit="s"/>
    <define name="KILL_MODE_DISTANCE" value="(2.0*MAX_DIST_FROM_HOME)"/>
    <define name="CONTROL_FREQUENCY" value="60" unit="Hz"/>
    <define name="NO_XBEE_API_INIT" value="TRUE"/>
    <define name="TRIGGER_DELAY" value="1."/>
    <define name="DEFAULT_CIRCLE_RADIUS" value="100."/>
  </section>

  <section name="VERTICAL CONTROL" prefix="V_CTL_">
    <define name="POWER_CTL_BAT_NOMINAL" value="11.0" unit="volt"/>
    <!-- outer loop -->
    <define name="ALTITUDE_PGAIN" value="0.075" unit="(m/s)/m"/>
    <define name="ALTITUDE_MAX_CLIMB" value="4." unit="m/s"/>
    <!-- auto throttle inner loop -->
    <define name="AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE" value="0.5" unit="%"/>
    <define name="AUTO_THROTTLE_MIN_CRUISE_THROTTLE" value="0.4" unit="%"/>
    <define name="AUTO_THROTTLE_MAX_CRUISE_THROTTLE" value="0.8" unit="%"/>
    <define name="AUTO_THROTTLE_LOITER_TRIM" value="1500" unit="pprz_t"/>
    <define name="AUTO_THROTTLE_DASH_TRIM" value="-1000" unit="pprz_t"/>
    <define name="AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT" value="0.1" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_PGAIN" value="0.02" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_IGAIN" value="0.1"/>
    <define name="AUTO_THROTTLE_PITCH_OF_VZ_PGAIN" value="0.05" unit="rad/(m/s)"/>
    <define name="AUTO_PITCH_PGAIN" value="0.125"/>
    <define name="AUTO_PITCH_IGAIN" value="0.025"/>
    <define name="AUTO_PITCH_MAX_PITCH" value="RadOfDeg(25)"/>
    <define name="AUTO_PITCH_MIN_PITCH" value="RadOfDeg(-25)"/>
    <define name="THROTTLE_SLEW" value="1.0"/>
  </section>

  <section name="HORIZONTAL CONTROL" prefix="H_CTL_">
    <define name="COURSE_PGAIN" value="0.7"/>
    <define name="ROLL_MAX_SETPOINT" value="35" unit="deg"/>
    <define name="PITCH_MAX_SETPOINT" value="25" unit="deg"/>
    <define name="PITCH_MIN_SETPOINT" value="-25" unit="deg"/>
    <define name="PITCH_PGAIN" value="20000."/>
    <define name="PITCH_DGAIN" value="1.5"/>
    <define name="ELEVATOR_OF_ROLL" value="2500"/>
    <define name="ROLL_ATTITUDE_GAIN" value="7400"/>
    <define name="ROLL_RATE_GAIN" value="200"/>
  </section>

  <section name="NAV">
    <define name="NAV_GLIDE_PITCH_TRIM" value="0"/>
  </section>

  <section name="AGGRESSIVE" prefix="AGR_">
    <define name="BLEND_START" value="20"/><!-- Altitude Error to Initiate Aggressive Climb CANNOT BE ZERO!!-->
    <define name="BLEND_END" value="10"/><!-- Altitude Error to Blend Aggressive to Regular Climb Modes  CANNOT BE ZERO!!-->
    <define name="CLIMB_THROTTLE" value="0.9"/><!-- Gaz for Aggressive Climb -->
    <define name="CLIMB_PITCH" value="RadOfDeg(18)"/><!-- Pitch for Aggressive Climb -->
    <define name="DESCENT_THROTTLE" value="0.1"/><!-- Gaz for Aggressive Decent -->
    <define name="DESCENT_PITCH" value="RadOfDeg(-20)"/><!-- Pitch for Aggressive Decent -->
    <define name="CLIMB_NAV_RATIO" value="0.8"/><!-- Percent Navigation for Altitude Error Equal to Start Altitude -->
    <define name="DESCENT_NAV_RATIO" value="1.0"/>
  </section>

  <section name="FAILSAFE" prefix="FAILSAFE_">
    <define name="DELAY_WITHOUT_GPS" value="3" unit="s"/>
    <define name="DEFAULT_THROTTLE" value="0.4" unit="%"/>
    <define name="DEFAULT_ROLL" value="15" unit="deg"/>
    <define name="DEFAULT_PITCH" value="0" unit="deg"/>
    <define name="HOME_RADIUS" value="90" unit="m"/>
  </section>

</airframe>

=== paparazzi/paparazzi/conf/airframes/untested/hex_naze32.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<!-- this is a test file for the Abusemark Naze32 rev5 board:
     * Autopilot:   Abusemark Naze32       https://code.google.com/p/afrodevices/wiki/AfroFlight32
     * Actuators:   PWM motor controllers  http://wiki.paparazziuav.org/wiki/Subsystem/actuators#PWM
     * RC:          PPM input              http://wiki.paparazziuav.org/wiki/Subsystem/radio_control#PPM

     hex copter configuration (USE_SERVOS_5AND6) moves the PPM input from "1" to "6" on RC input
     pwm motor connectors are in "standard mode" M1-M6 on the servo headers
-->

<airframe name="Hexcopter Naze32">

  <firmware name="rotorcraft">
    <define name="PPRZ_TRIG_INT_COMPR_FLASH"/>
    <define name="PPRZ_TRIG_INT_COMPR_HIGHEST"/>
    <target name="ap" board="naze32_rev5">
    </target>

    <subsystem name="radio_control" type="ppm"/>

    <subsystem name="motor_mixing"/>
    <subsystem name="actuators"     type="pwm">
      <define name="SERVO_HZ" value="400"/>
    </subsystem>

    <subsystem name="telemetry"     type="transparent"/>
    <subsystem name="imu"           type="mpu60x0_i2c">
      <configure name="IMU_MPU60X0_I2C_DEV" value="i2c2"/>
      <configure name="USE_MAGNETOMETER" value="FALSE"/>
    </subsystem>
    <subsystem name="stabilization" type="int_quat"/>
    <subsystem name="ahrs"          type="int_cmpl_quat">
      <define name="AHRS_GRAVITY_HEURISTIC_FACTOR" value="30"/>
    </subsystem>
    <subsystem name="ins"/>
    <subsystem name="gps"           type="ublox"/>
  </firmware>

  <firmware name="test_progs">
    <target name="test_sys_time_timer" board="naze32_rev5"/>
    <target name="test_sys_time_usleep" board="naze32_rev5"/>
    <target name="test_telemetry" board="naze32_rev5"/>
    <target name="test_math_trig_lut" board="naze32_rev5"/>
    <target name="test_imu" board="naze32_rev5">
      <subsystem name="imu" type="mpu6000"/>
    </target>
    <target name="test_ahrs" board="naze32_rev5">
      <subsystem name="imu" type="mpu6000"/>
      <subsystem name="ahrs" type="int_cmpl_quat"/>
      <configure name="USE_MAGNETOMETER" value="FALSE"/>
    </target>
  </firmware>

  <modules>
    <load name="mag_hmc58xx.xml">
      <define name="MODULE_HMC58XX_UPDATE_AHRS"/>
      <configure name="MAG_HMC58XX_I2C_DEV" value="i2c2"/>
    </load>
    <load name="gps_ubx_ucenter.xml"/>
  </modules>

  <servos driver="Pwm">
    <!-- Naze32 Hexa-X standard -->
    <servo name="BACK_RIGHT"   no="0" min="1000" neutral="1100" max="1900"/>
    <servo name="FRONT_RIGHT"  no="1" min="1000" neutral="1100" max="1900"/>
    <servo name="BACK_LEFT"    no="2" min="1000" neutral="1100" max="1900"/>
    <servo name="FRONT_LEFT"   no="3" min="1000" neutral="1100" max="1900"/>
    <servo name="CENTER_RIGHT" no="4" min="1000" neutral="1100" max="1900"/>
    <servo name="CENTER_LEFT"  no="5" min="1000" neutral="1100" max="1900"/>
  </servos>

  <commands>
    <axis name="ROLL"   failsafe_value="0"/>
    <axis name="PITCH"  failsafe_value="0"/>
    <axis name="YAW"    failsafe_value="0"/>
    <axis name="THRUST" failsafe_value="0"/>
  </commands>

  <section name="MIXING" prefix="MOTOR_MIXING_">
    <define name="TRIM_ROLL" value="0"/>
    <define name="TRIM_PITCH" value="0"/>
    <define name="TRIM_YAW" value="0"/>
    <define name="NB_MOTOR" value="6"/>
    <define name="SCALE" value="256"/>
    <!-- https://github.com/gearwolf-OP/Mini-Hexacopter >
    <    Naze32 Hexa-X standard        BR_CC FR_CC  BL_C  FL_C  CR_C CL_CC  -->
    <define name="ROLL_COEF"   value="{ 106,  150, -106, -150,  256, -256}"/>
    <define name="PITCH_COEF"  value="{-256,  256, -256,  256,    0,    0}"/>
    <define name="YAW_COEF"    value="{ 199,  192, -199, -192, -256,  256}"/>
    <define name="THRUST_COEF" value="{ 256,  256,  256,  256,  256,  256}"/>
  </section>

  <command_laws>
    <call fun="motor_mixing_run(autopilot_motors_on,FALSE,values)"/>
    <set servo="BACK_RIGHT"   value="motor_mixing.commands[0]"/>
    <set servo="FRONT_RIGHT"  value="motor_mixing.commands[1]"/>
    <set servo="BACK_LEFT"    value="motor_mixing.commands[2]"/>
    <set servo="FRONT_LEFT"   value="motor_mixing.commands[3]"/>
    <set servo="CENTER_RIGHT" value="motor_mixing.commands[4]"/>
    <set servo="CENTER_LEFT"  value="motor_mixing.commands[5]"/>
  </command_laws>

  <section name="IMU" prefix="IMU_">
    <define name="BODY_TO_IMU_PHI"   value="180." unit="deg"/>
    <define name="BODY_TO_IMU_THETA" value="0." unit="deg"/>
    <define name="BODY_TO_IMU_PSI"   value="0." unit="deg"/>
  </section>

  <section name="STABILIZATION_RATE" prefix="STABILIZATION_RATE_">
    <!-- setpoints -->
    <define name="SP_MAX_P" value="140" unit="deg/s"/>
    <define name="SP_MAX_Q" value="140" unit="deg/s"/>
    <define name="SP_MAX_R" value="140" unit="deg/s"/>
    <define name="DEADBAND_P" value="20"/>
    <define name="DEADBAND_Q" value="20"/>
    <define name="DEADBAND_R" value="200"/>
    <define name="REF_TAU" value="4"/>

    <!-- feedback -->
    <define name="GAIN_P" value="400"/>
    <define name="GAIN_Q" value="400"/>
    <define name="GAIN_R" value="350"/>

    <define name="IGAIN_P" value="75"/>
    <define name="IGAIN_Q" value="75"/>
    <define name="IGAIN_R" value="50"/>

    <!-- feedforward -->
    <define name="DDGAIN_P" value="300"/>
    <define name="DDGAIN_Q" value="300"/>
    <define name="DDGAIN_R" value="300"/>
  </section>


  <section name="STABILIZATION_ATTITUDE" prefix="STABILIZATION_ATTITUDE_">
    <!-- setpoints -->
    <define name="SP_MAX_PHI"     value="45." unit="deg"/>
    <define name="SP_MAX_THETA"   value="45." unit="deg"/>
    <define name="SP_MAX_R"       value="90." unit="deg/s"/>
    <define name="DEADBAND_A"     value="0"/>
    <define name="DEADBAND_E"     value="0"/>
    <define name="DEADBAND_R"     value="250"/>

    <!-- reference -->
    <define name="REF_OMEGA_P"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_P"   value="0.85"/>
    <define name="REF_MAX_P"    value="400." unit="deg/s"/>
    <define name="REF_MAX_PDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_Q"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_Q"   value="0.85"/>
    <define name="REF_MAX_Q"    value="400." unit="deg/s"/>
    <define name="REF_MAX_QDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_R"  value="250" unit="deg/s"/>
    <define name="REF_ZETA_R"   value="0.85"/>
    <define name="REF_MAX_R"    value="180." unit="deg/s"/>
    <define name="REF_MAX_RDOT" value="RadOfDeg(1800.)"/>

    <!-- feedback -->
    <define name="PHI_PGAIN"  value="1000"/>
    <define name="PHI_DGAIN"  value="400"/>
    <define name="PHI_IGAIN"  value="200"/>

    <define name="THETA_PGAIN"  value="1000"/>
    <define name="THETA_DGAIN"  value="400"/>
    <define name="THETA_IGAIN"  value="200"/>

    <define name="PSI_PGAIN"  value="500"/>
    <define name="PSI_DGAIN"  value="300"/>
    <define name="PSI_IGAIN"  value="10"/>

    <!-- feedforward -->
    <define name="PHI_DDGAIN"   value="300"/>
    <define name="THETA_DDGAIN" value="300"/>
    <define name="PSI_DDGAIN"   value="300"/>
  </section>

  <section name="GUIDANCE_V" prefix="GUIDANCE_V_">
    <define name="HOVER_KP"    value="150"/>
    <define name="HOVER_KD"    value="80"/>
    <define name="HOVER_KI"    value="20"/>
    <define name="NOMINAL_HOVER_THROTTLE" value="0.5"/>
    <define name="ADAPT_THROTTLE_ENABLED" value="TRUE"/>
  </section>

  <section name="GUIDANCE_H" prefix="GUIDANCE_H_">
    <define name="MAX_BANK" value="20" unit="deg"/>
    <define name="USE_SPEED_REF" value="TRUE"/>
    <define name="PGAIN" value="50"/>
    <define name="DGAIN" value="100"/>
    <define name="AGAIN" value="70"/>
    <define name="IGAIN" value="20"/>
  </section>

  <section name="AUTOPILOT">
    <define name="MODE_MANUAL" value="AP_MODE_RATE_DIRECT"/>
    <define name="MODE_AUTO1"  value="AP_MODE_ATTITUDE_DIRECT"/>
    <define name="MODE_AUTO2"  value="AP_MODE_HOVER_Z_HOLD"/>
  </section>

  <section name="BAT">
    <define name="CATASTROPHIC_BAT_LEVEL" value="9.3" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="9.6" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="10.1" unit="V"/>
    <define name="MAX_BAT_LEVEL" value="12.4" unit="V"/>
    <define name="MILLIAMP_AT_FULL_THROTTLE" value="30000"/>
  </section>

</airframe>

=== paparazzi/paparazzi/conf/airframes/obsolete/mm/fixed-wing/trojan.xml
<!DOCTYPE airframe SYSTEM "../../airframe.dtd">

<!-- Parkzone T-28D Trojan
     Tiny 2.11 board (http://paparazzi.enac.fr/wiki/index.php/Tiny_v2)
     XBee modem
     LEA 5H
-->

<airframe name="T28">

  <firmware name="fixedwing">
    <define name="AGR_CLIMB"/>
    <define name="LOITER_TRIM"/>
    <define name="ALT_KALMAN"/>
    <define name="WIND_INFO"/>
    <define name="WIND_INFO_RET"/>

    <target name="ap"                  board="tiny_2.11">
      <define name="SENSOR_SYNC_SEND"/>
      <configure name="PERIODIC_FREQUENCY" value="120"/>
      <configure name="AHRS_PROPAGATE_FREQUENCY" value="100"/>
      <configure name="AHRS_CORRECT_FREQUENCY" value="100"/>
      <define name="AHRS_TRIGGERED_ATTITUDE_LOOP" />
      <define name="USE_AHRS_GPS_ACCELERATIONS" />
    </target>

    <target name="sim"                 board="pc">
    </target>

    <!-- RC -->
    <subsystem name="radio_control"    type="ppm"/>
    <!-- Communication -->
    <subsystem name="telemetry"        type="xbee_api"/>
    <!-- Actuators are automatically chosen according to board-->
    <subsystem name="control"/>
    <!-- Sensors -->
    <subsystem name="imu"              type="aspirin2_i2c"/>
    <subsystem name="ahrs"             type="float_dcm"/>
    <subsystem name="gps"              type="ublox"/>
    <!-- Nav -->
    <subsystem name="navigation"/>
    <!-- Interfaces -->
    <!--subsystem name="spi"/-->
  </firmware>

  <firmware name="setup">
    <target name="tunnel"              board="tiny_2.11"/>
    <target name="usb_tunnel_0"        board="tiny_2.11"/>
    <target name="usb_tunnel_1"        board="tiny_2.11"/>
    <target name="setup_actuators"     board="tiny_2.11"/>
  </firmware>

  <!-- modules -->
  <modules>
  </modules>

  <!-- commands section -->
  <servos>
    <servo name="MOTOR"         no="0" min="1000" neutral="1000" max="2000"/>
    <servo name="AILERON_LEFT"  no="2" min="1100" neutral="1545" max="1900"/>
    <servo name="AILERON_RIGHT" no="6" min="1100" neutral="1545" max="1900"/>
    <servo name="ELEVATOR"      no="7" min="1900" neutral="1504" max="1100"/>
    <servo name="RUDDER"        no="3" min="1100" neutral="1419" max="1900"/>
  </servos>

  <commands>
    <axis name="THROTTLE" failsafe_value="0"/>
    <axis name="ROLL"     failsafe_value="0"/>
    <axis name="PITCH"    failsafe_value="0"/>
    <axis name="YAW"      failsafe_value="0"/>
  </commands>

  <rc_commands>
    <set command="THROTTLE" value="@THROTTLE"/>
    <set command="ROLL"     value="@ROLL"/>
    <set command="PITCH"    value="@PITCH"/>
    <set command="YAW"      value="@YAW"/>
  </rc_commands>

  <auto_rc_commands>
  </auto_rc_commands>

  <command_laws>
    <set servo="MOTOR"         value="@THROTTLE"/>
    <set servo="AILERON_LEFT"  value="@ROLL"/>
    <set servo="AILERON_RIGHT" value="@ROLL"/>
    <set servo="ELEVATOR"      value="@PITCH"/>
    <set servo="RUDDER"        value="@YAW"/>
  </command_laws>

  <section name="IMU" prefix="IMU_">
    <!-- Calibration Neutral -->
    <define name="GYRO_P_NEUTRAL" value="0"/>
    <define name="GYRO_Q_NEUTRAL" value="0"/>
    <define name="GYRO_R_NEUTRAL" value="0"/>

    <!-- SENS = 16.4 LSB/(deg/sec) * 57.6 deg/rad = 939.650 LSB/rad/sec / 12bit FRAC: 4096 / 939.65 -->
    <define name="GYRO_P_SENS" value="4.359" integer="16"/>
    <define name="GYRO_Q_SENS" value="4.359" integer="16"/>
    <define name="GYRO_R_SENS" value="4.359" integer="16"/>

    <define name="GYRO_P_Q" value="0."/>
    <define name="GYRO_P_R" value="0"/>
    <define name="GYRO_Q_P" value="0."/>
    <define name="GYRO_Q_R" value="0."/>
    <define name="GYRO_R_P" value="0."/>
    <define name="GYRO_R_Q" value="0."/>

    <define name="GYRO_P_SIGN" value="1"/>
    <define name="GYRO_Q_SIGN" value="1"/>
    <define name="GYRO_R_SIGN" value="1"/>

    <define name="ACCEL_X_NEUTRAL" value="0"/>
    <define name="ACCEL_Y_NEUTRAL" value="0"/>
    <define name="ACCEL_Z_NEUTRAL" value="0"/>

    <!-- SENS = 2048 LSB/g / 9.81 ms2/g = 208.766564729 LSB/ms2 / 10bit FRAC: 1024 / 208.7665 -->
    <define name="ACCEL_X_SENS" value="9.81" integer="16"/>
    <define name="ACCEL_Y_SENS" value="9.81" integer="16"/>
    <define name="ACCEL_Z_SENS" value="9.81" integer="16"/>

<!--
    <define name="ACCEL_X_SENS" value="4.905" integer="16"/>
    <define name="ACCEL_Y_SENS" value="4.905" integer="16"/>
    <define name="ACCEL_Z_SENS" value="4.905" integer="16"/>
-->
    <define name="ACCEL_X_SIGN" value="1"/>
    <define name="ACCEL_Y_SIGN" value="1"/>
    <define name="ACCEL_Z_SIGN" value="1"/>

    <define name="MAG_X_NEUTRAL" value="0"/>
    <define name="MAG_Y_NEUTRAL" value="0"/>
    <define name="MAG_Z_NEUTRAL" value="0"/>

    <define name="MAG_X_SENS" value="1" integer="16"/>
    <define name="MAG_Y_SENS" value="1" integer="16"/>
    <define name="MAG_Z_SENS" value="1" integer="16"/>

    <define name="MAG_X_SIGN" value="1"/>
    <define name="MAG_Y_SIGN" value="1"/>
    <define name="MAG_Z_SIGN" value="1"/>

    <define name="BODY_TO_IMU_PHI" value="0"/>
    <define name="BODY_TO_IMU_THETA" value="0"/>
    <define name="BODY_TO_IMU_PSI" value="0"/>
  </section>

  <section name="INS" prefix="INS_">
    <define name="ROLL_NEUTRAL_DEFAULT" value="3" unit="deg"/>
    <define name="PITCH_NEUTRAL_DEFAULT" value="2" unit="deg"/>
  </section>

  <section name="AUTO1" prefix="AUTO1_">
    <define name="MAX_ROLL" value="0.85"/>
    <define name="MAX_PITCH" value="0.6"/>
  </section>

  <section name="BAT">
    <!--define name="MILLIAMP_AT_FULL_THROTTLE" value="10000."/-->
    <define name="CATASTROPHIC_BAT_LEVEL" value="9.3" unit="V"/>
                                        <!-- 0.0247311828 -->
                                        <!-- 0.02432905 -->
    <define name="VoltageOfAdc(adc)" value="(0.02454*adc)"/>
  </section>

  <section name="MISC">
    <define name="NOMINAL_AIRSPEED" value="15." unit="m/s"/>
    <define name="CARROT" value="5." unit="s"/>
    <define name="KILL_MODE_DISTANCE" value="(1.5*MAX_DIST_FROM_HOME)"/>
    <define name="CONTROL_FREQUENCY" value="60" unit="Hz"/>
<!--    <define name="XBEE_INIT" value="\"ATPL2\rATRN1\rATTT80\r\""/> -->
<!--    <define name="NO_XBEE_API_INIT" value="TRUE"/> -->
    <define name="ALT_KALMAN_ENABLED" value="FALSE"/>

    <define name="TRIGGER_DELAY" value="1."/>
    <define name="DEFAULT_CIRCLE_RADIUS" value="120."/>

    <define name="COMMAND_ROLL_TRIM" value="0"/>
    <define name="COMMAND_PITCH_TRIM" value="0"/>
  </section>

  <section name="VERTICAL CONTROL" prefix="V_CTL_">

    <define name="POWER_CTL_BAT_NOMINAL" value="11.1" unit="volt"/>
    <!-- outer loop proportional gain -->
    <define name="ALTITUDE_PGAIN" value="0.1"/> <!-- -0.06 -->
    <!-- outer loop saturation -->
    <define name="ALTITUDE_MAX_CLIMB" value="2."/>

    <!-- auto throttle inner loop -->
    <define name="AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE" value="0.66"/>
    <define name="AUTO_THROTTLE_MIN_CRUISE_THROTTLE" value="0.55"/>
    <define name="AUTO_THROTTLE_MAX_CRUISE_THROTTLE" value="0.85"/>
    <define name="AUTO_THROTTLE_LOITER_TRIM" value="1000"/>
    <define name="AUTO_THROTTLE_DASH_TRIM" value="-600"/>
    <define name="AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT" value="0.2" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_PGAIN" value="0.023"/> <!-- -0.012 -->
    <define name="AUTO_THROTTLE_IGAIN" value="0.01"/>
    <define name="AUTO_THROTTLE_PITCH_OF_VZ_PGAIN" value="0.05"/>

    <!-- auto pitch inner loop -->
    <define name="AUTO_PITCH_PGAIN" value="0.06"/> <!-- -0.03 -->
    <define name="AUTO_PITCH_IGAIN" value="0.0"/>
    <define name="AUTO_PITCH_MAX_PITCH" value="0.35"/>
    <define name="AUTO_PITCH_MIN_PITCH" value="-0.35"/>

   <define name="THROTTLE_SLEW" value="0.1"/>

  </section>

  <section name="HORIZONTAL CONTROL" prefix="H_CTL_">
    <define name="COURSE_PGAIN" value="1.1"/>
    <define name="ROLL_MAX_SETPOINT" value="0.85" unit="rad"/> <!-- 0.5 -->
    <define name="PITCH_MAX_SETPOINT" value="0.5" unit="rad"/>
    <define name="PITCH_MIN_SETPOINT" value="-0.5" unit="rad"/>

    <define name="ROLL_PGAIN" value="14000."/>
    <define name="AILERON_OF_THROTTLE" value="0.0"/>
    <define name="PITCH_PGAIN" value="7500."/>
    <define name="PITCH_DGAIN" value="0.4"/>

    <define name="ELEVATOR_OF_ROLL" value="2400"/>

    <!--define name="ROLL_ATTITUDE_GAIN" value="7500"/>
    <define name="ROLL_RATE_GAIN" value="1500"/-->

  </section>

  <section name="NAV">
    <define name="NAV_GLIDE_PITCH_TRIM" value="0"/>
  </section>

  <section name="AGGRESSIVE" prefix="AGR_">
    <define name="BLEND_START" value="50"/><!-- Altitude Error to Initiate Aggressive Climb CANNOT BE ZERO!!-->
    <define name="BLEND_END" value="15"/><!-- Altitude Error to Blend Aggressive to Regular Climb Modes  CANNOT BE ZERO!!-->
    <define name="CLIMB_THROTTLE" value="0.9"/><!-- Gaz for Aggressive Climb -->
    <define name="CLIMB_PITCH" value="0.35"/><!-- Pitch for Aggressive Climb -->
    <define name="DESCENT_THROTTLE" value="0.05"/><!-- Gaz for Aggressive Decent -->
    <define name="DESCENT_PITCH" value="-0.35"/><!-- Pitch for Aggressive Decent -->
    <define name="CLIMB_NAV_RATIO" value="0.8"/><!-- Percent Navigation for Altitude Error Equal to Start Altitude -->
    <define name="DESCENT_NAV_RATIO" value="1.0"/>
    </section>

  <section name="FAILSAFE" prefix="FAILSAFE_">
	<define name="DELAY_WITHOUT_GPS" value="2" unit="s"/>
    	<define name="DEFAULT_THROTTLE" value="0.3" unit="%"/>
    	<define name="DEFAULT_ROLL" value="0.3" unit="rad"/>
    	<define name="DEFAULT_PITCH" value="0.5" unit="rad"/>
	<define name="HOME_RADIUS" value="100" unit="m"/>
</section>
</airframe>
