=== paparazzi/paparazzi/conf/airframes/airframe.dtd
<!-- Paparazzi airframe DTD -->

<!ELEMENT airframe (include|servos|commands|rc_commands|auto_rc_commands|ap_only_commands|command_laws|section|modules|firmware|autopilot|heli_curves|description)*>
<!ELEMENT include EMPTY>
<!ELEMENT servos (servo)*>
<!ELEMENT commands (axis)*>
<!ELEMENT rc_commands (set)*>
<!ELEMENT auto_rc_commands (set)*>
<!ELEMENT ap_only_commands (copy)*>
<!ELEMENT command_laws (let|set|call|ratelimit)*>
<!ELEMENT heli_curves (curve)*>
<!ELEMENT section (define|comment)*>
<!ELEMENT servo EMPTY>
<!ELEMENT axis EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT ratelimit EMPTY>
<!ELEMENT copy EMPTY>
<!ELEMENT curve EMPTY>
<!ELEMENT let EMPTY>
<!ELEMENT define EMPTY>
<!ELEMENT modules (module)*>
<!ELEMENT configure EMPTY>
<!ELEMENT firmware (target|module|autopilot|configure|define|comment)*>
<!ELEMENT target (module|autopilot|configure|define|comment)*>
<!ELEMENT module (configure|define|comment)*>
<!ELEMENT autopilot EMPTY>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ATTLIST include
href CDATA #REQUIRED>

<!ATTLIST firmware
name CDATA #REQUIRED>

<!ATTLIST autopilot
name CDATA #REQUIRED
freq CDATA #IMPLIED>

<!ATTLIST target
name CDATA #REQUIRED
board CDATA #REQUIRED>

<!ATTLIST airframe
name CDATA #IMPLIED>

<!ATTLIST servos
driver CDATA #IMPLIED>

<!ATTLIST commands>
<!ATTLIST rc_commands>
<!ATTLIST ap_only_commands>
<!ATTLIST command_laws>

<!ATTLIST heli_curves>

<!ATTLIST section
name CDATA #IMPLIED
prefix CDATA #IMPLIED>

<!ATTLIST servo
name CDATA #REQUIRED
no CDATA #REQUIRED
min CDATA #REQUIRED
neutral CDATA #REQUIRED
max CDATA #REQUIRED>

<!ATTLIST curve
throttle CDATA #REQUIRED
rpm CDATA #IMPLIED
collective CDATA #REQUIRED>

<!ATTLIST axis
name CDATA #REQUIRED
failsafe_value CDATA #REQUIRED>

<!ATTLIST set
value CDATA #REQUIRED
command CDATA #IMPLIED
servo CDATA #IMPLIED>

<!ATTLIST call
fun CDATA #REQUIRED>

<!ATTLIST copy
command CDATA #REQUIRED>

<!ATTLIST let
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST ratelimit
var CDATA #REQUIRED
value CDATA #REQUIRED
rate_min CDATA #REQUIRED
rate_max CDATA #REQUIRED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED
unit CDATA #IMPLIED
code_unit CDATA #IMPLIED
integer CDATA #IMPLIED
type CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED
description CDATA #IMPLIED>

<!ATTLIST modules
main_freq CDATA #IMPLIED
target CDATA #IMPLIED>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED
dir CDATA #IMPLIED>

=== paparazzi/paparazzi/conf/airframes/obsolete/twinjet_overo.xml
<!DOCTYPE airframe SYSTEM "airframe.dtd">

<!-- Twinjet Multiplex (http://www.multiplex-rc.de/)
     Twog v1 board (http://wiki.paparazziuav.org/wiki/Twog_v1)
     PerkinElmer TPS334 IR Sensors
     Aligned infrared sensor
     XBee modem with AT firmware
     LEA 5H GPS
-->

<airframe name="Twinjet">

  <firmware name="fixedwing">
    <target name="ap"           board="twog_1.0">
      <define name="UBX_EXTERNAL"/>
    </target>

    <target name="sim"          board="pc"/>

    <define name="LOITER_TRIM"/>
    <define name="AGR_CLIMB"/>

    <subsystem name="radio_control" type="ppm"/>
    <subsystem name="telemetry"     type="transparent"/>
    <subsystem name="control"/>
    <subsystem name="gps"           type="ublox_hitl"/>
    <subsystem name="navigation"/>
    <subsystem name="ins"           type="gps_passthrough"/>
    <define name="USE_JOYSTICK" value="TRUE"/>
  </firmware>

  <firmware name="setup">
    <target name="tunnel"       board="twog_1.0" />
  </firmware>

  <modules>
    <load name="twog_extra_dl.xml"/>
    <load name="adc_generic.xml">
      <flag name="ADC_CHANNEL_GENERIC1" value="ADC_3"/>
      <flag name="ADC_CHANNEL_GENERIC2" value="ADC_5"/>
      <flag name="USE_ADC_3"/>
      <flag name="USE_ADC_5"/>
    </load>
    <load name="infrared_adc.xml"/>
    <load name="ahrs_infrared.xml"/>
  </modules>

  <servos>
    <servo name="THROTTLE"      no="0" min="1000" neutral="1000" max="2000"/>
    <servo name="AILEVON_RIGHT" no="1" min="1230" neutral="1710" max="2100"/>
    <servo name="AILEVON_LEFT"  no="2" min="2120" neutral="1785" max="1300"/>
    <servo name="CHAN3"  no="3" min="2120" neutral="1785" max="1300"/>
    <servo name="CHAN4"  no="4" min="2120" neutral="1785" max="1300"/>
    <servo name="CHAN5"  no="5" min="2120" neutral="1785" max="1300"/>
    <servo name="CHAN6"  no="6" min="2120" neutral="1785" max="1300"/>
    <servo name="CHAN7"  no="7" min="2120" neutral="1785" max="1300"/>
  </servos>

  <commands>
    <axis name="THROTTLE"  failsafe_value="0"/>
    <axis name="ROLL"      failsafe_value="0"/>
    <axis name="PITCH"     failsafe_value="0"/>
  </commands>

  <rc_commands>
    <set command="THROTTLE" value="@THROTTLE"/>
    <set command="ROLL"     value="@ROLL"/>
    <set command="PITCH"    value="@PITCH"/>
  </rc_commands>

  <section name="MIXER">
    <define name="AILEVON_AILERON_RATE" value="0.75"/>
    <define name="AILEVON_ELEVATOR_RATE" value="1.00"/>
  </section>

  <command_laws>
    <set servo="THROTTLE" value="@THROTTLE"/>
    <let var="aileron" value="@ROLL * AILEVON_AILERON_RATE"/>
    <let var="elevator" value="@PITCH * AILEVON_ELEVATOR_RATE"/>
    <set servo="AILEVON_LEFT" value="$aileron + $elevator"/>
    <set servo="AILEVON_RIGHT" value="-$aileron + $elevator"/>
  </command_laws>

  <section name="AUTO1" prefix="AUTO1_">
    <define name="MAX_ROLL" value="0.6"/>
    <define name="MAX_PITCH" value="0.6"/>
  </section>

  <section name="INFRARED" prefix="IR_">
    <define name="ADC_IR1_NEUTRAL" value="512"/>
    <define name="ADC_IR2_NEUTRAL" value="512"/>
    <define name="ADC_TOP_NEUTRAL" value="512"/>

    <define name="HORIZ_SENSOR_ALIGNED" value="1"/>
    <define name="IR1_SIGN" value="1"/>
    <define name="IR2_SIGN" value="-1"/>

    <define name="ROLL_NEUTRAL_DEFAULT" value="5" unit="deg"/>
    <define name="PITCH_NEUTRAL_DEFAULT" value="10" unit="deg"/>

    <define name="LATERAL_CORRECTION" value="1."/>
    <define name="LONGITUDINAL_CORRECTION" value="1."/>
    <define name="VERTICAL_CORRECTION" value="1.25"/>

    <define name="CORRECTION_UP" value="1."/>
    <define name="CORRECTION_DOWN" value="1."/>
    <define name="CORRECTION_LEFT" value="1."/>
    <define name="CORRECTION_RIGHT" value="1."/>
  </section>

  <section name="HORIZONTAL CONTROL" prefix="H_CTL_">
    <define name="COURSE_PGAIN" value="0.9"/>

    <define name="ROLL_MAX_SETPOINT" value="0.53" unit="rad"/>
    <define name="PITCH_MAX_SETPOINT" value="0.5" unit="rad"/>
    <define name="PITCH_MIN_SETPOINT" value="-0.5" unit="rad"/>

    <define name="PITCH_PGAIN" value="6000."/>
    <define name="PITCH_DGAIN" value="0."/>
    <define name="ELEVATOR_OF_ROLL" value="0"/>

    <!--  roll rate loop -->
    <define name="ROLL_ATTITUDE_GAIN" value="7500"/>
    <define name="ROLL_RATE_GAIN" value="1500"/>
  </section>


 <section name="VERTICAL CONTROL" prefix="V_CTL_">
    <!-- outer loop proportional gain -->
    <define name="ALTITUDE_PGAIN" value="0.05"/>
    <!-- outer loop saturation -->
    <define name="ALTITUDE_MAX_CLIMB" value="3."/>

    <!-- auto throttle inner loop -->
    <define name="AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE" value="0.40"/>
    <define name="AUTO_THROTTLE_MIN_CRUISE_THROTTLE" value=".3"/>
    <define name="AUTO_THROTTLE_MAX_CRUISE_THROTTLE" value="0.8"/>
    <define name="AUTO_THROTTLE_LOITER_TRIM" value="2000"/>
    <define name="AUTO_THROTTLE_DASH_TRIM" value="-1500"/>
    <define name="AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT" value="0.15" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_PGAIN" value="0.008"/>
    <define name="AUTO_THROTTLE_IGAIN" value="0.25"/>
    <define name="AUTO_THROTTLE_PITCH_OF_VZ_PGAIN" value="0.14"/>

    <define name="THROTTLE_SLEW_LIMITER" value="2" unit="s"/>
  </section>



  <section name="NAV">
    <define name="NAV_GLIDE_PITCH_TRIM" value="0"/>
    <define name="DEFAULT_CIRCLE_RADIUS" value="75."/>
  </section>

  <section name="BAT">
    <define name="MILLIAMP_AT_FULL_THROTTLE" value="1000"/>
    <define name="CATASTROPHIC_BAT_LEVEL" value="6.3" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="7.0" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="7.3" unit="V"/>
  </section>

  <section name="MISC">
    <define name="NOMINAL_AIRSPEED" value="12." unit="m/s"/>
    <define name="CARROT" value="5." unit="s"/>
    <define name="KILL_MODE_DISTANCE" value="(MAX_DIST_FROM_HOME*1.5)" unit="s"/>
  </section>

  <section name="FAILSAFE" prefix="FAILSAFE_">
    <define name="DELAY_WITHOUT_GPS" value="2" unit="s"/>
    <define name="DEFAULT_THROTTLE" value="V_CTL_AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE+0.05" unit="%"/>
    <define name="DEFAULT_ROLL" value="0.17" unit="rad"/>
    <define name="DEFAULT_PITCH" value="0.08" unit="rad"/>
    <define name="HOME_RADIUS" value="50" unit="m"/>
  </section>

  <section name="AGGRESSIVE" prefix="AGR_">
    <define name="CLIMB_THROTTLE" value="0.65"/><!-- Throttle for Aggressive Climb -->
    <define name="DESCENT_THROTTLE" value="0.1"/><!-- Throttle for Aggressive Decent -->
    <define name="CLIMB_PITCH" value="0.2"/><!-- Pitch for Aggressive Climb -->
    <define name="DESCENT_PITCH" value="-0.25"/><!-- Pitch for Aggressive Decent -->
    <define name="BLEND_START" value="20"/><!-- Altitude Error to Initiate Aggressive Climb CANNOT BE ZERO!!-->
    <define name="BLEND_END" value="10"/><!-- Altitude Error to Blend Aggressive to Regular Climb Modes  CANNOT BE ZERO!!-->
    <define name="CLIMB_NAV_RATIO" value="0.8"/><!-- Percent Navigation for Altitude Error Equal to Start Altitude -->
    <define name="DESCENT_NAV_RATIO" value="1.0"/>
  </section>

</airframe>

=== paparazzi/paparazzi/conf/airframes/flixr/fraser_lisa_m_rotorcraft.xml
<!DOCTYPE airframe SYSTEM "../airframe.dtd">

<!-- this is a quadrotor frame equiped with Lisa/M and MKK motor controllers -->

<airframe name="fraser">

  <firmware name="rotorcraft">
    <target name="ap" board="lisa_m_1.0">
      <define name="ACTUATORS_START_DELAY" value="3"/>
    </target>

    <target name="nps" board="pc">
      <subsystem name="fdm"           type="jsbsim"/>
    </target>

    <subsystem name="radio_control" type="spektrum">
      <define name="RADIO_MODE" value="RADIO_AUX1"/>
      <define name="RADIO_KILL_SWITCH" value="RADIO_GEAR"/>
      <configure name="USE_SECONDARY_SPEKTRUM_RECEIVER" value="1"/>
    </subsystem>
    <subsystem name="telemetry"     type="transparent"/>

    <subsystem name="motor_mixing"/>
    <subsystem name="actuators"     type="mkk"/>

    <subsystem name="stabilization" type="int_quat"/>

    <subsystem name="gps"           type="ublox"/>
    <subsystem name="imu"           type="aspirin_v1.5"/>
    <subsystem name="ahrs"          type="int_cmpl_quat">
      <define name="AHRS_GRAVITY_HEURISTIC_FACTOR" value="30"/>
    </subsystem>
    <subsystem name="ins_extended"/>

	<!--define name="KILL_ON_GROUND_DETECT" value="TRUE"/-->
  </firmware>

  <firmware name="setup">
    <target name="tunnel" board="lisa_m_1.0"/>
  </firmware>

  <firmware name="test_progs">
    <target name="test_sys_time_timer"      board="lisa_m_1.0"/>
	<target name="test_sys_time_usleep"     board="lisa_m_1.0"/>
    <target name="test_telemetry"           board="lisa_m_1.0"/>
    <target name="test_esc_mkk_simple"      board="lisa_m_1.0"/>
    <target name="test_uart"                board="lisa_m_1.0">
      <define name="USE_UART1"/>
      <define name="UART1_BAUD" value="B57600"/>
      <define name="USE_UART2"/>
      <define name="UART2_BAUD" value="B57600"/>
    </target>
    <target name="test_baro_board"          board="lisa_m_1.0"/>
    <target name="test_adc"                 board="lisa_m_1.0"/>
    <target name="test_imu"                 board="lisa_m_1.0">
      <subsystem name="imu"           type="aspirin_v1.5"/>
    </target>
  </firmware>

  <modules main_freq="512">
    <load name="sys_mon.xml"/>
    <load name="gps_ubx_ucenter.xml"/>
  </modules>

  <commands>
    <axis name="PITCH"  failsafe_value="0"/>
    <axis name="ROLL"   failsafe_value="0"/>
    <axis name="YAW"    failsafe_value="0"/>
    <axis name="THRUST" failsafe_value="0"/>
  </commands>

  <section name="ACTUATORS_MKK" prefix="ACTUATORS_MKK_">
    <define name="NB" value="4"/>
    <!-- FRONT, BACK, RIGHT, LEFT -->
    <define name="ADDR" value="{ 0x54, 0x52, 0x56, 0x58 }"/>
  </section>

  <servos driver="Mkk">
    <servo name="FRONT"  no="0"    min="0" neutral="2" max="200"/>
    <servo name="BACK"   no="1"    min="0" neutral="2" max="200"/>
    <servo name="RIGHT"  no="2"    min="0" neutral="2" max="200"/>
    <servo name="LEFT"   no="3"    min="0" neutral="2" max="200"/>
  </servos>

  <section name="MIXING" prefix="MOTOR_MIXING_">
    <define name="TRIM_ROLL" value="0"/>
    <define name="TRIM_PITCH" value="0"/>
    <define name="TRIM_YAW" value="0"/>
    <define name="MAX_SATURATION_OFFSET" value="2000"/>
    <define name="NB_MOTOR" value="4"/>
    <define name="SCALE" value="256"/>
    <!-- front/back turning CCW, left/right CW -->
    <define name="ROLL_COEF"   value="{    0,    0, -256,  256 }"/>
    <define name="PITCH_COEF"  value="{  256, -256,    0,    0 }"/>
    <define name="YAW_COEF"    value="{  256,  256, -256, -256 }"/>
    <define name="THRUST_COEF" value="{  256,  256,  256,  256 }"/>
  </section>

  <command_laws>
    <call fun="motor_mixing_run(autopilot_motors_on,FALSE,values)"/>
    <set servo="FRONT" value="motor_mixing.commands[0]"/>
    <set servo="BACK"  value="motor_mixing.commands[1]"/>
    <set servo="RIGHT" value="motor_mixing.commands[2]"/>
    <set servo="LEFT"  value="motor_mixing.commands[3]"/>
  </command_laws>

  <section name="IMU" prefix="IMU_">
    <define name="ACCEL_X_NEUTRAL" value="11"/>
    <define name="ACCEL_Y_NEUTRAL" value="11"/>
    <define name="ACCEL_Z_NEUTRAL" value="-25"/>

	<define name="MAG_X_NEUTRAL" value="22"/>
	<define name="MAG_Y_NEUTRAL" value="-314"/>
	<define name="MAG_Z_NEUTRAL" value="13"/>
	<define name="MAG_X_SENS" value="3.68160078446" integer="16"/>
	<define name="MAG_Y_SENS" value="3.6093630842" integer="16"/>
	<define name="MAG_Z_SENS" value="3.48306842466" integer="16"/>

    <define name="BODY_TO_IMU_PHI"   value="0." unit="deg"/>
    <define name="BODY_TO_IMU_THETA" value="0." unit="deg"/>
    <define name="BODY_TO_IMU_PSI"   value="-45." unit="deg"/>
  </section>

  <section name="AHRS" prefix="AHRS_">
    <define name="H_X" value="0.3770441"/>
    <define name="H_Y" value="0.0193986"/>
    <define name="H_Z" value="0.9259921"/>
  </section>

  <section name="INS" prefix="INS_">
  </section>

  <section name="STABILIZATION_RATE" prefix="STABILIZATION_RATE_">
    <!-- setpoints -->
    <define name="SP_MAX_P" value="10000"/>
    <define name="SP_MAX_Q" value="10000"/>
    <define name="SP_MAX_R" value="10000"/>
    <define name="DEADBAND_P" value="20"/>
    <define name="DEADBAND_Q" value="20"/>
    <define name="DEADBAND_R" value="200"/>
    <define name="REF_TAU" value="4"/>

    <!-- feedback -->
    <define name="GAIN_P" value="400"/>
    <define name="GAIN_Q" value="400"/>
    <define name="GAIN_R" value="350"/>

    <define name="IGAIN_P" value="75"/>
    <define name="IGAIN_Q" value="75"/>
    <define name="IGAIN_R" value="50"/>

    <!-- feedforward -->
    <define name="DDGAIN_P" value="300"/>
    <define name="DDGAIN_Q" value="300"/>
    <define name="DDGAIN_R" value="300"/>
  </section>


  <section name="STABILIZATION_ATTITUDE" prefix="STABILIZATION_ATTITUDE_">
    <!-- setpoints -->
    <define name="SP_MAX_PHI"     value="60." unit="deg"/>
    <define name="SP_MAX_THETA"   value="60." unit="deg"/>
    <define name="SP_MAX_R"       value="90." unit="deg/s"/>
    <define name="DEADBAND_A"     value="0"/>
    <define name="DEADBAND_E"     value="0"/>
    <define name="DEADBAND_R"     value="250"/>

    <!-- reference -->
    <define name="REF_OMEGA_P"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_P"   value="0.85"/>
    <define name="REF_MAX_P"    value="400." unit="deg/s"/>
    <define name="REF_MAX_PDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_Q"  value="400" unit="deg/s"/>
    <define name="REF_ZETA_Q"   value="0.85"/>
    <define name="REF_MAX_Q"    value="400." unit="deg/s"/>
    <define name="REF_MAX_QDOT" value="RadOfDeg(8000.)"/>

    <define name="REF_OMEGA_R"  value="250" unit="deg/s"/>
    <define name="REF_ZETA_R"   value="0.85"/>
    <define name="REF_MAX_R"    value="180." unit="deg/s"/>
    <define name="REF_MAX_RDOT" value="RadOfDeg(1800.)"/>

    <!-- feedback -->
    <define name="PHI_PGAIN"  value="1000"/>
    <define name="PHI_DGAIN"  value="400"/>
    <define name="PHI_IGAIN"  value="200"/>

    <define name="THETA_PGAIN"  value="1000"/>
    <define name="THETA_DGAIN"  value="400"/>
    <define name="THETA_IGAIN"  value="200"/>

    <define name="PSI_PGAIN"  value="500"/>
    <define name="PSI_DGAIN"  value="300"/>
    <define name="PSI_IGAIN"  value="10"/>

    <!-- feedforward -->
    <define name="PHI_DDGAIN"   value="300"/>
    <define name="THETA_DDGAIN" value="300"/>
    <define name="PSI_DDGAIN"   value="300"/>
  </section>

  <section name="GUIDANCE_V" prefix="GUIDANCE_V_">
    <define name="HOVER_KP"    value="120"/>
    <define name="HOVER_KD"    value="100"/>
    <define name="HOVER_KI"    value="20"/>
    <define name="NOMINAL_HOVER_THROTTLE" value="0.38"/>
    <define name="ADAPT_THROTTLE_ENABLED" value="TRUE"/>
  </section>

  <section name="GUIDANCE_H" prefix="GUIDANCE_H_">
    <define name="APPROX_FORCE_BY_THRUST" value="TRUE"/>
    <define name="USE_REF" value="TRUE"/>
    <define name="MAX_BANK" value="30" unit="deg"/>
    <define name="PGAIN" value="100"/>
    <define name="DGAIN" value="100"/>
    <define name="IGAIN" value="0"/>
  </section>

  <section name="SIMULATOR" prefix="NPS_">
    <define name="ACTUATOR_NAMES"  value="{&quot;front_motor&quot;, &quot;back_motor&quot;, &quot;right_motor&quot;, &quot;left_motor&quot;}"/>
    <define name="JSBSIM_MODEL" value="&quot;simple_quad_ccw&quot;"/>
    <define name="SENSORS_PARAMS" value="&quot;nps_sensors_params_default.h&quot;"/>
    <!-- mode switch on joystick channel 5 (axis numbering starting at zero) -->
    <define name="JS_AXIS_MODE" value="4"/>
  </section>

  <section name="AUTOPILOT">
    <define name="MODE_MANUAL" value="AP_MODE_ATTITUDE_DIRECT"/>
    <define name="MODE_AUTO1"  value="AP_MODE_ATTITUDE_Z_HOLD"/>
    <define name="MODE_AUTO2"  value="AP_MODE_NAV"/>
  </section>

  <section name="BAT">
    <define name="CATASTROPHIC_BAT_LEVEL" value="9.3" unit="V"/>
    <define name="CRITIC_BAT_LEVEL" value="9.6" unit="V"/>
    <define name="LOW_BAT_LEVEL" value="9.7" unit="V"/>
    <define name="MAX_BAT_LEVEL" value="12.4" unit="V"/>
  </section>

</airframe>

=== paparazzi/paparazzi/conf/airframes/obsolete/microjet_raw_makefile.xml
<!DOCTYPE airframe SYSTEM "./airframe.dtd">

<!--
     Microjet Multiplex (http://www.multiplex-rc.de/)
     Tiny 2.11 board (http://paparazzi.enac.fr/wiki/Tiny_v2)
     Tilted infrared sensor
     Transparent modem

     This airframe demonstrate the old raw makefile syntax
     Look at conf/airframes/microjet_example.xml for equivalent new syntax
-->

<airframe name="microjet raw makefile">

  <servos>
    <servo name="MOTOR"         no="0" min="1000" neutral="1000" max="2000"/>
    <servo name="AILEVON_LEFT"  no="2" min="1130" neutral="1575" max="1880"/>
    <servo name="AILEVON_RIGHT" no="6" min="1980" neutral="1465" max="1170"/>
  </servos>

  <commands>
    <axis name="THROTTLE" failsafe_value="0"/>
    <axis name="ROLL"     failsafe_value="0"/>
    <axis name="PITCH"    failsafe_value="0"/>
    <axis name="HATCH"    failsafe_value="0"/>
  </commands>

  <rc_commands>
    <set command="THROTTLE" value="@THROTTLE"/>
    <set command="ROLL"     value="@ROLL"/>
    <set command="PITCH"    value="@PITCH"/>
  </rc_commands>

  <section name="MIXER">
    <define name="AILEVON_AILERON_RATE" value="0.75"/>
    <define name="AILEVON_ELEVATOR_RATE" value="0.75"/>
  </section>

  <command_laws>
    <let var="aileron"  value="@ROLL  * AILEVON_AILERON_RATE"/>
    <let var="elevator" value="@PITCH * AILEVON_ELEVATOR_RATE"/>
    <set servo="MOTOR"           value="@THROTTLE"/>
    <set servo="AILEVON_LEFT"  value="$elevator + $aileron"/>
    <set servo="AILEVON_RIGHT" value="$elevator - $aileron"/>
  </command_laws>

  <section name="AUTO1" prefix="AUTO1_">
    <define name="MAX_ROLL" value="0.85"/>
    <define name="MAX_PITCH" value="0.6"/>
  </section>

  <section name="adc" prefix="ADC_CHANNEL_">
    <define name="IR1" value="ADC_1"/>
    <define name="IR2" value="ADC_2"/>
    <define name="IR_TOP" value="ADC_0"/>
    <define name="IR_NB_SAMPLES" value="16"/>

    <define name="GYRO_ROLL" value="ADC_3"/>
    <define name="GYRO_NB_SAMPLES" value="16"/>

  </section>

  <section name="INFRARED" prefix="IR_">
    <define name="ADC_IR1_NEUTRAL" value="512"/>
    <define name="ADC_IR2_NEUTRAL" value="512"/>
    <define name="ADC_TOP_NEUTRAL" value="512"/>

    <define name="LATERAL_CORRECTION" value="1."/>
    <define name="LONGITUDINAL_CORRECTION" value="1."/>
    <define name="VERTICAL_CORRECTION" value="1.5"/>

    <define name="HORIZ_SENSOR_TILTED" value="1"/>
    <define name="IR2_SIGN" value="-1"/>
    <define name="TOP_SIGN" value="-1"/>

    <define name="ROLL_NEUTRAL_DEFAULT" value="-3.6" unit="deg"/>
    <define name="PITCH_NEUTRAL_DEFAULT" value="5" unit="deg"/>

    <define name="CORRECTION_UP" value="1."/>
    <define name="CORRECTION_DOWN" value="1."/>
    <define name="CORRECTION_LEFT" value="1."/>
    <define name="CORRECTION_RIGHT" value="1."/>
  </section>

 <section name="GYRO" prefix="GYRO_">
    <define name="ADC_ROLL_NEUTRAL" value="520"/>
    <define name="ADC_TEMP_NEUTRAL" value="476"/>
    <define name="ADC_TEMP_SLOPE" value="0"/>
    <define name="DYNAMIC_RANGE" value="300" unit="deg/s"/>
    <define name="ADXRS300_RESISTOR_BRIDGE" value="(3.3/(3.3+1.8))"/>
    <define name="ADXRS300_SENSITIVITY" value="5" unit="mV/(deg/s)"/>
    <define name="ROLL_SCALE" value="3.3*1000./1024./(GYRO_ADXRS300_SENSITIVITY*GYRO_ADXRS300_RESISTOR_BRIDGE)" unit="deg/s/adc_unit"/>
    <define name="ROLL_DIRECTION" value="-1."/>
  </section>

  <section name="BAT">
    <define name="MILLIAMP_AT_FULL_THROTTLE" value="4000"/>

    <define name="CATASTROPHIC_BAT_LEVEL" value="9.3" unit="V"/>
  </section>

  <section name="MISC">
    <define name="MINIMUM_AIRSPEED" value="12." unit="m/s"/>
    <define name="NOMINAL_AIRSPEED" value="15." unit="m/s"/>
    <define name="MAXIMUM_AIRSPEED" value="25." unit="m/s"/>
    <define name="CARROT" value="5." unit="s"/>
    <define name="KILL_MODE_DISTANCE" value="(1.5*MAX_DIST_FROM_HOME)"/>
    <define name="CONTROL_RATE" value="60" unit="Hz"/>
    <define name="ALT_KALMAN_ENABLED" value="TRUE"/>

    <define name="DEFAULT_CIRCLE_RADIUS" value="80."/>
  </section>

  <section name="VERTICAL CONTROL" prefix="V_CTL_">

    <!-- outer loop proportional gain -->
    <define name="ALTITUDE_PGAIN" value="0.04"/>
    <!-- outer loop saturation -->
    <define name="ALTITUDE_MAX_CLIMB" value="2."/>

    <!-- auto throttle inner loop -->
    <define name="AUTO_THROTTLE_NOMINAL_CRUISE_THROTTLE" value="0.35"/>
    <define name="AUTO_THROTTLE_MIN_CRUISE_THROTTLE" value="0.25"/>
    <define name="AUTO_THROTTLE_MAX_CRUISE_THROTTLE" value="0.80"/>
    <define name="AUTO_THROTTLE_LOITER_TRIM" value="1500"/>
    <define name="AUTO_THROTTLE_DASH_TRIM" value="-1000"/>
    <define name="AUTO_THROTTLE_CLIMB_THROTTLE_INCREMENT" value="0.1" unit="%/(m/s)"/>
    <define name="AUTO_THROTTLE_PGAIN" value="0.02"/>
    <define name="AUTO_THROTTLE_IGAIN" value="0.1"/>
    <define name="AUTO_THROTTLE_PITCH_OF_VZ_PGAIN" value="0.1"/>

    <!-- auto pitch inner loop -->
    <define name="AUTO_PITCH_PGAIN" value="0.05"/>
    <define name="AUTO_PITCH_IGAIN" value="0.075"/>
    <define name="AUTO_PITCH_MAX_PITCH" value="0.35"/>
    <define name="AUTO_PITCH_MIN_PITCH" value="-0.35"/>

   <define name="THROTTLE_SLEW" value="0.5"/>

  </section>

  <section name="HORIZONTAL CONTROL" prefix="H_CTL_">
    <define name="COURSE_PGAIN" value="0.8"/>

    <define name="ROLL_MAX_SETPOINT" value="0.7" unit="rad"/>
    <define name="PITCH_MAX_SETPOINT" value="0.5" unit="rad"/>
    <define name="PITCH_MIN_SETPOINT" value="-0.5" unit="rad"/>

    <define name="PITCH_PGAIN" value="10000."/>
    <define name="PITCH_DGAIN" value="1.5"/>

    <define name="ELEVATOR_OF_ROLL" value="2500"/>

    <define name="ROLL_ATTITUDE_GAIN" value="7500"/>
    <define name="ROLL_RATE_GAIN" value="1500"/>
  </section>

  <section name="AGGRESSIVE" prefix="AGR_">
    <define name="BLEND_START" value="20"/><!-- Altitude Error to Initiate Aggressive Climb CANNOT BE ZERO!!-->
    <define name="BLEND_END" value="10"/><!-- Altitude Error to Blend Aggressive to Regular Climb Modes  CANNOT BE ZERO!!-->
    <define name="CLIMB_THROTTLE" value="0.6"/><!-- Gaz for Aggressive Climb -->
    <define name="CLIMB_PITCH" value="0.20"/><!-- Pitch for Aggressive Climb -->
    <define name="DESCENT_THROTTLE" value="0.1"/><!-- Gaz for Aggressive Decent -->
    <define name="DESCENT_PITCH" value="-0.15"/><!-- Pitch for Aggressive Decent -->
    <define name="CLIMB_NAV_RATIO" value="0.8"/><!-- Percent Navigation for Altitude Error Equal to Start Altitude -->
    <define name="DESCENT_NAV_RATIO" value="1.0"/>
    </section>

  <section name="FAILSAFE" prefix="FAILSAFE_">
    <define name="DELAY_WITHOUT_GPS" value="1" unit="s"/>
        <define name="DEFAULT_THROTTLE" value="0.3" unit="%"/>
        <define name="DEFAULT_ROLL" value="0.3" unit="rad"/>
        <define name="DEFAULT_PITCH" value="0.5" unit="rad"/>
    <define name="HOME_RADIUS" value="100" unit="m"/>
  </section>


 <makefile>

<makefile>
 CONFIG=\"tiny_2_11.h\"
 include $(PAPARAZZI_SRC)/conf/autopilot/tiny.makefile
 FLASH_MODE=IAP
 ap.CFLAGS +=  -DFBW -DAP -DBOARD_CONFIG=$(CONFIG) -DUSE_LED -DTIME_LED=1
 ap.srcs = sys_time.c $(SRC_ARCH)/sys_time_hw.c $(SRC_ARCH)/armVIC.c main_fbw.c main_ap.c main.c
 ap.srcs += commands.c
 ap.CFLAGS += -DACTUATORS=\"servos_4015_MAT_hw.h\" -DSERVOS_4015_MAT
 ap.srcs += $(SRC_ARCH)/servos_4015_MAT_hw.c actuators.c
 ap.CFLAGS += -DRADIO_CONTROL
 ap.srcs += radio_control.c $(SRC_ARCH)/ppm_hw.c
 ap.CFLAGS += -DDOWNLINK -DUSE_UART0 -DDOWNLINK_TRANSPORT=PprzTransport -DDOWNLINK_FBW_DEVICE=Uart0 -DDOWNLINK_AP_DEVICE=Uart0 -DPPRZ_UART=Uart0 -DDATALINK=PPRZ -DUART0_BAUD=B9600
 ap.srcs += subsystems/datalink/downlink.c $(SRC_ARCH)/mcu_periph/uart_arch.c datalink.c subsystems/datalink/pprz_transport.c
 ap.CFLAGS += -DINTER_MCU
 ap.srcs += inter_mcu.c
 ap.CFLAGS += -DADC -DUSE_ADC_0 -DUSE_ADC_1 -DUSE_ADC_2 -DUSE_ADC_3
 ap.srcs += $(SRC_ARCH)/adc_hw.c
 ap.CFLAGS += -DUSE_GPS -DUBX -DUSE_UART1 -DGPS_LINK=Uart1 -DUART1_BAUD=B38400
 ap.CFLAGS += -DGPS_CONFIGURE -DGPS_BAUD=38400
 ap.srcs += gps_ubx.c gps.c latlong.c
 ap.CFLAGS += -DUSE_INFRARED
 ap.srcs += infrared.c estimator.c
 ap.CFLAGS += -DNAV -DAGR_CLIMB -DLOITER_TRIM -DALT_KALMAN -DWIND_INFO
 ap.srcs += subsystems/nav.c fw_h_ctl.c fw_v_ctl.c
 ap.srcs += subsystems/navigation/nav_line.c subsystems/navigation/nav_survey_rectangle.c

 ap.CFLAGS += -DTRAFFIC_INFO -DALT_KALMAN
 sim.CFLAGS += -DTRAFFIC_INFO


 include $(PAPARAZZI_SRC)/conf/autopilot/sitl.makefile
 sim.CFLAGS += -DBOARD_CONFIG=\"tiny.h\"

  </makefile>
</airframe>

=== paparazzi/paparazzi/conf/airframes/tudelft/calibrations/bebop7.xml
<!DOCTYPE airframe SYSTEM "../../airframe.dtd">

<airframe>
  <section name="IMU" prefix="IMU_">
    <!-- Magneto calibration -->
<define name="MAG_X_NEUTRAL" value="-54"/>
<define name="MAG_Y_NEUTRAL" value="-1"/>
<define name="MAG_Z_NEUTRAL" value="134"/>
<define name="MAG_X_SENS" value="7.55622140532" integer="16"/>
<define name="MAG_Y_SENS" value="7.72221931874" integer="16"/>
<define name="MAG_Z_SENS" value="7.84828034818" integer="16"/>



    <!-- Magneto current calibration -->
    <define name="MAG_X_CURRENT_COEF" value="0.0"/>
    <define name="MAG_Y_CURRENT_COEF" value="0.0"/>
    <define name="MAG_Z_CURRENT_COEF" value="0.0"/>
  </section>
</airframe>
