=== paparazzi/paparazzi/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (header?,waypoints,sectors?,variables?,modules?,includes?,exceptions?,blocks)>

<!ELEMENT procedure (param*,header?,waypoints?,sectors?,exceptions?,blocks?)>

<!ELEMENT header (#PCDATA)>

<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT sectors (sector|kml)*>
<!ELEMENT sector (corner,corner,corner+)>
<!ELEMENT corner EMPTY>
<!ELEMENT kml EMPTY>

<!ELEMENT variables (variable*)>
<!ELEMENT variable EMPTY>

<!ELEMENT modules (module*)>
<!ELEMENT module  (configure|define)*>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>

<!ELEMENT includes (include*)>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|manual|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|home|path)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (exception|while|heading|attitude|manual|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path)*>
<!ELEMENT for (exception|while|heading|attitude|manual|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT manual EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT call_once EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT home EMPTY>
<!ELEMENT eight EMPTY>
<!ELEMENT oval EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>
<!ELEMENT param EMPTY>
<!ELEMENT return EMPTY>
<!ELEMENT path EMPTY>


<!ATTLIST flight_plan
name CDATA #REQUIRED
lat0 CDATA #REQUIRED
lon0 CDATA #REQUIRED
max_dist_from_home CDATA #REQUIRED
ground_alt CDATA #REQUIRED
security_height CDATA #REQUIRED
alt CDATA #REQUIRED
qfu CDATA #IMPLIED
home_mode_height CDATA #IMPLIED
geofence_max_alt CDATA #IMPLIED
geofence_sector CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST exceptions>

<!ATTLIST sectors>

<!ATTLIST sector
name CDATA #REQUIRED
color CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST corner
name CDATA #REQUIRED>

<!ATTLIST kml
file CDATA #REQUIRED>

<!ATTLIST variables>

<!ATTLIST variable
var CDATA #REQUIRED
type CDATA #IMPLIED
init CDATA #IMPLIED
shortname CDATA #IMPLIED
min CDATA #IMPLIED
max CDATA #IMPLIED
step CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED>

<!ATTLIST modules>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST blocks>

<!ATTLIST block
name CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
strip_button CDATA #IMPLIED
strip_icon CDATA #IMPLIED
group CDATA #IMPLIED
key CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST for
var CDATA #REQUIRED
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST heading
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST manual
pitch CDATA #REQUIRED
roll CDATA #REQUIRED
yaw CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST go
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST path
wpts CDATA #REQUIRED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED
until CDATA #IMPLIED
loop CDATA #IMPLIED
break CDATA #IMPLIED>

<!ATTLIST call_once
fun CDATA #REQUIRED
break CDATA #IMPLIED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED>

<!ATTLIST xyz
radius CDATA #IMPLIED>

<!ATTLIST home>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
height CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST eight
center CDATA #REQUIRED
turn_around CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
until CDATA #IMPLIED
radius CDATA #REQUIRED>


<!ATTLIST oval
p1 CDATA #REQUIRED
p2 CDATA #REQUIRED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
orientation CDATA #IMPLIED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED
until CDATA #IMPLIED>

<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
alt CDATA #IMPLIED
until CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST includes>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST param
name CDATA #REQUIRED
default_value CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST return>

=== paparazzi/paparazzi/conf/flight_plans/Tudelft/rotorcraft_survey_competition.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="30" ground_alt="0" lat0="50.788595" lon0="6.04692" max_dist_from_home="500" name="IMAV2015_competition_outdoor" security_height="2">
  <waypoints>
    <waypoint name="HOME" x="0.0" y=".0"/>
    <waypoint name="CLIMB" x="-7.6" y="15.4"/>
    <waypoint name="STDBY" x="-3.7" y="24.0"/>
    <waypoint lat="50.790483" lon="6.047899" name="raceA"/>
    <waypoint lat="50.791800" lon="6.050200" name="raceB"/>
    <waypoint lat="50.789794" lon="6.047431" name="WG"/>
    <waypoint lat="50.788923" lon="6.046754" name="WD"/>
    <waypoint lat="50.788761" lon="6.046508" name="RZ1"/>
    <waypoint lat="50.788912" lon="6.046406" name="RZ2"/>
    <waypoint lat="50.788972" lon="6.046423" name="RZ3"/>
    <waypoint lat="50.789522" lon="6.047118" name="FC"/>
    <waypoint lat="50.788597" lon="6.046721" name="S1"/>
    <waypoint lat="50.788973" lon="6.045944" name="S2"/>
    <waypoint lat="50.789323" lon="6.046330" name="S3"/>
    <waypoint lat="50.788917" lon="6.047113" name="S4"/>
    <waypoint lat="50.790483" lon="6.047864" name="p1"/>
    <waypoint lat="50.790463" lon="6.047897" name="p2"/>
    <waypoint lat="50.791799" lon="6.050232" name="p3"/>
    <waypoint lat="50.791818" lon="6.050201" name="p4"/>
    <waypoint name="CAM" x="27.5" y="95.0"/>
    <waypoint name="CRUISE" x="19.2" y="-55.4" height="25"/>
    <waypoint lat="50.788731" lon="6.046967" name="TD"/>
    <waypoint lat="50.790144" lon="6.046879" name="_green1A"/>
    <waypoint lat="50.789748" lon="6.047844" name="_green1B"/>
    <waypoint lat="50.789058" lon="6.047072" name="_green1C"/>
    <waypoint lat="50.788919" lon="6.047391" name="_green1D"/>
    <waypoint lat="50.788477" lon="6.046880" name="_green1E"/>
    <waypoint lat="50.789113" lon="6.045554" name="_green1F"/>
    <waypoint lat="50.792252" lon="6.050405" name="_green2A"/>
    <waypoint lat="50.791915" lon="6.050962" name="_green2B"/>
    <waypoint lat="50.790077" lon="6.047761" name="_green2C"/>
    <waypoint lat="50.790426" lon="6.047251" name="_green2D"/>
    <waypoint lat="50.792552" lon="6.050093" name="_red1"/>
    <waypoint lat="50.791882" lon="6.051268" name="_red2"/>
    <waypoint lat="50.789988" lon="6.047834" name="_red3"/>
    <waypoint lat="50.789781" lon="6.048204" name="_red4"/>
    <waypoint lat="50.788865" lon="6.047626" name="_red5"/>
    <waypoint lat="50.788209" lon="6.046744" name="_red6"/>
    <waypoint lat="50.789046" lon="6.045032" name="_red7"/>
    <waypoint lat="50.790416" lon="6.046338" name="_red8"/>
  </waypoints>
  <sectors>
    <sector color="red" name="RED">
      <corner name="_red1"/>
      <corner name="_red2"/>
      <corner name="_red3"/>
      <corner name="_red4"/>
      <corner name="_red5"/>
      <corner name="_red6"/>
      <corner name="_red7"/>
      <corner name="_red8"/>
    </sector>
    <sector color="green" name="GREEN1">
      <corner name="_green1A"/>
      <corner name="_green1B"/>
      <corner name="_green1C"/>
      <corner name="_green1D"/>
      <corner name="_green1E"/>
      <corner name="_green1F"/>
    </sector>
    <sector color="green" name="GREEN2">
      <corner name="_green2A"/>
      <corner name="_green2B"/>
      <corner name="_green2C"/>
      <corner name="_green2D"/>
    </sector>
  </sectors>
  <includes>
    <include name="Mission" procedure="rotorcraft_survey_mission.xml"/>
  </includes>
  <blocks>
    <block name="Dummy"/>
  </blocks>
</flight_plan>

=== paparazzi/paparazzi/conf/flight_plans/DB/db_cyberzoo.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="1.5" ground_alt="0" lat0="51.990634" lon0="4.376789" max_dist_from_home="8" name="Bebop2 Testing CyberZoo" security_height="0.4">
  <header>
#include "autopilot.h"
#include "subsystems/ahrs.h"
#include "subsystems/electrical.h"
#include "subsystems/datalink/datalink.h"
</header>
  <waypoints>
    <waypoint height="0" name="HOME" x="0.0" y="0.0"/>
    <waypoint height="2.2" name="CLIMB" x="1.2" y="-0.6"/>
    <waypoint height="1.0" name="STDBY" x="-0.7" y="-0.8"/>
    <waypoint name="TD" x="0.8" y="-1.7"/>
    <waypoint lat="51.9906213" lon="4.3768628" name="_CZ1"/>
    <waypoint lat="51.9905874" lon="4.3767766" name="_CZ2"/>
    <waypoint lat="51.9906409" lon="4.3767226" name="_CZ3"/>
    <waypoint lat="51.990667" lon="4.376806" name="_CZ4"/>
    <waypoint lat="51.990624" lon="4.376845" name="_OZ1"/>
    <waypoint lat="51.990601" lon="4.376782" name="_OZ2"/>
    <waypoint lat="51.990638" lon="4.376748" name="_OZ3"/>
    <waypoint lat="51.990657" lon="4.376804" name="_OZ4"/>
  </waypoints>
  <sectors>
    <sector color="red" name="CyberZoo">
      <corner name="_CZ1"/>
      <corner name="_CZ2"/>
      <corner name="_CZ3"/>
      <corner name="_CZ4"/>
    </sector>
    <sector color="#FF9922" name="ObstacleZone">
      <corner name="_OZ1"/>
      <corner name="_OZ2"/>
      <corner name="_OZ3"/>
      <corner name="_OZ4"/>
    </sector>
  </sectors>
  <exceptions>
    <exception cond="!InsideCyberZoo(GetPosX(), GetPosY())" deroute="Standby"/>
    <!--<exception cond="datalink_time > 22" deroute="Land here"/>-->
   <!-- <exception cond="electrical.bat_low && !(nav_block == IndexOfBlock('Land')) && !(nav_block == IndexOfBlock('Flare')) && !(nav_block == IndexOfBlock('Landed'))" deroute="Land"/>
    <exception cond="electrical.bat_critical && !(nav_block == IndexOfBlock('Land')) && !(nav_block == IndexOfBlock('Flare')) && !(nav_block == IndexOfBlock('Landed'))" deroute="Land here"/>-->
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 2)"/>
      <call fun="NavSetGroundReferenceHere()"/>   <!-- This sets the altitude ref -->
      <!-- <call fun="NavSetAltitudeReferenceHere()"/> -->
    </block>
    <block name="Holding point">
      <call fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block key="r" name="Start Engine">
      <call fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block key="t" name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="stateGetPositionEnu_f()->z > 0.9" deroute="Standby"/>
      <call fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay climb="nav_climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    <block key="s" name="Standby" strip_button="Standby" strip_icon="home.png">
     <!-- <call fun="NavSetWaypointHere(WP_STDBY)"/>-->
      <stay wp="STDBY"/>
    </block>
    <block key="l" name="Land here" strip_button="Land Here" strip_icon="land-right.png">
      <call fun="NavSetWaypointHere(WP_TD)"/>
    </block>
    <block name="Land">
      <go wp="TD"/>
    </block>
    <block name="Flare">
      <exception cond="NavDetectGround()" deroute="Holding point"/>
      <exception cond="!nav_is_in_flight()" deroute="Landed"/>
      <call fun="NavStartDetectGround()"/>
      <stay climb="nav_descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="Landed">
      <call fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== paparazzi/paparazzi/conf/flight_plans/tudelft/imav2025.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="2150" ground_alt="2080" lat0="18.9426688" lon0="-98.1893464" max_dist_from_home="1500" name="Basic" security_height="2130">
  <header>
#include "modules/datalink/datalink.h"

// Extras for Photoscan
#ifdef DC_AUTOSHOOT_PERIOD
//TODO make shooting distance not periodic
#define LINE_START_FUNCTION dc_autoshoot = DC_AUTOSHOOT_PERIODIC;
#define LINE_STOP_FUNCTION dc_autoshoot = DC_AUTOSHOOT_STOP;
#endif

</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="STDBY" x="49.5" y="100.1"/>
    <waypoint name="1" x="-27.0" y="129.3"/>
    <waypoint name="2" x="-23.9" y="301.8"/>
    <waypoint name="MOB" x="137.0" y="-11.6"/>
    <waypoint name="S1" x="-119.2" y="69.6"/>
    <waypoint name="S2" x="274.4" y="209.5"/>
    <waypoint alt="2130.0" name="AF" x="-9.4" y="40.3"/>
    <waypoint alt="2080.0" name="TD" x="-6.8" y="208.3"/>
    <waypoint name="_BASELEG" x="168.8" y="-13.8"/>
    <waypoint name="CLIMB" x="-3.3" y="129.1"/>
  </waypoints>
  <exceptions/>
  <blocks>
    <block name="Wait GPS">
      <set value="1" var="autopilot.kill_throttle"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetGroundReferenceHere()"/>
    </block>
    <block name="Holding point">
      <set value="1" var="autopilot.kill_throttle"/>
      <attitude roll="0" throttle="0" vmode="throttle"/>
    </block>
    <block group="home" key="t" name="Takeoff" strip_button="Takeoff (wp CLIMB)" strip_icon="takeoff.png">
      <exception cond="GetPosAlt() @GT GetAltRef()+25" deroute="Standby"/>
      <set value="0" var="autopilot.kill_throttle"/>
      <set value="0" var="autopilot.flight_time"/>
      <go from="HOME" pitch="15" throttle="1.0" vmode="throttle" wp="CLIMB"/>
    </block>
    <block group="home" key="Ctrl+a" name="Standby" strip_button="Standby" strip_icon="home.png">
      <circle radius="nav_radius" wp="STDBY"/>
    </block>
    <block group="base_pattern" key="F8" name="Figure 8 around wp 1" strip_button="Figure 8 (wp 1-2)" strip_icon="eight.png">
      <eight center="1" radius="nav_radius" turn_around="2"/>
    </block>
    <block group="base_pattern" name="Oval 1-2" strip_button="Oval (wp 1-2)" strip_icon="oval.png">
      <oval p1="1" p2="2" radius="nav_radius"/>
    </block>
    <block group="base_pattern" name="MOB" strip_button="Circle around here" strip_icon="mob.png">
      <call_once fun="NavSetWaypointHere(WP_MOB)"/>
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <circle radius="nav_radius" wp="MOB"/>
    </block>
    <block group="extra_pattern" name="Survey S1-S2" strip_button="Survey (wp S1-S2)" strip_icon="survey.png">
      <survey_rectangle grid="80" wp1="S1" wp2="S2"/>
    </block>
    <block group="extra_pattern" name="Path 1,2,S1,S2,STDBY" strip_button="Path (1,2,S1,S2,STDBY)" strip_icon="path.png">
      <path wpts="1,2 S1"/>
      <path approaching_time="1" pitch="auto" throttle="0.4" wpts="S1, S2 STDBY"/>
      <deroute block="Standby"/>
    </block>
    <block group="land" name="Land Right AF-TD" strip_button="Land right (wp AF-TD)" strip_icon="land-right.png">
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block group="land" name="Land Left AF-TD" strip_button="Land left (wp AF-TD)" strip_icon="land-left.png">
      <set value="-DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block name="land">
      <call_once fun="nav_compute_baseleg(WP_AF, WP_TD, WP__BASELEG, nav_radius)"/>
      <circle radius="nav_radius" until="NavCircleCount() @GT 0.5" wp="_BASELEG"/>
      <circle radius="nav_radius" until="NavQdrCloseTo(DegOfRad(baseleg_out_qdr)-(nav_radius/fabs(nav_radius))*10) @AND (fabs(GetPosAlt() - WaypointAlt(WP__BASELEG)) @LT 10)" wp="_BASELEG"/>
    </block>
    <block name="final">
      <exception cond="GetAltRef() + 10 @GT GetPosAlt()" deroute="flare"/>
      <go from="AF" hmode="route" vmode="glide" wp="TD"/>
    </block>
    <block name="flare">
      <go approaching_time="0" from="AF" hmode="route" throttle="0.0" vmode="throttle" wp="TD"/>
      <attitude roll="0.0" throttle="0.0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== paparazzi/paparazzi/conf/flight_plans/slayer_training.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan alt="75" ground_alt="0" lat0="43.4622" lon0="1.2729" max_dist_from_home="800" name="Versatile" qfu="270" security_height="25">
  <header>
#include "subsystems/navigation/bomb.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="T1" x="-172.3" y="223.2"/>
    <waypoint name="T2" x="126.7" y="314.0"/>
    <waypoint name="T1__" x="-275.8" y="234.9"/>
    <waypoint name="T2__" x="213.1" y="307.2"/>
    <waypoint name="T3_SW" x="266.7" y="80.3"/>
    <waypoint name="T3_NE" x="439.1" y="240.0"/>
    <waypoint alt="30" name="AF" x="200" y="-10"/>
    <waypoint alt="0" name="TD" x="58.3" y="45.2"/>
    <waypoint name="BASELEG" x="309.9" y="138.1"/>
    <waypoint name="STDBY" x="-82.4" y="33.8"/>
    <waypoint name="RELEASE" x="126.9" y="181.6"/>
    <waypoint alt="30" name="START" x="168.8" y="-2.6"/>
    <waypoint name="CLIMB" x="19.2" y="212.5"/>
    <waypoint alt="0.0" name="TARGET" x="25.4" y="73.2"/>
    <waypoint name="A1" x="58.8" y="23.3"/>
    <waypoint name="A2" x="-30.7" y="66.8"/>
    <waypoint alt="9.0" name="A1__" x="150.9" y="16.5"/>
    <waypoint alt="9.0" name="A2__" x="-96.5" y="126.9"/>
    <waypoint alt="15.0" name="A0" x="214.6" y="103.7"/>
  </waypoints>
  <blocks>
    <block name="wait GPS">
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call fun="NavSetGroundReferenceHere()"/>
      <deroute block="climb"/>
    </block>
    <block name="climb">
      <attitude pitch="10" roll="0" throttle="0.9" until="GetPosAlt() > ground_alt+30" vmode="throttle"/>
    </block>
    <block name="standby" strip_button="STDBY">
      <circle radius="nav_radius" wp="STDBY"/>
    </block>
    <block name="identify T1">
      <eight center="T1" radius="nav_radius" turn_around="T1__"/>
    </block>
    <block name="identify T2">
      <eight center="T2" radius="nav_radius" turn_around="T2__"/>
    </block>
    <block name="locate T3">
      <survey_rectangle grid="150" wp1="T3_SW" wp2="T3_NE"/>
    </block>
    <block name="bomb" strip_button="Bomb">
      <set value="BombComputeApproach(WP_TARGET, WP_START)" var="unit"/>
      <circle radius="BOMB_RADIUS" until="NavQdrCloseTo(DegOfRad(bomb_start_qdr)-10)" wp="BASELEG"/>
    </block>
    <block name="align">
      <exception cond="BombUpdateRelease(WP_TARGET)" deroute="standby"/>
      <go approaching_time="bomb_trigger_delay" from="START" hmode="route" wp="RELEASE"/>
    </block>
    <block name="shoot">
      <set value="BombShoot()" var="unit"/>
      <go approaching_time="0" from="RELEASE" hmode="route" wp="CLIMB"/>
      <set value="BombCloseHatch()" var="unit"/>
      <deroute block="standby"/>
    </block>
    <block name="close">
      <set value="BombCloseHatch()" var="unit"/>
      <deroute block="standby"/>
    </block>
    <block name="arch">
      <oval p1="A1__" p2="A2__" radius="nav_radius"/>
    </block>
    <block name="land">
      <call fun="nav_compute_baseleg(WP_AF, WP_TD, WP_BASELEG)"/>
      <circle radius="nav_radius" until="NavCircleCount() > 0.5" wp="BASELEG"/>
      <set value="V_CTL_AUTO_THROTTLE_MIN_CRUISE_THROTTLE" var="v_ctl_auto_throttle_cruise_throttle"/>
      <circle radius="nav_radius" until="NavQdrCloseTo(DegOfRad(baseleg_out_qdr)-(nav_radius/fabs(nav_radius))*10) && 10 > fabs(GetPosAlt() - WaypointAlt(WP_BASELEG))" wp="BASELEG"/>
    </block>
    <block name="final">
      <exception cond="ground_alt + 10 > GetPosAlt()" deroute="flare"/>
      <go from="AF" hmode="route" vmode="glide" wp="TD"/>
    </block>
    <block name="flare">
      <go approaching_time="0" from="AF" hmode="route" throttle="0.0" vmode="throttle" wp="TD"/>
      <attitude roll="0.0" throttle="0.0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== paparazzi/paparazzi/conf/flight_plans/ENAC/cohoma/cohoma_beynes_demo.xml
<?xml version="1.0"?>
<!DOCTYPE flight_plan SYSTEM "../../flight_plan.dtd">
<flight_plan alt="185" ground_alt="115" lat0="48.8614" lon0="1.89647" max_dist_from_home="300" name="COHOMA2" security_height="30">
  <header>
    static inline bool delay_test_rc(bool test, int delay) {
      static int nb = 0;
        if (test) {
        nb++;
        if (nb == delay) {
          nb = 0;
          return true;
        }
        return false;
      } else {
        nb = 0;
        return false;
      }
    }

    static inline bool delay_test_gf(bool test, int delay) {
      static int nb = 0;
      if (test) {
        nb++;
        if (nb == delay) {
          nb = 0;
          return true;
        }
        return false;
      } else {
        nb = 0;
        return false;
      }
    }

    #if DIGITAL_CAM
    #define LINE_START_FUNCTION dc_Survey(20);
    #define LINE_STOP_FUNCTION dc_autoshoot = DC_AUTOSHOOT_STOP;
    #endif
  </header>
  <waypoints>
    <waypoint name="HOME" lat="48.8615" lon="1.89836"/>
    <waypoint name="STDBY" lat="48.8615" lon="1.89686"/>
    <waypoint name="LANDPAD" lat="48.8614" lon="1.89647"/>
    <waypoint name="L1_START" lat="48.8616" lon="1.8973"/>
    <waypoint name="L1_END" lat="48.8612" lon="1.89934"/>
    <waypoint name="L2_START" lat="48.8619" lon="1.89761"/>
    <waypoint name="L2_END" lat="48.8615" lon="1.89956"/>
    <waypoint name="VAB" lat="48.8622" lon="1.89884"/>
    <waypoint name="_FLY1" lat="48.8601" lon="1.90036"/>
    <waypoint name="_FLY2" lat="48.8613" lon="1.89552"/>
    <waypoint name="_FLY3" lat="48.8635" lon="1.89704"/>
    <waypoint name="_FLY4" lat="48.8625" lon="1.90163"/>
    <!--waypoint name="_KILL1" lat="48.8583" lon="1.89994"/>
    <waypoint name="_KILL2" lat="48.8602" lon="1.8933"/>
    <waypoint name="_KILL3" lat="48.8647" lon="1.89634"/>
    <waypoint name="_KILL4" lat="48.8632" lon="1.90243"/-->
  </waypoints>
  <sectors>
    <!--sector name="KillZone" color="red">
      <corner name="_KILL1"/>
      <corner name="_KILL2"/>
      <corner name="_KILL3"/>
      <corner name="_KILL4"/>
    </sector-->
    <sector name="FlyZone" color="green">
      <corner name="_FLY1"/>
      <corner name="_FLY2"/>
      <corner name="_FLY3"/>
      <corner name="_FLY4"/>
    </sector>
  </sectors>
  <variables>
    <variable var="fp_max_height" init="110." min="10." max="120." step="1."/>
    <variable var="fp_oval_radius" init="-40." min="-80." max="80." step="1."/>
  </variables>
  <modules>
    <module name="mission" type="rotorcraft">
      <define name="MISSION_WAIT_TIMEOUT" value="240"/>
    </module>
    <module name="nav" type="takeoff_and_landing"/>
    <module name="nav" type="survey_hybrid"/>
  </modules>
  <exceptions>
    <!-- RC-Loss -->
    <!--exception cond="(delay_test_rc(RadioControlIsLost(),20) @AND
      !(IndexOfBlock('Takeoff') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('Kill landed')) @AND
      (autopilot_in_flight() == true) )" deroute="EmergencyLanding"/-->

    <!-- Datalink loss -->
    <exception cond="(datalink_time @GT 10 @AND
      !(IndexOfBlock('Takeoff') @GT nav_block) @AND
      !(nav_block @GEQ IndexOfBlock('Kill landed')) @AND
      (autopilot_in_flight() == true) )" deroute="EmergencyLanding"/>

    <!-- Geofence -->
    <exception cond="((!InsideFlyZone(GetPosX(), GetPosY()) @OR GetPosHeight() @GT fp_max_height) @AND
      !(IndexOfBlock('Takeoff') @GT nav_block) @AND
      !(nav_block @GEQ IndexOfBlock('Kill landed')) @AND
      (autopilot_in_flight() == true) )" deroute="Standby"/>

    <!--exception cond="((delay_test_gf(!InsideKillZone(GetPosX(), GetPosY()),10) @OR GetPosHeight() @GT fp_max_height+10) @AND
      !(IndexOfBlock('Takeoff') @GT nav_block) @AND
      !(nav_block @GEQ IndexOfBlock('Kill landed')) @AND
      (autopilot_in_flight() == true) )" deroute="Kill landed"/-->

  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 3)"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <!--block name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="GetPosHeight() @GT 10." deroute="Standby"/>
      <call_once fun="ins_reset_vertical_pos()"/>
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0." until="stage_time @GT 2" vmode="throttle"/>
      <call_once fun="NavSetWaypointHere(WP_LANDPAD)"/>
      <stay climb="nav.climb_vspeed" vmode="climb" wp="LANDPAD"/>
    </block-->
    <block name="Takeoff" strip_button="Takeoff (Here)" group="takeoff">
      <call fun="nav_takeoff_from_here()"/>
      <deroute block="Standby"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <stay wp="STDBY"/>
    </block>
    <block name="Goto VAB" strip_button="Goto VAB" group="mission">
      <exception cond="!(mission_get() == NULL)" deroute="Mission"/>
      <stay wp="VAB"/>
    </block>
    <block name="Circle VAB" strip_button="Circle VAB" group="mission">
      <exception cond="!(mission_get() == NULL)" deroute="Mission"/>
      <circle wp="VAB" radius="nav.radius"/>
    </block>
    <block name="Mission" strip_button="Mission">
      <call fun="mission_run()"/>
      <deroute block="Standby"/>
    </block>
    <block name="Carto Oval" strip_button="Carto Oval">
      <oval p1="L1_END" p2="L1_START" radius="fp_oval_radius" until="NavOvalCount @GEQ 2"/>
      <oval p1="L2_END" p2="L2_START" radius="fp_oval_radius" until="NavOvalCount @GEQ 2"/>
      <deroute block="Standby"/>
    </block>
    <block name="Land (WP)" strip_button="Land (WP)" group="land">
      <call fun="nav_land_at_wp(WP_LANDPAD, WP_LANDPAD, 0.)"/>
      <deroute block="Kill landed"/>
    </block>
    <block name="Land here" strip_button="Land here" strip_icon="land-right.png" group="land">
      <call_once fun="NavSetWaypointHere(WP_LANDPAD)"/>
    </block>
    <block name="Land" strip_button="Land on pad" group="land">
      <go wp="LANDPAD"/>
    </block>
    <block name="Flare">
      <exception cond="!nav_is_in_flight()" deroute="Kill landed"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="LANDPAD"/>
    </block>
    <block name="Kill landed">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="EmergencyLanding">
      <stay wp="HOME" vmode="throttle" throttle="0."/>
    </block>
  </blocks>
</flight_plan>
