=== paparazzi/paparazzi/conf/flight_plans/flight_plan.dtd
<!-- Paparazzi flight plan DTD -->

<!ELEMENT flight_plan (header?,waypoints,sectors?,variables?,modules?,includes?,exceptions?,blocks)>

<!ELEMENT procedure (param*,header?,waypoints?,sectors?,exceptions?,blocks?)>

<!ELEMENT header (#PCDATA)>

<!ELEMENT waypoints (waypoint+)>
<!ELEMENT waypoint EMPTY>

<!ELEMENT sectors (sector|kml)*>
<!ELEMENT sector (corner,corner,corner+)>
<!ELEMENT corner EMPTY>
<!ELEMENT kml EMPTY>

<!ELEMENT variables (variable*)>
<!ELEMENT variable EMPTY>

<!ELEMENT modules (module*)>
<!ELEMENT module  (configure|define)*>
<!ELEMENT configure EMPTY>
<!ELEMENT define EMPTY>

<!ELEMENT includes (include*)>

<!ELEMENT exceptions (exception*)>

<!ELEMENT blocks (block+)>
<!ELEMENT block (exception|while|heading|attitude|manual|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|home|path)*>

<!ELEMENT include (arg|with)*>
<!ELEMENT arg EMPTY>
<!ELEMENT with EMPTY>

<!ELEMENT while (exception|while|heading|attitude|manual|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path)*>
<!ELEMENT for (exception|while|heading|attitude|manual|go|xyz|set|call|call_once|circle|deroute|stay|follow|survey_rectangle|for|return|eight|oval|path)*>
<!ELEMENT exception EMPTY>
<!ELEMENT heading EMPTY>
<!ELEMENT attitude EMPTY>
<!ELEMENT manual EMPTY>
<!ELEMENT go EMPTY>
<!ELEMENT xyz EMPTY>
<!ELEMENT set EMPTY>
<!ELEMENT call EMPTY>
<!ELEMENT call_once EMPTY>
<!ELEMENT circle EMPTY>
<!ELEMENT home EMPTY>
<!ELEMENT eight EMPTY>
<!ELEMENT oval EMPTY>
<!ELEMENT survey_rectangle EMPTY>
<!ELEMENT deroute EMPTY>
<!ELEMENT stay EMPTY>
<!ELEMENT follow EMPTY>
<!ELEMENT param EMPTY>
<!ELEMENT return EMPTY>
<!ELEMENT path EMPTY>


<!ATTLIST flight_plan
name CDATA #REQUIRED
lat0 CDATA #REQUIRED
lon0 CDATA #REQUIRED
max_dist_from_home CDATA #REQUIRED
ground_alt CDATA #REQUIRED
security_height CDATA #REQUIRED
alt CDATA #REQUIRED
qfu CDATA #IMPLIED
home_mode_height CDATA #IMPLIED
geofence_max_alt CDATA #IMPLIED
geofence_sector CDATA #IMPLIED>

<!ATTLIST waypoints
utm_x0 CDATA #IMPLIED
utm_y0 CDATA #IMPLIED>

<!ATTLIST waypoint
name CDATA #REQUIRED
x CDATA #IMPLIED
y CDATA #IMPLIED
lat CDATA #IMPLIED
lon CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST exceptions>

<!ATTLIST sectors>

<!ATTLIST sector
name CDATA #REQUIRED
color CDATA #IMPLIED
type CDATA #IMPLIED>

<!ATTLIST corner
name CDATA #REQUIRED>

<!ATTLIST kml
file CDATA #REQUIRED>

<!ATTLIST variables>

<!ATTLIST variable
var CDATA #REQUIRED
type CDATA #IMPLIED
init CDATA #IMPLIED
shortname CDATA #IMPLIED
min CDATA #IMPLIED
max CDATA #IMPLIED
step CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED>

<!ATTLIST modules>

<!ATTLIST module
name CDATA #REQUIRED
type CDATA #IMPLIED>

<!ATTLIST define
name CDATA #REQUIRED
value CDATA #IMPLIED>

<!ATTLIST configure
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST blocks>

<!ATTLIST block
name CDATA #REQUIRED
pre_call CDATA #IMPLIED
post_call CDATA #IMPLIED
strip_button CDATA #IMPLIED
strip_icon CDATA #IMPLIED
group CDATA #IMPLIED
key CDATA #IMPLIED
description CDATA #IMPLIED>

<!ATTLIST exception
cond CDATA #REQUIRED
deroute CDATA #REQUIRED>

<!ATTLIST while cond CDATA #IMPLIED>

<!ATTLIST for
var CDATA #REQUIRED
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST heading
course CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #REQUIRED>

<!ATTLIST attitude
roll CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST manual
pitch CDATA #REQUIRED
roll CDATA #REQUIRED
yaw CDATA #REQUIRED
vmode CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST go
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
from CDATA #IMPLIED
from_qdr CDATA #IMPLIED
from_dist CDATA #IMPLIED
hmode CDATA #IMPLIED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
height CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST path
wpts CDATA #REQUIRED
vmode CDATA #IMPLIED
pitch CDATA #IMPLIED
alt CDATA #IMPLIED
approaching_time CDATA #IMPLIED
exceeding_time CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED>

<!ATTLIST set
var CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST call
fun CDATA #REQUIRED
until CDATA #IMPLIED
loop CDATA #IMPLIED
break CDATA #IMPLIED>

<!ATTLIST call_once
fun CDATA #REQUIRED
break CDATA #IMPLIED>

<!ATTLIST follow
ac_id CDATA #REQUIRED
distance CDATA #REQUIRED
height CDATA #REQUIRED>

<!ATTLIST xyz
radius CDATA #IMPLIED>

<!ATTLIST home>

<!ATTLIST circle
wp CDATA #REQUIRED
wp_qdr CDATA #IMPLIED
wp_dist CDATA #IMPLIED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
height CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST eight
center CDATA #REQUIRED
turn_around CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
until CDATA #IMPLIED
radius CDATA #REQUIRED>


<!ATTLIST oval
p1 CDATA #REQUIRED
p2 CDATA #REQUIRED
radius CDATA #REQUIRED
alt CDATA #IMPLIED
vmode CDATA #IMPLIED
climb CDATA #IMPLIED
pitch CDATA #IMPLIED
throttle CDATA #IMPLIED
until CDATA #IMPLIED>

<!ATTLIST survey_rectangle
grid CDATA #REQUIRED
orientation CDATA #IMPLIED
wp1 CDATA #REQUIRED
wp2 CDATA #REQUIRED
until CDATA #IMPLIED>

<!ATTLIST stay
wp CDATA #REQUIRED
vmode CDATA #IMPLIED
throttle CDATA #IMPLIED
climb CDATA #IMPLIED
alt CDATA #IMPLIED
until CDATA #IMPLIED
height CDATA #IMPLIED>

<!ATTLIST deroute
block CDATA #REQUIRED>

<!ATTLIST includes>

<!ATTLIST include
name CDATA #REQUIRED
procedure CDATA #REQUIRED
>

<!ATTLIST arg
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!ATTLIST with
from CDATA #REQUIRED
to CDATA #REQUIRED>

<!ATTLIST param
name CDATA #REQUIRED
default_value CDATA #IMPLIED>

<!ATTLIST header>

<!ATTLIST return>

=== paparazzi/paparazzi/conf/flight_plans/legacy/creidlitz.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="420" ground_alt="360" lat0="50.230060" lon0="10.990449" max_dist_from_home="1500" name="Flugplatz Steinruecken" security_height="25"  QFU="210">
  <header>
#include "subsystems/datalink/datalink.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="STDBY" x="103.9" y="-96.3"/>
    <waypoint name="PROFILE" x="123.9" y="-116.7"/>
    <waypoint name="1" x="8.9" y="-149.8"/>
    <waypoint name="2" x="241.5" y="-62.1"/>
    <waypoint name="MOB" x="137.0" y="-11.6"/>
    <waypoint name="S1" x="-100.8" y="-293.0"/>
    <waypoint name="S2" x="307.3" y="-65.4"/>
    <waypoint name="CLIMB" x="-102.3" y="-129.0"/>
  </waypoints>
  <exceptions>
    <exception cond="GetPosAlt() > 3400" deroute="Standby"/>
    <exception cond="datalink_time > 30" deroute="Standby"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <set value="1" var="autopilot.kill_throttle"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetGroundReferenceHere()"/>
    </block>
    <block name="Holding point">
      <set value="1" var="autopilot.kill_throttle"/>
      <attitude roll="0" throttle="0" vmode="throttle"/>
    </block>
    <block name="Takeoff" strip_button="Takeoff (wp CLIMB)" strip_icon="takeoff.png">
      <exception cond="GetPosAlt() > GetAltRef()+25" deroute="Standby"/>
      <set value="0" var="autopilot.kill_throttle"/>
      <set value="0" var="autopilot.flight_time"/>
      <go from="HOME" throttle="1.0" vmode="throttle" wp="CLIMB"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <circle radius="nav_radius" wp="STDBY"/>
    </block>
    <block name="profile_up" strip_button="Profile Up" strip_icon="up_profile.png">
      <circle radius="nav_radius" wp="PROFILE"/>
    </block>
    <block name="profile_down" strip_button="Profile Down" strip_icon="down_profile.png">
      <circle pitch="RadOfDeg(-10)" radius="nav_radius" throttle="0" until="(GetAltRef()+150 > GetPosAlt())" vmode="throttle" wp="PROFILE"/>
      <deroute block="Standby"/>
    </block>
    <block name="MOB" strip_button="Circle around here" strip_icon="mob.png">
      <call_once fun="NavSetWaypointHere(WP_MOB)"/>
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <circle radius="nav_radius" wp="MOB"/>
    </block>
    <block name="Line 1-2" strip_button="Line (wp 1-2)" strip_icon="line.png">
      <exception cond="datalink_time > 22" deroute="Standby"/>
      <call_once fun="nav_line_setup()"/>
      <call fun="nav_line_run(WP_1, WP_2, nav_radius)"/>
    </block>
    <block name="Oval 1-2" strip_button="Oval (wp 1-2)" strip_icon="oval.png">
      <oval p1="1" p2="2" radius="nav_radius"/>
    </block>
    <block name="Survey S1-S2 NS" strip_button="Survey (wp S1-S2) NS" strip_icon="survey.png">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>
    <block name="Survey S1-S2 WE" strip_button="Survey (wp S1-S2) WE" strip_icon="survey_we.png">
      <survey_rectangle grid="150" orientation="WE" wp1="S1" wp2="S2"/>
    </block>
  </blocks>
</flight_plan>

=== paparazzi/paparazzi/conf/flight_plans/tudelft/oneloop_cyberzoo.xml
<!DOCTYPE flight_plan SYSTEM "../flight_plan.dtd">

<flight_plan alt="1.0" ground_alt="0" lat0="51.990634" lon0="4.376789" max_dist_from_home="60" name="Safe TU Delft Cyberzoo" security_height="0.4">
  <header>
    #include "autopilot.h"
    #include "modules/datalink/datalink.h"
    #include "modules/energy/electrical.h"
    #include "modules/radio_control/radio_control.h"
    #include "modules/ahrs/ahrs.h"
    #include "modules/gps/gps.h"
    #include "modules/rotwing_drone/rotwing_state.h"
    <!-- #include "sw/airborne/firmwares/rotorcraft/oneloop/oneloop_andi.h" -->
    inline static void set_demo_skew(void) {
      float amplitude_skew_demo       = (rotwing_demo_max_skew - rotwing_demo_min_skew) / 2;
      float offset_skew_demo          = (rotwing_demo_max_skew + rotwing_demo_min_skew) / 2;
      float time_skew_demo            = (float) rotwing_demo_timestep / NAVIGATION_FREQUENCY;
      float angle_skew_demo           = amplitude_skew_demo * (-cosf(2 * M_PI * rotwing_demo_freq_skew * time_skew_demo)) + offset_skew_demo;
      rotwing_state.sp_skew_angle_deg = angle_skew_demo;
      rotwing_demo_timestep++;
    }
</header>
  <waypoints>
    <waypoint lat="51.990631" lon="4.376796" name="HOME"/>
    <waypoint name="CLIMB" x="1.9" y="1.0"/>
    <waypoint name="STDBY" x="0.5" y="0.3"/>
    <waypoint name="p5" x="0.2" y="0.3"/>
    <waypoint name="TD" x="0.8" y="-1.7"/>
    <waypoint lat="51.9905979" lon="4.3767279" name="CZ1"/>
    <waypoint lat="51.9906685" lon="4.3767327" name="CZ2"/>
    <waypoint lat="51.9906652" lon="4.3768481" name="CZ3"/>
    <waypoint lat="51.9905941" lon="4.3768441" name="CZ4"/>
    <waypoint lat="51.9906028" lon="4.3767375" name="p1"/>
    <waypoint lat="51.9906633" lon="4.3767411" name="p2"/>
    <waypoint lat="51.9906601" lon="4.3768415" name="p3"/>
    <waypoint lat="51.9905979" lon="4.3768386" name="p4"/>
  </waypoints>
  <sectors>
    <sector color="blue" name="CyberZoo">
      <corner name="CZ1"/>
      <corner name="CZ2"/>
      <corner name="CZ3"/>
      <corner name="CZ4"/>
    </sector>
    <sector color="red" name="Flyzone">
      <corner name="p1"/>
      <corner name="p2"/>
      <corner name="p3"/>
      <corner name="p4"/>
    </sector>
  </sectors>
  <variables>
    <variable var="rotwing_demo_max_skew"  init="50.0f" type="float"  min="0"   step="1"   max="80" shortname="demo_max_skew"/>
    <variable var="rotwing_demo_min_skew"  init="0.0f"  type="float"  min="0"   step="1"   max="80" shortname="demo_min_skew"/>
    <variable var="rotwing_demo_freq_skew" init="0.8f"  type="float"  min="0.1" step="0.1" max="10" shortname="demo_freq_skew"/>
    <variable var="rotwing_demo_timestep"  init="0"     type="uint32_t"/>
  </variables>
  <exceptions>
    <!--Soft Geofencing (go back to Standby)-->
    <exception cond="Or(!InsideFlyzone(GetPosX(), GetPosY()), GetPosAlt() @GT 20.0) @AND
     !(nav_block == IndexOfBlock('Wait GPS')) @AND
     !(nav_block == IndexOfBlock('Geo init'))" deroute="safe"/>
    <!-- Hard Geofencing (Kill) -->
    <exception cond="(Or(!InsideCyberZoo(GetPosX(), GetPosY()), GetPosAlt() @GT 80.0) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Landed"/>
    <!-- RC lost -->
    <exception cond="((radio_control.status == RC_REALLY_LOST) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Landed"/>
    <!-- Datalink lost  -->
    <exception cond="((datalink_time @GT 5) @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="Landed"/>
    <!-- Bat low (constant RPM descent)-->
    <exception cond="(electrical.bat_low @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
    <!-- Bat critical (constant RPM no stabilization)-->
    <exception cond="(electrical.bat_critical @AND
      !(IndexOfBlock('Holding point') @GT nav_block) @AND
      !(nav_block >= IndexOfBlock('land here')) @AND
      (autopilot_in_flight() == true) )" deroute="land here"/>
  </exceptions>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 2)"/>
      <call_once fun="NavSetAltitudeReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block key="r" name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
      <call_once fun="NavResurrect()"/>
    </block>
    <block key="t" name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="GetPosAlt() @GT 0.8" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay climb="nav.climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    <block key="s" name="Standby" strip_button="Standby" strip_icon="home.png">
      <stay wp="STDBY"/>
    </block>
    <block key="d" name="Standby Demo" on_enter="rotwing_state.force_skew=true" on_exit="rotwing_state.force_skew=false; rotwing_demo_timestep = 0">  
      <stay wp="STDBY" pre_call="set_demo_skew()"/>
    </block>
    <block name="go_p5">
      <stay wp="p5"/>
    </block>
    <block name="safe">
      <stay wp="p5"/>
      <exception cond="NavBlockTime() @GT 5" deroute="go_p5"/>
    </block>
    <block key="l" name="land here" strip_button="land here" strip_icon="land-right.png">
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
      <go wp="TD"/>
      <deroute block="Flare"/>
    </block>
    <block name="Land">
      <go wp="TD"/>
      <deroute block="Flare"/>
    </block>
    <block name="Flare">
      <exception cond="NavDetectGround()" deroute="Holding point"/>
      <exception cond="!nav_is_in_flight()" deroute="Landed"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="Landed"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="Safe landing">
      <exception cond="!nav_is_in_flight()" deroute="Manual"/>
      <exception cond="0.10 @GT GetPosAlt()" deroute="Manual"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="nav.descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="Manual">
      <set value="AP_MODE_ATTITUDE_DIRECT" var="autopilot_mode_auto2"/>
      <stay wp="STDBY"/>
    </block>
    <block name="Landed">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>

=== paparazzi/paparazzi/conf/flight_plans/versatile_airspeed.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan alt="260" ground_alt="185" lat0="43.4622" lon0="1.2729" max_dist_from_home="1500" name="Versatile" qfu="270" security_height="25">
  <header>
#include "firmwares/fixedwing/guidance/energy_ctrl.h"
#include "subsystems/datalink/datalink.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0" y="0"/>
    <waypoint name="STDBY" x="20" y="80"/>
    <waypoint name="1" x="44.8" y="102.2"/>
    <waypoint name="2" x="-63.5" y="122.9"/>
    <waypoint name="MOB" x="-11.5" y="-21.2"/>
    <waypoint name="S1" x="-151.6" y="80.4"/>
    <waypoint name="S2" x="180.1" y="214.9"/>
    <waypoint alt="30" name="AF" x="200" y="-10"/>
    <waypoint alt="0" name="TD" x="80.0" y="20.0"/>
    <waypoint name="BASELEG" x="26.9" y="-23.0"/>
    <waypoint name="_1" x="-100" y="0"/>
    <waypoint name="_2" x="-100" y="200"/>
    <waypoint name="_3" x="100" y="200"/>
    <waypoint name="_4" x="100" y="0"/>
    <waypoint name="CLIMB" x="-122.5" y="35.4"/>
  </waypoints>
  <sectors>
    <sector name="Square">
      <corner name="_1"/>
      <corner name="_2"/>
      <corner name="_3"/>
      <corner name="_4"/>
    </sector>
  </sectors>
  <exceptions/>
  <blocks>
    <block name="Wait GPS">
      <set value="1" var="autopilot.kill_throttle"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetGroundReferenceHere()"/>
    </block>
    <block name="Holding point">
      <set value="1" var="autopilot.kill_throttle"/>
      <attitude roll="0" throttle="0" vmode="throttle"/>
    </block>
    <block name="Takeoff" strip_icon="takeoff.png" strip_button="Takeoff (wp CLIMB)">
      <exception cond="GetPosAlt() > GetAltRef()+25" deroute="Standby"/>
      <set value="0" var="autopilot.kill_throttle"/>
      <set value="CLIMB_AIRSPEED" var="v_ctl_auto_airspeed_setpoint" />
      <go wp="CLIMB"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <set value="NOMINAL_AIRSPEED" var="v_ctl_auto_airspeed_setpoint" />
      <circle radius="nav_radius" wp="STDBY"/>
    </block>
    <block name="Figure 8 around wp 1" strip_button="Figure 8 (wp 1-2)" strip_icon="eight.png">
      <eight center="1" radius="nav_radius" turn_around="2"/>
    </block>
    <block name="Oval 1-2" strip_button="Oval (wp 1-2)" strip_icon="oval.png">
      <set value="RACE_AIRSPEED" var="v_ctl_auto_airspeed_setpoint" />
      <oval p1="1" p2="2" radius="nav_radius"/>
    </block>
    <block name="MOB" strip_button="Circle around here" strip_icon="mob.png">
      <call_once fun="NavSetWaypointHere(WP_MOB)"/>
      <circle radius="100" wp="MOB"/>
    </block>
    <block name="Auto pitch (circle wp 1)">
      <circle pitch="auto" radius="75" throttle="0.7" wp="1"/>
    </block>
    <block name="Climb 75% throttle">
      <circle pitch="10" radius="50+(GetPosAlt()-GetAltRef())/2" throttle="0.75" until="(10 > PowerVoltage()) || (GetPosAlt() > GetAltRef()+ 1350)" vmode="throttle" wp="1"/>
    </block>
    <block name="Climb 0m/s">
      <circle climb="0" radius="nav_radius" until="10 > PowerVoltage()" vmode="climb" wp="1"/>
    </block>
    <block name="Climb 1m/s">
      <circle climb="1" pitch="5" radius="50+(GetPosAlt()-GetAltRef())/2" until="10 > PowerVoltage()" vmode="climb" wp="1"/>
    </block>
    <block name="Climb nav_climb m/s">
      <circle climb="nav_climb" radius="nav_radius" until="(10 > PowerVoltage()) || (GetPosAlt() > GetAltRef()+ 1350)" vmode="climb" wp="1"/>
    </block>

    <block name="Circle 0% throttle">
      <circle pitch="fp_pitch" radius="nav_radius" throttle="0.0" until="GetAltRef()+50 > GetPosAlt()" vmode="throttle" wp="1"/>
      <deroute block="Standby"/>
    </block>

    <block name="Oval 0% throttle">
      <oval p1="1" p2="2" pitch="fp_pitch" radius="nav_radius" throttle="0.0" until="GetAltRef()+50 > GetPosAlt()" vmode="throttle"/>
      <deroute block="Standby"/>
    </block>


    <block name="Route 1-2">
      <go approaching_time="0" from="1" hmode="route" wp="2"/>
    </block>
    <block name="Stack wp 2">
      <circle radius="75" wp="2"/>
    </block>
    <block name="Route 2-1">
      <go approaching_time="0" from="2" hmode="route" wp="1"/>
    </block>
    <block name="Stack wp 1">
      <circle radius="75" wp="1"/>
    </block>
    <block name="Glide 1-2">
      <go from="1" hmode="route" vmode="glide" wp="2"/>
      <deroute block="Standby"/>
    </block>
    <block name="Survey S1-S2" strip_button="Survey (wp S1-S2)" strip_icon="survey.png">
      <survey_rectangle grid="150" wp1="S1" wp2="S2"/>
    </block>
    <block name="Land Right AF-TD" strip_button="Land right (wp AF-TD)" strip_icon="land-right.png">
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block name="Land Left AF-TD" strip_button="Land left (wp AF-TD)" strip_icon="land-left.png">
      <set value="-DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block name="Constant Slope Land Right AF-TD" strip_button="Land right (wp AF-TD)" strip_icon="land-right.png">
      <call_once fun="nav_compute_final_from_glide(WP_AF, WP_TD, 10.)"/>
      <set value="DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block name="Constant Slope Land Left AF-TD" strip_button="Land left (wp AF-TD)" strip_icon="land-left.png">
      <call_once fun="nav_compute_final_from_glide(WP_AF, WP_TD, 10.)"/>
      <set value="-DEFAULT_CIRCLE_RADIUS" var="nav_radius"/>
      <deroute block="land"/>
    </block>
    <block name="land">
      <set value="NOMINAL_AIRSPEED" var="v_ctl_auto_airspeed_setpoint" />
      <call_once fun="nav_compute_baseleg(WP_AF, WP_TD, WP_BASELEG, nav_radius)"/>
      <circle radius="nav_radius" until="NavCircleCount() > 0.5" wp="BASELEG"/>
      <set value="GLIDE_AIRSPEED" var="v_ctl_auto_airspeed_setpoint" />
      <circle radius="nav_radius" until="NavQdrCloseTo(DegOfRad(baseleg_out_qdr)-(nav_radius/fabs(nav_radius))*10) && 10 > fabs(GetPosAlt() - WaypointAlt(WP_BASELEG))" wp="BASELEG"/>
    </block>
    <block name="final">
      <go from="AF" hmode="route" vmode="glide" wp="TD" approaching_time="5" />
      <set value="(GLIDE_AIRSPEED*10.0/12.0)" var="v_ctl_auto_airspeed_setpoint" />
    </block>
    <block name="flare">
      <go approaching_time="0" from="AF" hmode="route" throttle="0.0" vmode="glide" wp="TD"  approaching_time="0" />
      <attitude roll="0.0" throttle="0.0" until="FALSE" vmode="throttle" />
    </block>
    <block name="Steps roll -10, +10">
      <while cond="TRUE">
        <attitude alt="250" roll="10.0" until=" stage_time > 6" vmode="alt"/>
        <attitude alt="250" roll="-10.0" until="stage_time > 6" vmode="alt"/>
      </while>
    </block>
    <block name="Steps roll -20, +20">
      <while cond="TRUE">
        <attitude alt="250" roll="20.0" until=" stage_time > 3" vmode="alt"/>
        <attitude alt="250" roll="-20.0" until="stage_time > 3" vmode="alt"/>
      </while>
    </block>
    <block name="Steps pitch -10, +10">
      <while cond="TRUE">
        <attitude alt="250" pitch="10" roll="0.0" until=" stage_time > 2" vmode="alt"/>
        <attitude alt="250" pitch="-10" roll="0.0" until=" stage_time > 2" vmode="alt"/>
      </while>
    </block>
    <block name="Heading 30">
      <heading alt="GetAltRef()+50" course="30" until="FALSE"/>
    </block>
    <block name="For loop (circles wp 1)">
      <for from="0" to="3" var="i">
        <circle radius="DEFAULT_CIRCLE_RADIUS+ $i*10" wp="1" until="NavCircleCount() > 1"/>
      </for>
      <deroute block="Standby"/>
    </block>
    <block name="Test datalink (go to wp 2)">
      <exception cond="datalink_time > 22" deroute="Standby"/>
      <go from="STDBY" hmode="route" wp="2"/>
      <go from="2" hmode="route" wp="STDBY"/>
    </block>
    <block name="Fly in Square">
      <exception cond="! InsideSquare(GetPosX(), GetPosY())" deroute="Come back wp 1"/>
      <attitude alt="GetAltRef()+75" roll="0" vmode="alt"/>
    </block>
    <block name="Come back wp 1">
      <exception cond="InsideSquare(GetPosX(), GetPosY())" deroute="Fly in Square"/>
      <go wp="1"/>
      <deroute block="Fly in Square"/>
    </block>
  </blocks>
</flight_plan>

=== paparazzi/paparazzi/conf/flight_plans/rotorcraft_cam.xml
<!DOCTYPE flight_plan SYSTEM "flight_plan.dtd">

<flight_plan alt="152" ground_alt="147" lat0="43 33 50.83" lon0="1 28 52.61" max_dist_from_home="150" name="Rotorcraft Cam test (Enac)" security_height="2">
  <header>
#include "autopilot.h"
</header>
  <waypoints>
    <waypoint name="HOME" x="0.0" y="0.0"/>
    <waypoint name="CLIMB" x="0.0" y="5.0"/>
    <waypoint name="STDBY" x="-2.0" y="-5.0"/>
    <waypoint name="p1" x="22.4" y="-15.9"/>
    <waypoint name="p2" x="60.5" y="-71.6"/>
    <waypoint name="p3" x="43.1" y="-83.1"/>
    <waypoint name="p4" x="2.7" y="-26.7"/>
    <waypoint height="2." name="CAM" x="-20" y="-50"/>
    <waypoint name="TD" x="5.6" y="-10.9"/>
  </waypoints>
  <blocks>
    <block name="Wait GPS">
      <call_once fun="NavKillThrottle()"/>
      <while cond="!GpsFixValid()"/>
    </block>
    <block name="Geo init">
      <while cond="LessThan(NavBlockTime(), 10)"/>
      <call_once fun="NavSetGroundReferenceHere()"/>
    </block>
    <block name="Holding point">
      <call_once fun="NavKillThrottle()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Start Engine">
      <call_once fun="NavResurrect()"/>
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
    <block name="Takeoff" strip_button="Takeoff" strip_icon="takeoff.png">
      <exception cond="stateGetPositionEnu_f()->z > 2.0" deroute="Standby"/>
      <call_once fun="NavSetWaypointHere(WP_CLIMB)"/>
      <stay climb="nav_climb_vspeed" vmode="climb" wp="CLIMB"/>
    </block>
    <block name="Standby" strip_button="Standby" strip_icon="home.png">
      <stay wp="STDBY"/>
    </block>
    <block name="stay_p1">
      <stay wp="p1"/>
    </block>
    <block name="go_p2">
      <call_once fun="nav_set_heading_deg(90)"/>
      <go wp="p2"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="line_p1_p2">
      <go from="p1" hmode="route" wp="p2"/>
      <stay until="stage_time>10" wp="p2"/>
      <go from="p2" hmode="route" wp="p1"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="route dc shoot">
      <go wp="p1"/>
      <set value="DC_AUTOSHOOT_DISTANCE" var="dc_autoshoot"/>
      <go from="p1" hmode="route" wp="p2"/>
      <go from="p2" hmode="route" wp="p3"/>
      <go from="p3" hmode="route" wp="p4"/>
      <go from="p4" hmode="route" wp="p1"/>
      <set value="DC_AUTOSHOOT_STOP" var="dc_autoshoot"/>
      <deroute block="stay_p1"/>
    </block>
    <block name="circle CAM" pre_call="nav_set_heading_towards_waypoint(WP_CAM)">
      <set value="25" var="nav_radius"/>
      <call_once fun="dc_Circle(30)"/>
      <circle radius="nav_radius" until="NavCircleCount() > 1.0" wp="CAM"/>
      <call_once fun="dc_stop()"/>
      <deroute block="Standby"/>
    </block>
    <block name="land here" strip_button="Land Here" strip_icon="land-right.png">
      <call_once fun="NavSetWaypointHere(WP_TD)"/>
    </block>
    <block name="land">
      <go wp="TD"/>
    </block>
    <block name="flare">
      <exception cond="NavDetectGround()" deroute="Holding point"/>
      <exception cond="!nav_is_in_flight()" deroute="landed"/>
      <call_once fun="NavStartDetectGround()"/>
      <stay climb="nav_descend_vspeed" vmode="climb" wp="TD"/>
    </block>
    <block name="landed">
      <attitude pitch="0" roll="0" throttle="0" until="FALSE" vmode="throttle"/>
    </block>
  </blocks>
</flight_plan>
