=== paparazzi/paparazzi/conf/radios/radio.dtd
<!-- Radio configuration DTD -->

<!ELEMENT radio (channel+)>
<!ELEMENT channel EMPTY>

<!ATTLIST radio
  name CDATA #REQUIRED
  data_min CDATA #REQUIRED
  data_max CDATA #REQUIRED
  sync_min CDATA #REQUIRED
  sync_max CDATA #REQUIRED
  pulse_type CDATA #REQUIRED>

<!ATTLIST channel
  ctl CDATA #IMPLIED
  function CDATA #REQUIRED
  min CDATA #REQUIRED
  neutral CDATA #REQUIRED
  max CDATA #REQUIRED
  average CDATA #IMPLIED
  reverse CDATA #IMPLIED>

=== paparazzi/paparazzi/conf/radios/AGGIEAIR/aggieair_FrSky3dr.xml
<!DOCTYPE radio SYSTEM "../radio.dtd">
<!-- Values set by experiment using X8R receiver SBus connection -->
<radio name="FrSky X9D + X8R receiver SBus connection" data_min="350" data_max="2500" sync_min="8000" sync_max="19000" pulse_type="POSITIVE">
 <channel function="ROLL" min="2015" neutral="1490" max="990" average="0" reverse="1"/>
 <channel function="PITCH" min="2015" neutral="1490" max="990" average="0" reverse="1"/>
 <channel function="THROTTLE" min="2015" neutral="990" max="990" average="0" reverse="1"/>
 <channel function="YAW" min="2015" neutral="1490" max="990" average="0" reverse="1"/>

 <channel function="MODE" min="1862" neutral="1500" max="990" average="1" reverse="1"/>
 <channel function="KILL" min="2015" neutral="1490" max="990" average="1" reverse="1"/>
 <channel function="AUX2" min="2015" neutral="990" max="990" average="0" reverse="1"/>
 <channel function="UNUSED2" min="2015" neutral="1900" max="990" average="1" reverse="1"/>
</radio>

=== paparazzi/paparazzi/conf/radios/cockpitSX.xml
<!DOCTYPE radio SYSTEM "radio.dtd">
<radio name="cockpitSX (easy)" data_min="900" data_max="2100" sync_min ="5000" sync_max ="15000" pulse_type="POSITIVE">
 <channel ctl="D" function="ROLL"     min="2050" neutral="1500" max="950" average="0"/>
 <channel ctl="C" function="PITCH"    min="2050" neutral="1500" max="950" average="0"/>
 <channel ctl="B" function="YAW"      min="950" neutral="1500" max="2050" average="0"/>
 <channel ctl="A" function="THROTTLE" min="1223" neutral="1223" max="2050" average="0"/>
 <channel ctl="G" function="UNUSED"    min="2050" neutral="1500" max="950" average="1"/> <!-- center slider        -->
 <channel ctl="E" function="GAIN1"     min="2050" neutral="1496" max="948" average="1"/> <!-- top right slider     -->
 <channel ctl="PHAUX2" function="MODE"    min="2050" neutral="1500" max="948" average="1"/> <!-- Top right switch -->
</radio>
