=== paparazzi/paparazzi/conf/settings/settings.dtd
<!-- Dataling and RC settings DTD -->

<!ELEMENT settings (dl_settings?)>
<!ELEMENT dl_settings (dl_setting|dl_settings|include)+>
<!ELEMENT dl_setting (strip_button|key_press)*>
<!ELEMENT include EMPTY>
<!ELEMENT strip_button EMPTY>
<!ELEMENT key_press EMPTY>

<!ATTLIST settings
target CDATA #IMPLIED
>

<!ATTLIST dl_settings
name CDATA #IMPLIED
>

<!ATTLIST include
header CDATA #REQUIRED
>

<!ATTLIST dl_setting
var CDATA #REQUIRED
min CDATA #REQUIRED
max CDATA #REQUIRED
type CDATA #IMPLIED
step CDATA #IMPLIED
widget CDATA #IMPLIED
shortname CDATA #IMPLIED
module CDATA #IMPLIED
header CDATA #IMPLIED
handler CDATA #IMPLIED
param CDATA #IMPLIED
unit CDATA #IMPLIED
alt_unit CDATA #IMPLIED
alt_unit_coef CDATA #IMPLIED
values CDATA #IMPLIED
persistent CDATA #IMPLIED
>

<!ATTLIST strip_button
name CDATA #REQUIRED
value CDATA #REQUIRED
icon CDATA #IMPLIED
group CDATA #IMPLIED
>

<!ATTLIST key_press
key CDATA #REQUIRED
value CDATA #REQUIRED
>

=== paparazzi/paparazzi/conf/settings/beth/beth_twist_old.xml
<!DOCTYPE settings SYSTEM "../settings.dtd">

<settings>
  <dl_settings>
    <dl_settings NAME="Controller">

      <dl_setting var="controller.elevation_sp" min="-25" step="1" max="20" module="firmwares/beth/overo_twist_controller" shortname="elev_sp" unit="rad" alt_unit="deg" alt_unit_coef="57.29578"/>

      <dl_setting var="controller.tilt_sp" min="-15" step="0.5" max="15" module="firmwares/beth/overo_twist_controller"  shortname="tilt_sp" unit="rad" alt_unit="deg" alt_unit_coef="57.29578">
      </dl_setting>

      <dl_setting var="controller.azim_gain" min="0" step=".01" max=".1" module="firmwares/beth/overo_estimator"  shortname="azim_gain">
      </dl_setting>

      <dl_setting var="controller.omega_tilt_ref" min="200" step="100" max="1200" module="firmwares/beth/overo_twist_controller"  shortname="tilt_omega_ref" unit="rad/s" alt_unit="deg/s" alt_unit_coef="57.29578">
      </dl_setting>

      <dl_setting var="estimator.elevation_lp_coeff" min="0.01" step="0.01" max="1" module="firmwares/beth/overo_estimator"  shortname="elev_lp_coeff">
      </dl_setting>

      <dl_setting var="estimator.tilt_lp_coeff" min="0.01" step="0.01" max="1" module="firmwares/beth/overo_estimator"  shortname="tilt_lp_coeff">
      </dl_setting>

      <dl_setting var="estimator.azimuth_lp_coeff" min="0.01" step="0.01" max="1" module="firmwares/beth/overo_estimator"  shortname="azim_lp_coeff">
      </dl_setting>

      <dl_setting var="controller.ulim" min="0.1" step="0.1" max="50" module="firmwares/beth/overo_twist_controller" shortname="ulim">
      </dl_setting>
      <dl_setting var="controller.Vm" min="0.001" step="0.01" max="200" module="firmwares/beth/overo_twist_controller"  shortname="Vm">
      </dl_setting>
      <dl_setting var="controller.VM" min="100" step="10" max="600" module="firmwares/beth/overo_twist_controller"  shortname="VM">
      </dl_setting>
      <dl_setting var="controller.satval1" min="0" step="0.1" max="100" module="firmwares/beth/overo_twist_controller"  shortname="satval1">
      </dl_setting>
      <dl_setting var="controller.satval2" min="0.01" step="0.1" max="4" module="firmwares/beth/overo_twist_controller"  shortname="satval2">
      </dl_setting>
      <dl_setting var="controller.c" min="0.001" step="0.01" max="10" module="firmwares/beth/overo_twist_controller"  shortname="c">
      </dl_setting>

  <!--float ulim;  1
  float Vm; .1
  float VM; 300
  float satval1; 0.4
  float satval2; 1
  const float c;.04-->

      <dl_setting var="controller.armed" min="0" step="1" max="2" shortname ="mode"/>

    </dl_settings>
  </dl_settings>
</settings>

=== paparazzi/paparazzi/conf/settings/settings_booz2.xml
<!DOCTYPE settings SYSTEM "settings.dtd">

<settings>
  <dl_settings>

    <dl_settings NAME="Misc">
       <dl_setting var="autopilot_mode_auto2" min="0" step="1" max="12" module="autopilot" shortname="auto2" values="Fail|Kill|Rate|Att|Rate_rcC|Att_rcC|Att_C|Rate_Z|Att_Z|Hover|Hover_C|Hover_Z|Nav"/>
      <dl_setting var="kill_throttle" min="0" step="1" max="1" module="autopilot" values="Resurrect|Kill" handler="KillThrottle"/>
      <dl_setting var="autopilot_power_switch" min="0" step="1" max="1" module="autopilot" values="OFF|ON" handler="SetPowerSwitch">
        <strip_button name="POWER ON" icon="on.png" value="1"/>
        <strip_button name="POWER OFF" icon="off.png" value="0"/>
      </dl_setting>
      <dl_setting var="autopilot_rc" min="0" step="1" max="1" module="autopilot" values="RC OFF|RC ON">
        <strip_button name="RC ON" value="1"/>
        <strip_button name="RC OFF" value="0"/>
      </dl_setting>
    </dl_settings>

    <dl_settings NAME="Rate Loop">
      <dl_setting var="stabilization_rate_gain.p" min="1" step="1" max="1000" module="stabilization/stabilization_rate" shortname="gain p"/>
      <dl_setting var="stabilization_rate_gain.q" min="1" step="1" max="1000" module="stabilization/stabilization_rate" shortname="gain q"/>
      <dl_setting var="stabilization_rate_gain.r" min="1" step="1" max="1000" module="stabilization/stabilization_rate" shortname="gain r"/>
    </dl_settings>


    <dl_settings NAME="Att Loop">
      <dl_setting var="stabilization_gains.p.x" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude" shortname="pgain phi" />
      <dl_setting var="stabilization_gains.d.x" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude" shortname="dgain p"/>
      <dl_setting var="stabilization_gains.i.x" min="0" step="1" max="400"    module="stabilization/stabilization_attitude" shortname="igain phi" handler="SetKiPhi"/>
      <dl_setting var="stabilization_gains.dd.x" min="0" step="1" max="1000" module="stabilization/stabilization_attitude" shortname="ddgain p"/>
      <dl_setting var="stabilization_gains.p.y" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude" shortname="pgain theta"/>
      <dl_setting var="stabilization_gains.d.y" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude" shortname="dgain q"/>
      <dl_setting var="stabilization_gains.i.y" min="0"  step="1" max="400"    module="stabilization/stabilization_attitude" shortname="igain theta"/>
      <dl_setting var="stabilization_gains.dd.y" min="0"    step="1" max="1000"  module="stabilization/stabilization_attitude" shortname="ddgain q"/>
      <dl_setting var="stabilization_gains.p.z" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude" shortname="pgain psi"/>
      <dl_setting var="stabilization_gains.d.z" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude" shortname="dgain r"/>
      <dl_setting var="stabilization_gains.i.z" min="0"  step="1" max="400"    module="stabilization/stabilization_attitude" shortname="igain psi"/>
      <dl_setting var="stabilization_gains.dd.z" min="0" step="1" max="1000"  module="stabilization/stabilization_attitude" shortname="ddgain r"/>
    </dl_settings>

    <dl_settings NAME="Vert Loop">
      <dl_setting var="guidance_v_kp" min="0" step="1" max="600"   module="guidance/guidance_v" shortname="kp"/>
      <dl_setting var="guidance_v_kd" min="0" step="1" max="600"   module="guidance/guidance_v" shortname="kd"/>
      <dl_setting var="guidance_v_ki" min="0" step="1" max="300"   module="guidance/guidance_v" shortname="ki" handler="SetKi" />
      <dl_setting var="guidance_v_z_sp" min="-5" step="0.5" max="3" module="guidance/guidance_v" shortname="sp" unit="2e-8m" alt_unit="m" alt_unit_coef="0.00390625"/>
      <dl_setting var="guidance_v_nominal_throttle" min="0.1" step="0.01" max="0.9" module="guidance/guidance_v" shortname="nominal_throttle" handler="SetNominalHoverThrottle" alt_unit="%" alt_unit_coef="0.000104167"/>
      <dl_setting var="ins_vf_realign" min="0" step="1" max="1" module="subsystems/ins" shortname="vf_realign" values="OFF|ON"/>
   </dl_settings>

   <dl_settings NAME="Horiz Loop">
      <dl_setting var="guidance_h_pos_sp.x" MIN="-10" MAX="10" STEP="1"  module="guidance/guidance_h" shortname="sp_x_ned" unit="1/2^8m" alt_unit="m" alt_unit_coef="0.00390625"/>
      <dl_setting var="guidance_h_pos_sp.y" MIN="-10" MAX="10" STEP="1"  module="guidance/guidance_h" shortname="sp_y_ned" unit="1/2^8m" alt_unit="m" alt_unit_coef="0.00390625"/>
      <dl_setting var="guidance_h_psi_sp" MIN="-180" MAX="180" STEP="5"  module="guidance/guidance_h" shortname="sp_psi" unit="1/2^20r" alt_unit="deg" alt_unit_coef="0.000054641513360"/>
      <dl_setting var="guidance_h_pgain" min="0" step="1" max="400" module="guidance/guidance_h" shortname="kp"/>
      <dl_setting var="guidance_h_dgain" min="0" step="1" max="400" module="guidance/guidance_h" shortname="kd"/>
      <dl_setting var="guidance_h_igain" min="0" step="1" max="400" module="guidance/guidance_h" shortname="ki" handler="SetKi"/>
      <dl_setting var="guidance_h_again" min="0" step="1" max="400" module="guidance/guidance_h" shortname="ka"/>
      <dl_setting var="ins_hf_realign" min="0" step="1" max="1" module="subsystems/ins" shortname="hf_realign" values="OFF|ON"/>
   </dl_settings>

   <dl_settings NAME="NAV">
     <dl_setting var="flight_altitude" MIN="0" STEP="0.1" MAX="400" module="navigation" unit="m" handler="SetFlightAltitude"/>
     <dl_setting var="nav_heading" MIN="0" STEP="1" MAX="360" module="navigation" unit="1/2^12r" alt_unit="deg" alt_unit_coef="0.0139882"/>
     <dl_setting var="nav_radius" MIN="-150" STEP="0.1" MAX="150" module="navigation" unit="m"/>
   </dl_settings>


  </dl_settings>
</settings>

=== paparazzi/paparazzi/conf/settings/control/ctl_adaptive.xml
<!DOCTYPE settings SYSTEM "../settings.dtd">

<!-- A conf to use to tune a new A/C -->

<settings>
  <dl_settings>

    <dl_settings NAME="control">
      <dl_settings NAME="attitude">
        <dl_setting MAX="15000" MIN="0" STEP="250" VAR="h_ctl_roll_attitude_gain" shortname="roll_pgain" param="H_CTL_ROLL_ATTITUDE_GAIN" module="stabilization/stabilization_attitude"/>
        <dl_setting MAX="15000" MIN="0" STEP="250" VAR="h_ctl_roll_rate_gain" shortname="roll_dgain" param="H_CTL_ROLL_RATE_GAIN" module="stabilization/stabilization_attitude"/>
        <dl_setting MAX="5000" MIN="0" STEP="10" VAR="h_ctl_roll_igain" shortname="roll_igain" param="H_CTL_ROLL_IGAIN" handler="SetRollIGain" module="stabilization/stabilization_adaptive"/>
        <dl_setting MAX="25000" MIN="0" STEP="250" VAR="h_ctl_pitch_pgain" shortname="pitch_pgain" param="H_CTL_PITCH_PGAIN" module="stabilization/stabilization_attitude"/>
        <dl_setting MAX="50000" MIN="0" STEP="250" VAR="h_ctl_pitch_dgain" shortname="pitch_dgain" param="H_CTL_PITCH_DGAIN" module="stabilization/stabilization_attitude"/>
        <dl_setting MAX="5000" MIN="0" STEP="10" VAR="h_ctl_pitch_igain" shortname="pitch_igain" param="H_CTL_PITCH_IGAIN" handler="SetPitchIGain" module="stabilization/stabilization_adaptive"/>
        <dl_setting MAX=".3" MIN="0." STEP="0.001" VAR="h_ctl_pitch_of_roll" shortname="pitch_of_roll" param="H_CTL_PITCH_OF_ROLL" module="stabilization/stabilization_attitude"/>
        <dl_setting MAX="5000" MIN="0" STEP="100" VAR="h_ctl_aileron_of_throttle" shortname="aileron_of_throttle" module="stabilization/stabilization_adaptive"/>

        <dl_setting MAX="60" MIN="0" STEP="1." VAR="h_ctl_roll_max_setpoint" shortname="max_roll" param="H_CTL_ROLL_MAX_SETPOINT" unit="rad" alt_unit="deg"/>
        <dl_setting MAX="1" MIN="0" STEP="1" var="use_airspeed_ratio" values="FALSE|TRUE"/>
      </dl_settings>

      <dl_settings NAME="feedforward">
        <dl_setting MAX="5000" MIN="0" STEP="10" VAR="h_ctl_roll_Kffa" shortname="roll_Kffa" param="H_CTL_ROLL_KFFA"/>
        <dl_setting MAX="5000" MIN="0" STEP="10" VAR="h_ctl_roll_Kffd" shortname="roll_Kffd" param="H_CTL_ROLL_KFFD"/>
        <dl_setting MAX="5000" MIN="0" STEP="10" VAR="h_ctl_pitch_Kffa" shortname="pitch_Kffa" param="H_CTL_PITCH_KFFA"/>
        <dl_setting MAX="5000" MIN="0" STEP="10" VAR="h_ctl_pitch_Kffd" shortname="pitch_Kffd" param="H_CTL_PITCH_KFFD"/>
      </dl_settings>
    </dl_settings>
  </dl_settings>
</settings>

=== paparazzi/paparazzi/conf/settings/control/stabilization_att_indi.xml
<!DOCTYPE settings SYSTEM "../settings.dtd">
<settings>
  <dl_settings>
    <dl_settings NAME="indi">
      <dl_setting var="indi.reference_acceleration.err_p" min="0" step="1" max="500" module="stabilization/stabilization_attitude_quat_indi" shortname="kp_p"/>
      <dl_setting var="indi.reference_acceleration.rate_p" min="0" step="0.1" max="100" module="stabilization/stabilization_attitude_quat_indi" shortname="kd_p"/>
      <dl_setting var="indi.g1.p" min="0" step="1" max="500" module="stabilization/stabilization_attitude_quat_indi" shortname="ctl_eff_p"/>
      <dl_setting var="indi.reference_acceleration.err_q" min="0" step="1" max="500" module="stabilization/stabilization_attitude_quat_indi" shortname="kp_q"/>
      <dl_setting var="indi.reference_acceleration.rate_q" min="0" step="0.1" max="100" module="stabilization/stabilization_attitude_quat_indi" shortname="kd_q"/>
      <dl_setting var="indi.g1.q" min="0" step="1" max="500" module="stabilization/stabilization_attitude_quat_indi" shortname="ctl_eff_q"/>
      <dl_setting var="indi.reference_acceleration.err_r" min="0" step="1" max="500" module="stabilization/stabilization_attitude_quat_indi" shortname="kp_r"/>
      <dl_setting var="indi.reference_acceleration.rate_r" min="0" step="0.1" max="100" module="stabilization/stabilization_attitude_quat_indi" shortname="kd_r"/>
      <dl_setting var="indi.g1.r" min="0" step="1" max="500" module="stabilization/stabilization_attitude_quat_indi" shortname="ctl_eff_r"/>
      <dl_setting var="indi.adaptive" min="0" step="1" max="1" module="stabilization/stabilization_attitude_quat_indi" shortname="adaptive" values="FALSE|TRUE" param="ADAPTIVE_INDI"/>
<!--       <dl_setting var="indi.lambda_inv" min="1" step="1000" max="1000000000" module="stabilization/stabilization_attitude_quat_indi" shortname="lambda_inv"/> -->
    </dl_settings>
  </dl_settings>
</settings>

=== paparazzi/paparazzi/conf/settings/test_settings.xml
<!DOCTYPE settings SYSTEM "settings.dtd">

<settings>
  <dl_settings>
    <dl_settings NAME="Group1">

      <dl_setting var="setting_a" min="0" step="1" max="42" shortname ="a" module="test/subsystems/test_settings"/>
      <dl_setting var="setting_b" min="0" step="1" max="42" shortname ="b" persistent="true"/>
      <dl_setting var="setting_c" min="0" step="1" max="42" shortname ="c" persistent="true"/>
      <dl_setting var="setting_d" min="0" step="1" max="42" shortname ="d" persistent="true" />
      <dl_setting var="settings_store_now" min="0" step="1" max="1" shortname ="store" handler="StoreSettings" module="subsystems/settings"/>

    </dl_settings>
  </dl_settings>
</settings>

=== paparazzi/paparazzi/conf/settings/control/stabilization_att_int.xml
<!DOCTYPE settings SYSTEM "../settings.dtd">

<settings>
  <dl_settings>

    <dl_settings NAME="Att Loop">
      <dl_setting var="stabilization_gains.p.x" min="1" step="1" max="8000"   module="stabilization/stabilization_attitude_common_int" shortname="pgain phi" param="STABILIZATION_ATTITUDE_PHI_PGAIN"/>
      <dl_setting var="stabilization_gains.d.x" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="dgain p" param="STABILIZATION_ATTITUDE_PHI_DGAIN"/>
      <dl_setting var="stabilization_gains.i.x" min="0" step="1" max="800"    module="stabilization/stabilization_attitude_common_int" shortname="igain phi" param="STABILIZATION_ATTITUDE_PHI_IGAIN" />
      <dl_setting var="stabilization_gains.dd.x" min="0" step="1" max="1000" module="stabilization/stabilization_attitude_common_int" shortname="ddgain p" param="STABILIZATION_ATTITUDE_PHI_DDGAIN"/>
      <dl_setting var="stabilization_gains.p.y" min="1" step="1" max="8000"   module="stabilization/stabilization_attitude_common_int" shortname="pgain theta" param="STABILIZATION_ATTITUDE_THETA_PGAIN"/>
      <dl_setting var="stabilization_gains.d.y" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="dgain q" param="STABILIZATION_ATTITUDE_THETA_DGAIN"/>
      <dl_setting var="stabilization_gains.i.y" min="0"  step="1" max="800"    module="stabilization/stabilization_attitude_common_int" shortname="igain theta" param="STABILIZATION_ATTITUDE_THETA_IGAIN"/>
      <dl_setting var="stabilization_gains.dd.y" min="0"    step="1" max="1000"  module="stabilization/stabilization_attitude_common_int" shortname="ddgain q" param="STABILIZATION_ATTITUDE_THETA_DDGAIN"/>
      <dl_setting var="stabilization_gains.p.z" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="pgain psi" param="STABILIZATION_ATTITUDE_PSI_PGAIN"/>
      <dl_setting var="stabilization_gains.d.z" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="dgain r" param="STABILIZATION_ATTITUDE_PSI_DGAIN"/>
      <dl_setting var="stabilization_gains.i.z" min="0"  step="1" max="400"    module="stabilization/stabilization_attitude_common_int" shortname="igain psi" param="STABILIZATION_ATTITUDE_PSI_IGAIN"/>
      <dl_setting var="stabilization_gains.dd.z" min="0" step="1" max="1000"  module="stabilization/stabilization_attitude_common_int" shortname="ddgain r" param="STABILIZATION_ATTITUDE_PSI_DDGAIN"/>
    </dl_settings>

  </dl_settings>
</settings>

=== paparazzi/paparazzi/conf/settings/control/stabilization_att_int_quat.xml
<!DOCTYPE settings SYSTEM "../settings.dtd">

<settings>
  <dl_settings>

    <dl_settings NAME="Att Loop">
      <dl_setting var="stabilization_gains.p.x" min="1" step="1" max="8000"   module="stabilization/stabilization_attitude_common_int" shortname="pgain phi" param="STABILIZATION_ATTITUDE_PHI_PGAIN"/>
      <dl_setting var="stabilization_gains.d.x" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="dgain p" param="STABILIZATION_ATTITUDE_PHI_DGAIN"/>
      <dl_setting var="stabilization_gains.i.x" min="0" step="1" max="800"    module="stabilization/stabilization_attitude_common_int" shortname="igain phi" param="STABILIZATION_ATTITUDE_PHI_IGAIN"/>
      <dl_setting var="stabilization_gains.dd.x" min="0" step="1" max="1000" module="stabilization/stabilization_attitude_common_int" shortname="ddgain p" param="STABILIZATION_ATTITUDE_PHI_DDGAIN"/>
      <dl_setting var="stabilization_gains.p.y" min="1" step="1" max="8000"   module="stabilization/stabilization_attitude_common_int" shortname="pgain theta" param="STABILIZATION_ATTITUDE_THETA_PGAIN"/>
      <dl_setting var="stabilization_gains.d.y" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="dgain q" param="STABILIZATION_ATTITUDE_THETA_DGAIN"/>
      <dl_setting var="stabilization_gains.i.y" min="0"  step="1" max="800"    module="stabilization/stabilization_attitude_common_int" shortname="igain theta" param="STABILIZATION_ATTITUDE_THETA_IGAIN"/>
      <dl_setting var="stabilization_gains.dd.y" min="0"    step="1" max="1000"  module="stabilization/stabilization_attitude_common_int" shortname="ddgain q" param="STABILIZATION_ATTITUDE_THETA_DDGAIN"/>
      <dl_setting var="stabilization_gains.p.z" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="pgain psi" param="STABILIZATION_ATTITUDE_PSI_PGAIN"/>
      <dl_setting var="stabilization_gains.d.z" min="1" step="1" max="4000"   module="stabilization/stabilization_attitude_common_int" shortname="dgain r" param="STABILIZATION_ATTITUDE_PSI_DGAIN"/>
      <dl_setting var="stabilization_gains.i.z" min="0"  step="1" max="400"    module="stabilization/stabilization_attitude_common_int" shortname="igain psi" param="STABILIZATION_ATTITUDE_PSI_IGAIN"/>
      <dl_setting var="stabilization_gains.dd.z" min="0" step="1" max="1000"  module="stabilization/stabilization_attitude_common_int" shortname="ddgain r" param="STABILIZATION_ATTITUDE_PSI_DDGAIN"/>

      <dl_setting var="stab_att_ref_model.omega.p" min="1" step="1" max="1000" unit="rad/s" alt_unit="deg/s" module="stabilization/stabilization_attitude_ref_quat_int" shortname="omega p" param="STABILIZATION_ATTITUDE_REF_OMEGA_P" handler="SetOmegaP"/>
      <dl_setting var="stab_att_ref_model.zeta.p" min="0.5" step="0.05" max="1.2" module="stabilization/stabilization_attitude_ref_quat_int" shortname="zeta p" param="STABILIZATION_ATTITUDE_REF_ZETA_P" handler="SetZetaP"/>
      <dl_setting var="stab_att_ref_model.omega.q" min="1" step="1" max="1000" unit="rad/s" alt_unit="deg/s" module="stabilization/stabilization_attitude_ref_quat_int" shortname="omega q" param="STABILIZATION_ATTITUDE_REF_OMEGA_Q" handler="SetOmegaQ"/>
      <dl_setting var="stab_att_ref_model.zeta.q" min="0.5" step="0.05" max="1.2" module="stabilization/stabilization_attitude_ref_quat_int" shortname="zeta q" param="STABILIZATION_ATTITUDE_REF_ZETA_Q" handler="SetZetaQ"/>
      <dl_setting var="stab_att_ref_model.omega.r" min="1" step="1" max="1000" unit="rad/s" alt_unit="deg/s" module="stabilization/stabilization_attitude_ref_quat_int" shortname="omega r" param="STABILIZATION_ATTITUDE_REF_OMEGA_P" handler="SetOmegaR"/>
      <dl_setting var="stab_att_ref_model.zeta.r" min="0.5" step="0.05" max="1.2" module="stabilization/stabilization_attitude_ref_quat_int" shortname="zeta r" param="STABILIZATION_ATTITUDE_REF_ZETA_R" handler="SetZetaR"/>
    </dl_settings>

  </dl_settings>
</settings>
